// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: academic/archive/v1/archive.proto

package academicarchivev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ObservationReference 绑定不可变观察内容和精确作用域，不包含学生数据正文。
type ObservationReference struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ObservationId  string                 `protobuf:"bytes,1,opt,name=observation_id,json=observationId,proto3" json:"observation_id,omitempty"`
	ContentSha256  string                 `protobuf:"bytes,2,opt,name=content_sha256,json=contentSha256,proto3" json:"content_sha256,omitempty"`
	Provider       string                 `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	EducationLevel string                 `protobuf:"bytes,4,opt,name=education_level,json=educationLevel,proto3" json:"education_level,omitempty"`
	Kind           string                 `protobuf:"bytes,5,opt,name=kind,proto3" json:"kind,omitempty"`
	PeriodId       string                 `protobuf:"bytes,6,opt,name=period_id,json=periodId,proto3" json:"period_id,omitempty"`
	ObservedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ObservationReference) Reset() {
	*x = ObservationReference{}
	mi := &file_academic_archive_v1_archive_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObservationReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObservationReference) ProtoMessage() {}

func (x *ObservationReference) ProtoReflect() protoreflect.Message {
	mi := &file_academic_archive_v1_archive_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObservationReference.ProtoReflect.Descriptor instead.
func (*ObservationReference) Descriptor() ([]byte, []int) {
	return file_academic_archive_v1_archive_proto_rawDescGZIP(), []int{0}
}

func (x *ObservationReference) GetObservationId() string {
	if x != nil {
		return x.ObservationId
	}
	return ""
}

func (x *ObservationReference) GetContentSha256() string {
	if x != nil {
		return x.ContentSha256
	}
	return ""
}

func (x *ObservationReference) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ObservationReference) GetEducationLevel() string {
	if x != nil {
		return x.EducationLevel
	}
	return ""
}

func (x *ObservationReference) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ObservationReference) GetPeriodId() string {
	if x != nil {
		return x.PeriodId
	}
	return ""
}

func (x *ObservationReference) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

type GetObservationReceiptsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 服务端限制单次最多一百条，只允许内部平台身份调用。
	Observations  []*ObservationReference `protobuf:"bytes,1,rep,name=observations,proto3" json:"observations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetObservationReceiptsRequest) Reset() {
	*x = GetObservationReceiptsRequest{}
	mi := &file_academic_archive_v1_archive_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObservationReceiptsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObservationReceiptsRequest) ProtoMessage() {}

func (x *GetObservationReceiptsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_academic_archive_v1_archive_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObservationReceiptsRequest.ProtoReflect.Descriptor instead.
func (*GetObservationReceiptsRequest) Descriptor() ([]byte, []int) {
	return file_academic_archive_v1_archive_proto_rawDescGZIP(), []int{1}
}

func (x *GetObservationReceiptsRequest) GetObservations() []*ObservationReference {
	if x != nil {
		return x.Observations
	}
	return nil
}

type GetObservationReceiptsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Receipts      []*ObservationReceipt  `protobuf:"bytes,1,rep,name=receipts,proto3" json:"receipts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetObservationReceiptsResponse) Reset() {
	*x = GetObservationReceiptsResponse{}
	mi := &file_academic_archive_v1_archive_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObservationReceiptsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObservationReceiptsResponse) ProtoMessage() {}

func (x *GetObservationReceiptsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_academic_archive_v1_archive_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObservationReceiptsResponse.ProtoReflect.Descriptor instead.
func (*GetObservationReceiptsResponse) Descriptor() ([]byte, []int) {
	return file_academic_archive_v1_archive_proto_rawDescGZIP(), []int{2}
}

func (x *GetObservationReceiptsResponse) GetReceipts() []*ObservationReceipt {
	if x != nil {
		return x.Receipts
	}
	return nil
}

type ObservationReceipt struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Observation *ObservationReference  `protobuf:"bytes,1,opt,name=observation,proto3" json:"observation,omitempty"`
	// State 取值为 not_found、committed 或 rejected，不以队列接收冒充落库。
	State string `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	// ResultCode 使用 applied、unchanged 或固定拒绝类别。
	ResultCode    string                 `protobuf:"bytes,3,opt,name=result_code,json=resultCode,proto3" json:"result_code,omitempty"`
	RecordCount   uint64                 `protobuf:"varint,4,opt,name=record_count,json=recordCount,proto3" json:"record_count,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObservationReceipt) Reset() {
	*x = ObservationReceipt{}
	mi := &file_academic_archive_v1_archive_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObservationReceipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObservationReceipt) ProtoMessage() {}

func (x *ObservationReceipt) ProtoReflect() protoreflect.Message {
	mi := &file_academic_archive_v1_archive_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObservationReceipt.ProtoReflect.Descriptor instead.
func (*ObservationReceipt) Descriptor() ([]byte, []int) {
	return file_academic_archive_v1_archive_proto_rawDescGZIP(), []int{3}
}

func (x *ObservationReceipt) GetObservation() *ObservationReference {
	if x != nil {
		return x.Observation
	}
	return nil
}

func (x *ObservationReceipt) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ObservationReceipt) GetResultCode() string {
	if x != nil {
		return x.ResultCode
	}
	return ""
}

func (x *ObservationReceipt) GetRecordCount() uint64 {
	if x != nil {
		return x.RecordCount
	}
	return 0
}

func (x *ObservationReceipt) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

var File_academic_archive_v1_archive_proto protoreflect.FileDescriptor

const file_academic_archive_v1_archive_proto_rawDesc = "" +
	"\n" +
	"!academic/archive/v1/archive.proto\x12\x13academic.archive.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x97\x02\n" +
	"\x14ObservationReference\x12%\n" +
	"\x0eobservation_id\x18\x01 \x01(\tR\robservationId\x12%\n" +
	"\x0econtent_sha256\x18\x02 \x01(\tR\rcontentSha256\x12\x1a\n" +
	"\bprovider\x18\x03 \x01(\tR\bprovider\x12'\n" +
	"\x0feducation_level\x18\x04 \x01(\tR\x0eeducationLevel\x12\x12\n" +
	"\x04kind\x18\x05 \x01(\tR\x04kind\x12\x1b\n" +
	"\tperiod_id\x18\x06 \x01(\tR\bperiodId\x12;\n" +
	"\vobserved_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"observedAt\"n\n" +
	"\x1dGetObservationReceiptsRequest\x12M\n" +
	"\fobservations\x18\x01 \x03(\v2).academic.archive.v1.ObservationReferenceR\fobservations\"e\n" +
	"\x1eGetObservationReceiptsResponse\x12C\n" +
	"\breceipts\x18\x01 \x03(\v2'.academic.archive.v1.ObservationReceiptR\breceipts\"\xfa\x01\n" +
	"\x12ObservationReceipt\x12K\n" +
	"\vobservation\x18\x01 \x01(\v2).academic.archive.v1.ObservationReferenceR\vobservation\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x1f\n" +
	"\vresult_code\x18\x03 \x01(\tR\n" +
	"resultCode\x12!\n" +
	"\frecord_count\x18\x04 \x01(\x04R\vrecordCount\x12=\n" +
	"\fcompleted_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt2\x9c\x01\n" +
	"\x16AcademicArchiveService\x12\x81\x01\n" +
	"\x16GetObservationReceipts\x122.academic.archive.v1.GetObservationReceiptsRequest\x1a3.academic.archive.v1.GetObservationReceiptsResponseBRZPgithub.com/LDouble/campus-academic-api/pkg/academic/archive/v1;academicarchivev1b\x06proto3"

var (
	file_academic_archive_v1_archive_proto_rawDescOnce sync.Once
	file_academic_archive_v1_archive_proto_rawDescData []byte
)

func file_academic_archive_v1_archive_proto_rawDescGZIP() []byte {
	file_academic_archive_v1_archive_proto_rawDescOnce.Do(func() {
		file_academic_archive_v1_archive_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_academic_archive_v1_archive_proto_rawDesc), len(file_academic_archive_v1_archive_proto_rawDesc)))
	})
	return file_academic_archive_v1_archive_proto_rawDescData
}

var file_academic_archive_v1_archive_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_academic_archive_v1_archive_proto_goTypes = []any{
	(*ObservationReference)(nil),           // 0: academic.archive.v1.ObservationReference
	(*GetObservationReceiptsRequest)(nil),  // 1: academic.archive.v1.GetObservationReceiptsRequest
	(*GetObservationReceiptsResponse)(nil), // 2: academic.archive.v1.GetObservationReceiptsResponse
	(*ObservationReceipt)(nil),             // 3: academic.archive.v1.ObservationReceipt
	(*timestamppb.Timestamp)(nil),          // 4: google.protobuf.Timestamp
}
var file_academic_archive_v1_archive_proto_depIdxs = []int32{
	4, // 0: academic.archive.v1.ObservationReference.observed_at:type_name -> google.protobuf.Timestamp
	0, // 1: academic.archive.v1.GetObservationReceiptsRequest.observations:type_name -> academic.archive.v1.ObservationReference
	3, // 2: academic.archive.v1.GetObservationReceiptsResponse.receipts:type_name -> academic.archive.v1.ObservationReceipt
	0, // 3: academic.archive.v1.ObservationReceipt.observation:type_name -> academic.archive.v1.ObservationReference
	4, // 4: academic.archive.v1.ObservationReceipt.completed_at:type_name -> google.protobuf.Timestamp
	1, // 5: academic.archive.v1.AcademicArchiveService.GetObservationReceipts:input_type -> academic.archive.v1.GetObservationReceiptsRequest
	2, // 6: academic.archive.v1.AcademicArchiveService.GetObservationReceipts:output_type -> academic.archive.v1.GetObservationReceiptsResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_academic_archive_v1_archive_proto_init() }
func file_academic_archive_v1_archive_proto_init() {
	if File_academic_archive_v1_archive_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_academic_archive_v1_archive_proto_rawDesc), len(file_academic_archive_v1_archive_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_academic_archive_v1_archive_proto_goTypes,
		DependencyIndexes: file_academic_archive_v1_archive_proto_depIdxs,
		MessageInfos:      file_academic_archive_v1_archive_proto_msgTypes,
	}.Build()
	File_academic_archive_v1_archive_proto = out.File
	file_academic_archive_v1_archive_proto_goTypes = nil
	file_academic_archive_v1_archive_proto_depIdxs = nil
}
