// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: academic/archive/v1/archive.proto

package academicarchivev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AcademicArchiveService_GetObservationReceipts_FullMethodName = "/academic.archive.v1.AcademicArchiveService/GetObservationReceipts"
)

// AcademicArchiveServiceClient is the client API for AcademicArchiveService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AcademicArchiveService 只提供可信平台调用方需要的归档元数据回执。
type AcademicArchiveServiceClient interface {
	GetObservationReceipts(ctx context.Context, in *GetObservationReceiptsRequest, opts ...grpc.CallOption) (*GetObservationReceiptsResponse, error)
}

type academicArchiveServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAcademicArchiveServiceClient(cc grpc.ClientConnInterface) AcademicArchiveServiceClient {
	return &academicArchiveServiceClient{cc}
}

func (c *academicArchiveServiceClient) GetObservationReceipts(ctx context.Context, in *GetObservationReceiptsRequest, opts ...grpc.CallOption) (*GetObservationReceiptsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetObservationReceiptsResponse)
	err := c.cc.Invoke(ctx, AcademicArchiveService_GetObservationReceipts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AcademicArchiveServiceServer is the server API for AcademicArchiveService service.
// All implementations must embed UnimplementedAcademicArchiveServiceServer
// for forward compatibility.
//
// AcademicArchiveService 只提供可信平台调用方需要的归档元数据回执。
type AcademicArchiveServiceServer interface {
	GetObservationReceipts(context.Context, *GetObservationReceiptsRequest) (*GetObservationReceiptsResponse, error)
	mustEmbedUnimplementedAcademicArchiveServiceServer()
}

// UnimplementedAcademicArchiveServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAcademicArchiveServiceServer struct{}

func (UnimplementedAcademicArchiveServiceServer) GetObservationReceipts(context.Context, *GetObservationReceiptsRequest) (*GetObservationReceiptsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetObservationReceipts not implemented")
}
func (UnimplementedAcademicArchiveServiceServer) mustEmbedUnimplementedAcademicArchiveServiceServer() {
}
func (UnimplementedAcademicArchiveServiceServer) testEmbeddedByValue() {}

// UnsafeAcademicArchiveServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AcademicArchiveServiceServer will
// result in compilation errors.
type UnsafeAcademicArchiveServiceServer interface {
	mustEmbedUnimplementedAcademicArchiveServiceServer()
}

func RegisterAcademicArchiveServiceServer(s grpc.ServiceRegistrar, srv AcademicArchiveServiceServer) {
	// If the following call panics, it indicates UnimplementedAcademicArchiveServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AcademicArchiveService_ServiceDesc, srv)
}

func _AcademicArchiveService_GetObservationReceipts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetObservationReceiptsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcademicArchiveServiceServer).GetObservationReceipts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AcademicArchiveService_GetObservationReceipts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcademicArchiveServiceServer).GetObservationReceipts(ctx, req.(*GetObservationReceiptsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AcademicArchiveService_ServiceDesc is the grpc.ServiceDesc for AcademicArchiveService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AcademicArchiveService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "academic.archive.v1.AcademicArchiveService",
	HandlerType: (*AcademicArchiveServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetObservationReceipts",
			Handler:    _AcademicArchiveService_GetObservationReceipts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "academic/archive/v1/archive.proto",
}
