// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: academic/analytics/v1/analytics.proto

package academicanalyticsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PublicationMetadata struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	BatchId           uint64                 `protobuf:"varint,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	SourceCutoffAt    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=source_cutoff_at,json=sourceCutoffAt,proto3" json:"source_cutoff_at,omitempty"`
	PublishedAt       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	RuleVersion       string                 `protobuf:"bytes,4,opt,name=rule_version,json=ruleVersion,proto3" json:"rule_version,omitempty"`
	MinimumSampleSize int64                  `protobuf:"varint,5,opt,name=minimum_sample_size,json=minimumSampleSize,proto3" json:"minimum_sample_size,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PublicationMetadata) Reset() {
	*x = PublicationMetadata{}
	mi := &file_academic_analytics_v1_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicationMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicationMetadata) ProtoMessage() {}

func (x *PublicationMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_academic_analytics_v1_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicationMetadata.ProtoReflect.Descriptor instead.
func (*PublicationMetadata) Descriptor() ([]byte, []int) {
	return file_academic_analytics_v1_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *PublicationMetadata) GetBatchId() uint64 {
	if x != nil {
		return x.BatchId
	}
	return 0
}

func (x *PublicationMetadata) GetSourceCutoffAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SourceCutoffAt
	}
	return nil
}

func (x *PublicationMetadata) GetPublishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PublishedAt
	}
	return nil
}

func (x *PublicationMetadata) GetRuleVersion() string {
	if x != nil {
		return x.RuleVersion
	}
	return ""
}

func (x *PublicationMetadata) GetMinimumSampleSize() int64 {
	if x != nil {
		return x.MinimumSampleSize
	}
	return 0
}

type GradeDistribution struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	NumericFailCount    int64                  `protobuf:"varint,1,opt,name=numeric_fail_count,json=numericFailCount,proto3" json:"numeric_fail_count,omitempty"`
	Score_60_69Count    int64                  `protobuf:"varint,2,opt,name=score_60_69_count,json=score6069Count,proto3" json:"score_60_69_count,omitempty"`
	Score_70_79Count    int64                  `protobuf:"varint,3,opt,name=score_70_79_count,json=score7079Count,proto3" json:"score_70_79_count,omitempty"`
	Score_80_89Count    int64                  `protobuf:"varint,4,opt,name=score_80_89_count,json=score8089Count,proto3" json:"score_80_89_count,omitempty"`
	Score_90_100Count   int64                  `protobuf:"varint,5,opt,name=score_90_100_count,json=score90100Count,proto3" json:"score_90_100_count,omitempty"`
	LevelExcellentCount int64                  `protobuf:"varint,6,opt,name=level_excellent_count,json=levelExcellentCount,proto3" json:"level_excellent_count,omitempty"`
	LevelGoodCount      int64                  `protobuf:"varint,7,opt,name=level_good_count,json=levelGoodCount,proto3" json:"level_good_count,omitempty"`
	LevelMediumCount    int64                  `protobuf:"varint,8,opt,name=level_medium_count,json=levelMediumCount,proto3" json:"level_medium_count,omitempty"`
	LevelPassCount      int64                  `protobuf:"varint,9,opt,name=level_pass_count,json=levelPassCount,proto3" json:"level_pass_count,omitempty"`
	LevelFailCount      int64                  `protobuf:"varint,10,opt,name=level_fail_count,json=levelFailCount,proto3" json:"level_fail_count,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GradeDistribution) Reset() {
	*x = GradeDistribution{}
	mi := &file_academic_analytics_v1_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GradeDistribution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradeDistribution) ProtoMessage() {}

func (x *GradeDistribution) ProtoReflect() protoreflect.Message {
	mi := &file_academic_analytics_v1_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradeDistribution.ProtoReflect.Descriptor instead.
func (*GradeDistribution) Descriptor() ([]byte, []int) {
	return file_academic_analytics_v1_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *GradeDistribution) GetNumericFailCount() int64 {
	if x != nil {
		return x.NumericFailCount
	}
	return 0
}

func (x *GradeDistribution) GetScore_60_69Count() int64 {
	if x != nil {
		return x.Score_60_69Count
	}
	return 0
}

func (x *GradeDistribution) GetScore_70_79Count() int64 {
	if x != nil {
		return x.Score_70_79Count
	}
	return 0
}

func (x *GradeDistribution) GetScore_80_89Count() int64 {
	if x != nil {
		return x.Score_80_89Count
	}
	return 0
}

func (x *GradeDistribution) GetScore_90_100Count() int64 {
	if x != nil {
		return x.Score_90_100Count
	}
	return 0
}

func (x *GradeDistribution) GetLevelExcellentCount() int64 {
	if x != nil {
		return x.LevelExcellentCount
	}
	return 0
}

func (x *GradeDistribution) GetLevelGoodCount() int64 {
	if x != nil {
		return x.LevelGoodCount
	}
	return 0
}

func (x *GradeDistribution) GetLevelMediumCount() int64 {
	if x != nil {
		return x.LevelMediumCount
	}
	return 0
}

func (x *GradeDistribution) GetLevelPassCount() int64 {
	if x != nil {
		return x.LevelPassCount
	}
	return 0
}

func (x *GradeDistribution) GetLevelFailCount() int64 {
	if x != nil {
		return x.LevelFailCount
	}
	return 0
}

type CoursePassRate struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	EducationLevel      string                 `protobuf:"bytes,1,opt,name=education_level,json=educationLevel,proto3" json:"education_level,omitempty"`
	CourseCode          string                 `protobuf:"bytes,2,opt,name=course_code,json=courseCode,proto3" json:"course_code,omitempty"`
	CourseName          string                 `protobuf:"bytes,3,opt,name=course_name,json=courseName,proto3" json:"course_name,omitempty"`
	TermCount           int64                  `protobuf:"varint,4,opt,name=term_count,json=termCount,proto3" json:"term_count,omitempty"`
	ValidCount          int64                  `protobuf:"varint,5,opt,name=valid_count,json=validCount,proto3" json:"valid_count,omitempty"`
	PassCount           int64                  `protobuf:"varint,6,opt,name=pass_count,json=passCount,proto3" json:"pass_count,omitempty"`
	FailCount           int64                  `protobuf:"varint,7,opt,name=fail_count,json=failCount,proto3" json:"fail_count,omitempty"`
	NumericScoreCount   int64                  `protobuf:"varint,8,opt,name=numeric_score_count,json=numericScoreCount,proto3" json:"numeric_score_count,omitempty"`
	NumericScoreSumX100 int64                  `protobuf:"varint,9,opt,name=numeric_score_sum_x100,json=numericScoreSumX100,proto3" json:"numeric_score_sum_x100,omitempty"`
	Distribution        *GradeDistribution     `protobuf:"bytes,10,opt,name=distribution,proto3" json:"distribution,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CoursePassRate) Reset() {
	*x = CoursePassRate{}
	mi := &file_academic_analytics_v1_analytics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoursePassRate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoursePassRate) ProtoMessage() {}

func (x *CoursePassRate) ProtoReflect() protoreflect.Message {
	mi := &file_academic_analytics_v1_analytics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoursePassRate.ProtoReflect.Descriptor instead.
func (*CoursePassRate) Descriptor() ([]byte, []int) {
	return file_academic_analytics_v1_analytics_proto_rawDescGZIP(), []int{2}
}

func (x *CoursePassRate) GetEducationLevel() string {
	if x != nil {
		return x.EducationLevel
	}
	return ""
}

func (x *CoursePassRate) GetCourseCode() string {
	if x != nil {
		return x.CourseCode
	}
	return ""
}

func (x *CoursePassRate) GetCourseName() string {
	if x != nil {
		return x.CourseName
	}
	return ""
}

func (x *CoursePassRate) GetTermCount() int64 {
	if x != nil {
		return x.TermCount
	}
	return 0
}

func (x *CoursePassRate) GetValidCount() int64 {
	if x != nil {
		return x.ValidCount
	}
	return 0
}

func (x *CoursePassRate) GetPassCount() int64 {
	if x != nil {
		return x.PassCount
	}
	return 0
}

func (x *CoursePassRate) GetFailCount() int64 {
	if x != nil {
		return x.FailCount
	}
	return 0
}

func (x *CoursePassRate) GetNumericScoreCount() int64 {
	if x != nil {
		return x.NumericScoreCount
	}
	return 0
}

func (x *CoursePassRate) GetNumericScoreSumX100() int64 {
	if x != nil {
		return x.NumericScoreSumX100
	}
	return 0
}

func (x *CoursePassRate) GetDistribution() *GradeDistribution {
	if x != nil {
		return x.Distribution
	}
	return nil
}

type InstructorPassRate struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	EducationLevel      string                 `protobuf:"bytes,1,opt,name=education_level,json=educationLevel,proto3" json:"education_level,omitempty"`
	CourseCode          string                 `protobuf:"bytes,2,opt,name=course_code,json=courseCode,proto3" json:"course_code,omitempty"`
	CourseName          string                 `protobuf:"bytes,3,opt,name=course_name,json=courseName,proto3" json:"course_name,omitempty"`
	TeacherKey          string                 `protobuf:"bytes,4,opt,name=teacher_key,json=teacherKey,proto3" json:"teacher_key,omitempty"`
	TeacherName         string                 `protobuf:"bytes,5,opt,name=teacher_name,json=teacherName,proto3" json:"teacher_name,omitempty"`
	TermCount           int64                  `protobuf:"varint,6,opt,name=term_count,json=termCount,proto3" json:"term_count,omitempty"`
	ClassCount          int64                  `protobuf:"varint,7,opt,name=class_count,json=classCount,proto3" json:"class_count,omitempty"`
	ValidCount          int64                  `protobuf:"varint,8,opt,name=valid_count,json=validCount,proto3" json:"valid_count,omitempty"`
	PassCount           int64                  `protobuf:"varint,9,opt,name=pass_count,json=passCount,proto3" json:"pass_count,omitempty"`
	FailCount           int64                  `protobuf:"varint,10,opt,name=fail_count,json=failCount,proto3" json:"fail_count,omitempty"`
	NumericScoreCount   int64                  `protobuf:"varint,11,opt,name=numeric_score_count,json=numericScoreCount,proto3" json:"numeric_score_count,omitempty"`
	NumericScoreSumX100 int64                  `protobuf:"varint,12,opt,name=numeric_score_sum_x100,json=numericScoreSumX100,proto3" json:"numeric_score_sum_x100,omitempty"`
	Distribution        *GradeDistribution     `protobuf:"bytes,13,opt,name=distribution,proto3" json:"distribution,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *InstructorPassRate) Reset() {
	*x = InstructorPassRate{}
	mi := &file_academic_analytics_v1_analytics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstructorPassRate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstructorPassRate) ProtoMessage() {}

func (x *InstructorPassRate) ProtoReflect() protoreflect.Message {
	mi := &file_academic_analytics_v1_analytics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstructorPassRate.ProtoReflect.Descriptor instead.
func (*InstructorPassRate) Descriptor() ([]byte, []int) {
	return file_academic_analytics_v1_analytics_proto_rawDescGZIP(), []int{3}
}

func (x *InstructorPassRate) GetEducationLevel() string {
	if x != nil {
		return x.EducationLevel
	}
	return ""
}

func (x *InstructorPassRate) GetCourseCode() string {
	if x != nil {
		return x.CourseCode
	}
	return ""
}

func (x *InstructorPassRate) GetCourseName() string {
	if x != nil {
		return x.CourseName
	}
	return ""
}

func (x *InstructorPassRate) GetTeacherKey() string {
	if x != nil {
		return x.TeacherKey
	}
	return ""
}

func (x *InstructorPassRate) GetTeacherName() string {
	if x != nil {
		return x.TeacherName
	}
	return ""
}

func (x *InstructorPassRate) GetTermCount() int64 {
	if x != nil {
		return x.TermCount
	}
	return 0
}

func (x *InstructorPassRate) GetClassCount() int64 {
	if x != nil {
		return x.ClassCount
	}
	return 0
}

func (x *InstructorPassRate) GetValidCount() int64 {
	if x != nil {
		return x.ValidCount
	}
	return 0
}

func (x *InstructorPassRate) GetPassCount() int64 {
	if x != nil {
		return x.PassCount
	}
	return 0
}

func (x *InstructorPassRate) GetFailCount() int64 {
	if x != nil {
		return x.FailCount
	}
	return 0
}

func (x *InstructorPassRate) GetNumericScoreCount() int64 {
	if x != nil {
		return x.NumericScoreCount
	}
	return 0
}

func (x *InstructorPassRate) GetNumericScoreSumX100() int64 {
	if x != nil {
		return x.NumericScoreSumX100
	}
	return 0
}

func (x *InstructorPassRate) GetDistribution() *GradeDistribution {
	if x != nil {
		return x.Distribution
	}
	return nil
}

type PassRateTrendPoint struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	EducationLevel      string                 `protobuf:"bytes,1,opt,name=education_level,json=educationLevel,proto3" json:"education_level,omitempty"`
	PeriodId            string                 `protobuf:"bytes,2,opt,name=period_id,json=periodId,proto3" json:"period_id,omitempty"`
	TermLabel           string                 `protobuf:"bytes,3,opt,name=term_label,json=termLabel,proto3" json:"term_label,omitempty"`
	TermCode            string                 `protobuf:"bytes,4,opt,name=term_code,json=termCode,proto3" json:"term_code,omitempty"`
	ValidCount          int64                  `protobuf:"varint,5,opt,name=valid_count,json=validCount,proto3" json:"valid_count,omitempty"`
	PassCount           int64                  `protobuf:"varint,6,opt,name=pass_count,json=passCount,proto3" json:"pass_count,omitempty"`
	FailCount           int64                  `protobuf:"varint,7,opt,name=fail_count,json=failCount,proto3" json:"fail_count,omitempty"`
	NumericScoreCount   int64                  `protobuf:"varint,8,opt,name=numeric_score_count,json=numericScoreCount,proto3" json:"numeric_score_count,omitempty"`
	NumericScoreSumX100 int64                  `protobuf:"varint,9,opt,name=numeric_score_sum_x100,json=numericScoreSumX100,proto3" json:"numeric_score_sum_x100,omitempty"`
	Distribution        *GradeDistribution     `protobuf:"bytes,10,opt,name=distribution,proto3" json:"distribution,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PassRateTrendPoint) Reset() {
	*x = PassRateTrendPoint{}
	mi := &file_academic_analytics_v1_analytics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PassRateTrendPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PassRateTrendPoint) ProtoMessage() {}

func (x *PassRateTrendPoint) ProtoReflect() protoreflect.Message {
	mi := &file_academic_analytics_v1_analytics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PassRateTrendPoint.ProtoReflect.Descriptor instead.
func (*PassRateTrendPoint) Descriptor() ([]byte, []int) {
	return file_academic_analytics_v1_analytics_proto_rawDescGZIP(), []int{4}
}

func (x *PassRateTrendPoint) GetEducationLevel() string {
	if x != nil {
		return x.EducationLevel
	}
	return ""
}

func (x *PassRateTrendPoint) GetPeriodId() string {
	if x != nil {
		return x.PeriodId
	}
	return ""
}

func (x *PassRateTrendPoint) GetTermLabel() string {
	if x != nil {
		return x.TermLabel
	}
	return ""
}

func (x *PassRateTrendPoint) GetTermCode() string {
	if x != nil {
		return x.TermCode
	}
	return ""
}

func (x *PassRateTrendPoint) GetValidCount() int64 {
	if x != nil {
		return x.ValidCount
	}
	return 0
}

func (x *PassRateTrendPoint) GetPassCount() int64 {
	if x != nil {
		return x.PassCount
	}
	return 0
}

func (x *PassRateTrendPoint) GetFailCount() int64 {
	if x != nil {
		return x.FailCount
	}
	return 0
}

func (x *PassRateTrendPoint) GetNumericScoreCount() int64 {
	if x != nil {
		return x.NumericScoreCount
	}
	return 0
}

func (x *PassRateTrendPoint) GetNumericScoreSumX100() int64 {
	if x != nil {
		return x.NumericScoreSumX100
	}
	return 0
}

func (x *PassRateTrendPoint) GetDistribution() *GradeDistribution {
	if x != nil {
		return x.Distribution
	}
	return nil
}

type PassRateTrend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseCode    string                 `protobuf:"bytes,1,opt,name=course_code,json=courseCode,proto3" json:"course_code,omitempty"`
	CourseName    string                 `protobuf:"bytes,2,opt,name=course_name,json=courseName,proto3" json:"course_name,omitempty"`
	TeacherKey    string                 `protobuf:"bytes,3,opt,name=teacher_key,json=teacherKey,proto3" json:"teacher_key,omitempty"`
	TeacherName   string                 `protobuf:"bytes,4,opt,name=teacher_name,json=teacherName,proto3" json:"teacher_name,omitempty"`
	Points        []*PassRateTrendPoint  `protobuf:"bytes,5,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PassRateTrend) Reset() {
	*x = PassRateTrend{}
	mi := &file_academic_analytics_v1_analytics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PassRateTrend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PassRateTrend) ProtoMessage() {}

func (x *PassRateTrend) ProtoReflect() protoreflect.Message {
	mi := &file_academic_analytics_v1_analytics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PassRateTrend.ProtoReflect.Descriptor instead.
func (*PassRateTrend) Descriptor() ([]byte, []int) {
	return file_academic_analytics_v1_analytics_proto_rawDescGZIP(), []int{5}
}

func (x *PassRateTrend) GetCourseCode() string {
	if x != nil {
		return x.CourseCode
	}
	return ""
}

func (x *PassRateTrend) GetCourseName() string {
	if x != nil {
		return x.CourseName
	}
	return ""
}

func (x *PassRateTrend) GetTeacherKey() string {
	if x != nil {
		return x.TeacherKey
	}
	return ""
}

func (x *PassRateTrend) GetTeacherName() string {
	if x != nil {
		return x.TeacherName
	}
	return ""
}

func (x *PassRateTrend) GetPoints() []*PassRateTrendPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

type AcademicStatisticsBatch struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status              string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	TriggerType         string                 `protobuf:"bytes,3,opt,name=trigger_type,json=triggerType,proto3" json:"trigger_type,omitempty"`
	TriggeredBy         *uint64                `protobuf:"varint,4,opt,name=triggered_by,json=triggeredBy,proto3,oneof" json:"triggered_by,omitempty"`
	TriggerNote         *string                `protobuf:"bytes,5,opt,name=trigger_note,json=triggerNote,proto3,oneof" json:"trigger_note,omitempty"`
	TriggerTaskId       *string                `protobuf:"bytes,6,opt,name=trigger_task_id,json=triggerTaskId,proto3,oneof" json:"trigger_task_id,omitempty"`
	SourceCutoffAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=source_cutoff_at,json=sourceCutoffAt,proto3" json:"source_cutoff_at,omitempty"`
	RuleVersion         string                 `protobuf:"bytes,8,opt,name=rule_version,json=ruleVersion,proto3" json:"rule_version,omitempty"`
	SourceRowCount      int64                  `protobuf:"varint,9,opt,name=source_row_count,json=sourceRowCount,proto3" json:"source_row_count,omitempty"`
	CourseStatCount     int64                  `protobuf:"varint,10,opt,name=course_stat_count,json=courseStatCount,proto3" json:"course_stat_count,omitempty"`
	InstructorStatCount int64                  `protobuf:"varint,11,opt,name=instructor_stat_count,json=instructorStatCount,proto3" json:"instructor_stat_count,omitempty"`
	ErrorSummary        *string                `protobuf:"bytes,12,opt,name=error_summary,json=errorSummary,proto3,oneof" json:"error_summary,omitempty"`
	StartedAt           *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt          *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=finished_at,json=finishedAt,proto3,oneof" json:"finished_at,omitempty"`
	PublishedAt         *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=published_at,json=publishedAt,proto3,oneof" json:"published_at,omitempty"`
	CreatedAt           *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt           *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AcademicStatisticsBatch) Reset() {
	*x = AcademicStatisticsBatch{}
	mi := &file_academic_analytics_v1_analytics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcademicStatisticsBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcademicStatisticsBatch) ProtoMessage() {}

func (x *AcademicStatisticsBatch) ProtoReflect() protoreflect.Message {
	mi := &file_academic_analytics_v1_analytics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcademicStatisticsBatch.ProtoReflect.Descriptor instead.
func (*AcademicStatisticsBatch) Descriptor() ([]byte, []int) {
	return file_academic_analytics_v1_analytics_proto_rawDescGZIP(), []int{6}
}

func (x *AcademicStatisticsBatch) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AcademicStatisticsBatch) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AcademicStatisticsBatch) GetTriggerType() string {
	if x != nil {
		return x.TriggerType
	}
	return ""
}

func (x *AcademicStatisticsBatch) GetTriggeredBy() uint64 {
	if x != nil && x.TriggeredBy != nil {
		return *x.TriggeredBy
	}
	return 0
}

func (x *AcademicStatisticsBatch) GetTriggerNote() string {
	if x != nil && x.TriggerNote != nil {
		return *x.TriggerNote
	}
	return ""
}

func (x *AcademicStatisticsBatch) GetTriggerTaskId() string {
	if x != nil && x.TriggerTaskId != nil {
		return *x.TriggerTaskId
	}
	return ""
}

func (x *AcademicStatisticsBatch) GetSourceCutoffAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SourceCutoffAt
	}
	return nil
}

func (x *AcademicStatisticsBatch) GetRuleVersion() string {
	if x != nil {
		return x.RuleVersion
	}
	return ""
}

func (x *AcademicStatisticsBatch) GetSourceRowCount() int64 {
	if x != nil {
		return x.SourceRowCount
	}
	return 0
}

func (x *AcademicStatisticsBatch) GetCourseStatCount() int64 {
	if x != nil {
		return x.CourseStatCount
	}
	return 0
}

func (x *AcademicStatisticsBatch) GetInstructorStatCount() int64 {
	if x != nil {
		return x.InstructorStatCount
	}
	return 0
}

func (x *AcademicStatisticsBatch) GetErrorSummary() string {
	if x != nil && x.ErrorSummary != nil {
		return *x.ErrorSummary
	}
	return ""
}

func (x *AcademicStatisticsBatch) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *AcademicStatisticsBatch) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

func (x *AcademicStatisticsBatch) GetPublishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PublishedAt
	}
	return nil
}

func (x *AcademicStatisticsBatch) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AcademicStatisticsBatch) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListCoursePassRatesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Keyword        string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	CourseCode     string                 `protobuf:"bytes,2,opt,name=course_code,json=courseCode,proto3" json:"course_code,omitempty"`
	TermCode       string                 `protobuf:"bytes,3,opt,name=term_code,json=termCode,proto3" json:"term_code,omitempty"`
	EducationLevel string                 `protobuf:"bytes,4,opt,name=education_level,json=educationLevel,proto3" json:"education_level,omitempty"`
	Page           int32                  `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	PageSize       int32                  `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListCoursePassRatesRequest) Reset() {
	*x = ListCoursePassRatesRequest{}
	mi := &file_academic_analytics_v1_analytics_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCoursePassRatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCoursePassRatesRequest) ProtoMessage() {}

func (x *ListCoursePassRatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_academic_analytics_v1_analytics_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCoursePassRatesRequest.ProtoReflect.Descriptor instead.
func (*ListCoursePassRatesRequest) Descriptor() ([]byte, []int) {
	return file_academic_analytics_v1_analytics_proto_rawDescGZIP(), []int{7}
}

func (x *ListCoursePassRatesRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *ListCoursePassRatesRequest) GetCourseCode() string {
	if x != nil {
		return x.CourseCode
	}
	return ""
}

func (x *ListCoursePassRatesRequest) GetTermCode() string {
	if x != nil {
		return x.TermCode
	}
	return ""
}

func (x *ListCoursePassRatesRequest) GetEducationLevel() string {
	if x != nil {
		return x.EducationLevel
	}
	return ""
}

func (x *ListCoursePassRatesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListCoursePassRatesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListCoursePassRatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *PublicationMetadata   `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Items         []*CoursePassRate      `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	Total         int64                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCoursePassRatesResponse) Reset() {
	*x = ListCoursePassRatesResponse{}
	mi := &file_academic_analytics_v1_analytics_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCoursePassRatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCoursePassRatesResponse) ProtoMessage() {}

func (x *ListCoursePassRatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_academic_analytics_v1_analytics_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCoursePassRatesResponse.ProtoReflect.Descriptor instead.
func (*ListCoursePassRatesResponse) Descriptor() ([]byte, []int) {
	return file_academic_analytics_v1_analytics_proto_rawDescGZIP(), []int{8}
}

func (x *ListCoursePassRatesResponse) GetMetadata() *PublicationMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ListCoursePassRatesResponse) GetItems() []*CoursePassRate {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListCoursePassRatesResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListCoursePassRatesResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListCoursePassRatesResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListInstructorPassRatesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CourseCode     string                 `protobuf:"bytes,1,opt,name=course_code,json=courseCode,proto3" json:"course_code,omitempty"`
	TeacherName    string                 `protobuf:"bytes,2,opt,name=teacher_name,json=teacherName,proto3" json:"teacher_name,omitempty"`
	TermCode       string                 `protobuf:"bytes,3,opt,name=term_code,json=termCode,proto3" json:"term_code,omitempty"`
	EducationLevel string                 `protobuf:"bytes,4,opt,name=education_level,json=educationLevel,proto3" json:"education_level,omitempty"`
	Page           int32                  `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	PageSize       int32                  `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListInstructorPassRatesRequest) Reset() {
	*x = ListInstructorPassRatesRequest{}
	mi := &file_academic_analytics_v1_analytics_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInstructorPassRatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInstructorPassRatesRequest) ProtoMessage() {}

func (x *ListInstructorPassRatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_academic_analytics_v1_analytics_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInstructorPassRatesRequest.ProtoReflect.Descriptor instead.
func (*ListInstructorPassRatesRequest) Descriptor() ([]byte, []int) {
	return file_academic_analytics_v1_analytics_proto_rawDescGZIP(), []int{9}
}

func (x *ListInstructorPassRatesRequest) GetCourseCode() string {
	if x != nil {
		return x.CourseCode
	}
	return ""
}

func (x *ListInstructorPassRatesRequest) GetTeacherName() string {
	if x != nil {
		return x.TeacherName
	}
	return ""
}

func (x *ListInstructorPassRatesRequest) GetTermCode() string {
	if x != nil {
		return x.TermCode
	}
	return ""
}

func (x *ListInstructorPassRatesRequest) GetEducationLevel() string {
	if x != nil {
		return x.EducationLevel
	}
	return ""
}

func (x *ListInstructorPassRatesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListInstructorPassRatesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListInstructorPassRatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *PublicationMetadata   `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Items         []*InstructorPassRate  `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	Total         int64                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInstructorPassRatesResponse) Reset() {
	*x = ListInstructorPassRatesResponse{}
	mi := &file_academic_analytics_v1_analytics_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInstructorPassRatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInstructorPassRatesResponse) ProtoMessage() {}

func (x *ListInstructorPassRatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_academic_analytics_v1_analytics_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInstructorPassRatesResponse.ProtoReflect.Descriptor instead.
func (*ListInstructorPassRatesResponse) Descriptor() ([]byte, []int) {
	return file_academic_analytics_v1_analytics_proto_rawDescGZIP(), []int{10}
}

func (x *ListInstructorPassRatesResponse) GetMetadata() *PublicationMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ListInstructorPassRatesResponse) GetItems() []*InstructorPassRate {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListInstructorPassRatesResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListInstructorPassRatesResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListInstructorPassRatesResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetCoursePassRateTrendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseCode    string                 `protobuf:"bytes,1,opt,name=course_code,json=courseCode,proto3" json:"course_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCoursePassRateTrendRequest) Reset() {
	*x = GetCoursePassRateTrendRequest{}
	mi := &file_academic_analytics_v1_analytics_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCoursePassRateTrendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCoursePassRateTrendRequest) ProtoMessage() {}

func (x *GetCoursePassRateTrendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_academic_analytics_v1_analytics_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCoursePassRateTrendRequest.ProtoReflect.Descriptor instead.
func (*GetCoursePassRateTrendRequest) Descriptor() ([]byte, []int) {
	return file_academic_analytics_v1_analytics_proto_rawDescGZIP(), []int{11}
}

func (x *GetCoursePassRateTrendRequest) GetCourseCode() string {
	if x != nil {
		return x.CourseCode
	}
	return ""
}

type GetInstructorPassRateTrendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseCode    string                 `protobuf:"bytes,1,opt,name=course_code,json=courseCode,proto3" json:"course_code,omitempty"`
	TeacherKey    string                 `protobuf:"bytes,2,opt,name=teacher_key,json=teacherKey,proto3" json:"teacher_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInstructorPassRateTrendRequest) Reset() {
	*x = GetInstructorPassRateTrendRequest{}
	mi := &file_academic_analytics_v1_analytics_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInstructorPassRateTrendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInstructorPassRateTrendRequest) ProtoMessage() {}

func (x *GetInstructorPassRateTrendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_academic_analytics_v1_analytics_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInstructorPassRateTrendRequest.ProtoReflect.Descriptor instead.
func (*GetInstructorPassRateTrendRequest) Descriptor() ([]byte, []int) {
	return file_academic_analytics_v1_analytics_proto_rawDescGZIP(), []int{12}
}

func (x *GetInstructorPassRateTrendRequest) GetCourseCode() string {
	if x != nil {
		return x.CourseCode
	}
	return ""
}

func (x *GetInstructorPassRateTrendRequest) GetTeacherKey() string {
	if x != nil {
		return x.TeacherKey
	}
	return ""
}

type GetCoursePassRateTrendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *PublicationMetadata   `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Trend         *PassRateTrend         `protobuf:"bytes,2,opt,name=trend,proto3" json:"trend,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCoursePassRateTrendResponse) Reset() {
	*x = GetCoursePassRateTrendResponse{}
	mi := &file_academic_analytics_v1_analytics_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCoursePassRateTrendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCoursePassRateTrendResponse) ProtoMessage() {}

func (x *GetCoursePassRateTrendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_academic_analytics_v1_analytics_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCoursePassRateTrendResponse.ProtoReflect.Descriptor instead.
func (*GetCoursePassRateTrendResponse) Descriptor() ([]byte, []int) {
	return file_academic_analytics_v1_analytics_proto_rawDescGZIP(), []int{13}
}

func (x *GetCoursePassRateTrendResponse) GetMetadata() *PublicationMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GetCoursePassRateTrendResponse) GetTrend() *PassRateTrend {
	if x != nil {
		return x.Trend
	}
	return nil
}

type GetInstructorPassRateTrendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *PublicationMetadata   `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Trend         *PassRateTrend         `protobuf:"bytes,2,opt,name=trend,proto3" json:"trend,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInstructorPassRateTrendResponse) Reset() {
	*x = GetInstructorPassRateTrendResponse{}
	mi := &file_academic_analytics_v1_analytics_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInstructorPassRateTrendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInstructorPassRateTrendResponse) ProtoMessage() {}

func (x *GetInstructorPassRateTrendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_academic_analytics_v1_analytics_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInstructorPassRateTrendResponse.ProtoReflect.Descriptor instead.
func (*GetInstructorPassRateTrendResponse) Descriptor() ([]byte, []int) {
	return file_academic_analytics_v1_analytics_proto_rawDescGZIP(), []int{14}
}

func (x *GetInstructorPassRateTrendResponse) GetMetadata() *PublicationMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GetInstructorPassRateTrendResponse) GetTrend() *PassRateTrend {
	if x != nil {
		return x.Trend
	}
	return nil
}

type ListBatchesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBatchesRequest) Reset() {
	*x = ListBatchesRequest{}
	mi := &file_academic_analytics_v1_analytics_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBatchesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBatchesRequest) ProtoMessage() {}

func (x *ListBatchesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_academic_analytics_v1_analytics_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBatchesRequest.ProtoReflect.Descriptor instead.
func (*ListBatchesRequest) Descriptor() ([]byte, []int) {
	return file_academic_analytics_v1_analytics_proto_rawDescGZIP(), []int{15}
}

func (x *ListBatchesRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListBatchesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListBatchesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListBatchesResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Items         []*AcademicStatisticsBatch `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int64                      `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                      `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                      `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBatchesResponse) Reset() {
	*x = ListBatchesResponse{}
	mi := &file_academic_analytics_v1_analytics_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBatchesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBatchesResponse) ProtoMessage() {}

func (x *ListBatchesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_academic_analytics_v1_analytics_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBatchesResponse.ProtoReflect.Descriptor instead.
func (*ListBatchesResponse) Descriptor() ([]byte, []int) {
	return file_academic_analytics_v1_analytics_proto_rawDescGZIP(), []int{16}
}

func (x *ListBatchesResponse) GetItems() []*AcademicStatisticsBatch {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListBatchesResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListBatchesResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListBatchesResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type TriggerManualRunRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ActorId        uint64                 `protobuf:"varint,1,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	Confirmation   string                 `protobuf:"bytes,2,opt,name=confirmation,proto3" json:"confirmation,omitempty"`
	Note           string                 `protobuf:"bytes,3,opt,name=note,proto3" json:"note,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TriggerManualRunRequest) Reset() {
	*x = TriggerManualRunRequest{}
	mi := &file_academic_analytics_v1_analytics_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerManualRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerManualRunRequest) ProtoMessage() {}

func (x *TriggerManualRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_academic_analytics_v1_analytics_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerManualRunRequest.ProtoReflect.Descriptor instead.
func (*TriggerManualRunRequest) Descriptor() ([]byte, []int) {
	return file_academic_analytics_v1_analytics_proto_rawDescGZIP(), []int{17}
}

func (x *TriggerManualRunRequest) GetActorId() uint64 {
	if x != nil {
		return x.ActorId
	}
	return 0
}

func (x *TriggerManualRunRequest) GetConfirmation() string {
	if x != nil {
		return x.Confirmation
	}
	return ""
}

func (x *TriggerManualRunRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *TriggerManualRunRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type TriggerManualRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	QueuedAt      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=queued_at,json=queuedAt,proto3" json:"queued_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerManualRunResponse) Reset() {
	*x = TriggerManualRunResponse{}
	mi := &file_academic_analytics_v1_analytics_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerManualRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerManualRunResponse) ProtoMessage() {}

func (x *TriggerManualRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_academic_analytics_v1_analytics_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerManualRunResponse.ProtoReflect.Descriptor instead.
func (*TriggerManualRunResponse) Descriptor() ([]byte, []int) {
	return file_academic_analytics_v1_analytics_proto_rawDescGZIP(), []int{18}
}

func (x *TriggerManualRunResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TriggerManualRunResponse) GetQueuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.QueuedAt
	}
	return nil
}

type ListClassDiscussionRecipientsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Provider       string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	EducationLevel string                 `protobuf:"bytes,2,opt,name=education_level,json=educationLevel,proto3" json:"education_level,omitempty"`
	PeriodId       string                 `protobuf:"bytes,3,opt,name=period_id,json=periodId,proto3" json:"period_id,omitempty"`
	ClassNum       string                 `protobuf:"bytes,4,opt,name=class_num,json=classNum,proto3" json:"class_num,omitempty"`
	PageSize       int32                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Cursor         string                 `protobuf:"bytes,6,opt,name=cursor,proto3" json:"cursor,omitempty"`
	MinObservedAt  *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=min_observed_at,json=minObservedAt,proto3" json:"min_observed_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListClassDiscussionRecipientsRequest) Reset() {
	*x = ListClassDiscussionRecipientsRequest{}
	mi := &file_academic_analytics_v1_analytics_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClassDiscussionRecipientsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClassDiscussionRecipientsRequest) ProtoMessage() {}

func (x *ListClassDiscussionRecipientsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_academic_analytics_v1_analytics_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClassDiscussionRecipientsRequest.ProtoReflect.Descriptor instead.
func (*ListClassDiscussionRecipientsRequest) Descriptor() ([]byte, []int) {
	return file_academic_analytics_v1_analytics_proto_rawDescGZIP(), []int{19}
}

func (x *ListClassDiscussionRecipientsRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ListClassDiscussionRecipientsRequest) GetEducationLevel() string {
	if x != nil {
		return x.EducationLevel
	}
	return ""
}

func (x *ListClassDiscussionRecipientsRequest) GetPeriodId() string {
	if x != nil {
		return x.PeriodId
	}
	return ""
}

func (x *ListClassDiscussionRecipientsRequest) GetClassNum() string {
	if x != nil {
		return x.ClassNum
	}
	return ""
}

func (x *ListClassDiscussionRecipientsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListClassDiscussionRecipientsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ListClassDiscussionRecipientsRequest) GetMinObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.MinObservedAt
	}
	return nil
}

type ClassDiscussionRecipient struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentNo     string                 `protobuf:"bytes,1,opt,name=student_no,json=studentNo,proto3" json:"student_no,omitempty"`
	ClassNum      string                 `protobuf:"bytes,2,opt,name=class_num,json=classNum,proto3" json:"class_num,omitempty"`
	ObservedAt    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	SourceMask    uint32                 `protobuf:"varint,4,opt,name=source_mask,json=sourceMask,proto3" json:"source_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassDiscussionRecipient) Reset() {
	*x = ClassDiscussionRecipient{}
	mi := &file_academic_analytics_v1_analytics_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassDiscussionRecipient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassDiscussionRecipient) ProtoMessage() {}

func (x *ClassDiscussionRecipient) ProtoReflect() protoreflect.Message {
	mi := &file_academic_analytics_v1_analytics_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassDiscussionRecipient.ProtoReflect.Descriptor instead.
func (*ClassDiscussionRecipient) Descriptor() ([]byte, []int) {
	return file_academic_analytics_v1_analytics_proto_rawDescGZIP(), []int{20}
}

func (x *ClassDiscussionRecipient) GetStudentNo() string {
	if x != nil {
		return x.StudentNo
	}
	return ""
}

func (x *ClassDiscussionRecipient) GetClassNum() string {
	if x != nil {
		return x.ClassNum
	}
	return ""
}

func (x *ClassDiscussionRecipient) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

func (x *ClassDiscussionRecipient) GetSourceMask() uint32 {
	if x != nil {
		return x.SourceMask
	}
	return 0
}

type ListClassDiscussionRecipientsResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Recipients    []*ClassDiscussionRecipient `protobuf:"bytes,1,rep,name=recipients,proto3" json:"recipients,omitempty"`
	NextCursor    string                      `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	EvaluatedAt   *timestamppb.Timestamp      `protobuf:"bytes,3,opt,name=evaluated_at,json=evaluatedAt,proto3" json:"evaluated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClassDiscussionRecipientsResponse) Reset() {
	*x = ListClassDiscussionRecipientsResponse{}
	mi := &file_academic_analytics_v1_analytics_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClassDiscussionRecipientsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClassDiscussionRecipientsResponse) ProtoMessage() {}

func (x *ListClassDiscussionRecipientsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_academic_analytics_v1_analytics_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClassDiscussionRecipientsResponse.ProtoReflect.Descriptor instead.
func (*ListClassDiscussionRecipientsResponse) Descriptor() ([]byte, []int) {
	return file_academic_analytics_v1_analytics_proto_rawDescGZIP(), []int{21}
}

func (x *ListClassDiscussionRecipientsResponse) GetRecipients() []*ClassDiscussionRecipient {
	if x != nil {
		return x.Recipients
	}
	return nil
}

func (x *ListClassDiscussionRecipientsResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *ListClassDiscussionRecipientsResponse) GetEvaluatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EvaluatedAt
	}
	return nil
}

type GetStudentTimetableRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Provider       string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	EducationLevel string                 `protobuf:"bytes,2,opt,name=education_level,json=educationLevel,proto3" json:"education_level,omitempty"`
	StudentNo      string                 `protobuf:"bytes,3,opt,name=student_no,json=studentNo,proto3" json:"student_no,omitempty"`
	PeriodId       string                 `protobuf:"bytes,4,opt,name=period_id,json=periodId,proto3" json:"period_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetStudentTimetableRequest) Reset() {
	*x = GetStudentTimetableRequest{}
	mi := &file_academic_analytics_v1_analytics_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStudentTimetableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudentTimetableRequest) ProtoMessage() {}

func (x *GetStudentTimetableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_academic_analytics_v1_analytics_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudentTimetableRequest.ProtoReflect.Descriptor instead.
func (*GetStudentTimetableRequest) Descriptor() ([]byte, []int) {
	return file_academic_analytics_v1_analytics_proto_rawDescGZIP(), []int{22}
}

func (x *GetStudentTimetableRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *GetStudentTimetableRequest) GetEducationLevel() string {
	if x != nil {
		return x.EducationLevel
	}
	return ""
}

func (x *GetStudentTimetableRequest) GetStudentNo() string {
	if x != nil {
		return x.StudentNo
	}
	return ""
}

func (x *GetStudentTimetableRequest) GetPeriodId() string {
	if x != nil {
		return x.PeriodId
	}
	return ""
}

type TimetableCourse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Location      string                 `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	Weekday       int32                  `protobuf:"varint,3,opt,name=weekday,proto3" json:"weekday,omitempty"`
	StartSection  int32                  `protobuf:"varint,4,opt,name=start_section,json=startSection,proto3" json:"start_section,omitempty"`
	EndSection    int32                  `protobuf:"varint,5,opt,name=end_section,json=endSection,proto3" json:"end_section,omitempty"`
	Weeks         []int32                `protobuf:"varint,6,rep,packed,name=weeks,proto3" json:"weeks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimetableCourse) Reset() {
	*x = TimetableCourse{}
	mi := &file_academic_analytics_v1_analytics_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimetableCourse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimetableCourse) ProtoMessage() {}

func (x *TimetableCourse) ProtoReflect() protoreflect.Message {
	mi := &file_academic_analytics_v1_analytics_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimetableCourse.ProtoReflect.Descriptor instead.
func (*TimetableCourse) Descriptor() ([]byte, []int) {
	return file_academic_analytics_v1_analytics_proto_rawDescGZIP(), []int{23}
}

func (x *TimetableCourse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TimetableCourse) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *TimetableCourse) GetWeekday() int32 {
	if x != nil {
		return x.Weekday
	}
	return 0
}

func (x *TimetableCourse) GetStartSection() int32 {
	if x != nil {
		return x.StartSection
	}
	return 0
}

func (x *TimetableCourse) GetEndSection() int32 {
	if x != nil {
		return x.EndSection
	}
	return 0
}

func (x *TimetableCourse) GetWeeks() []int32 {
	if x != nil {
		return x.Weeks
	}
	return nil
}

type GetStudentTimetableResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Available          bool                   `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`
	Complete           bool                   `protobuf:"varint,2,opt,name=complete,proto3" json:"complete,omitempty"`
	ObservedAt         *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	CompleteObservedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=complete_observed_at,json=completeObservedAt,proto3" json:"complete_observed_at,omitempty"`
	Courses            []*TimetableCourse     `protobuf:"bytes,5,rep,name=courses,proto3" json:"courses,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetStudentTimetableResponse) Reset() {
	*x = GetStudentTimetableResponse{}
	mi := &file_academic_analytics_v1_analytics_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStudentTimetableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudentTimetableResponse) ProtoMessage() {}

func (x *GetStudentTimetableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_academic_analytics_v1_analytics_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudentTimetableResponse.ProtoReflect.Descriptor instead.
func (*GetStudentTimetableResponse) Descriptor() ([]byte, []int) {
	return file_academic_analytics_v1_analytics_proto_rawDescGZIP(), []int{24}
}

func (x *GetStudentTimetableResponse) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *GetStudentTimetableResponse) GetComplete() bool {
	if x != nil {
		return x.Complete
	}
	return false
}

func (x *GetStudentTimetableResponse) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

func (x *GetStudentTimetableResponse) GetCompleteObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompleteObservedAt
	}
	return nil
}

func (x *GetStudentTimetableResponse) GetCourses() []*TimetableCourse {
	if x != nil {
		return x.Courses
	}
	return nil
}

var File_academic_analytics_v1_analytics_proto protoreflect.FileDescriptor

const file_academic_analytics_v1_analytics_proto_rawDesc = "" +
	"\n" +
	"%academic/analytics/v1/analytics.proto\x12\x15academic.analytics.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x88\x02\n" +
	"\x13PublicationMetadata\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\x04R\abatchId\x12D\n" +
	"\x10source_cutoff_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x0esourceCutoffAt\x12=\n" +
	"\fpublished_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vpublishedAt\x12!\n" +
	"\frule_version\x18\x04 \x01(\tR\vruleVersion\x12.\n" +
	"\x13minimum_sample_size\x18\x05 \x01(\x03R\x11minimumSampleSize\"\xcf\x03\n" +
	"\x11GradeDistribution\x12,\n" +
	"\x12numeric_fail_count\x18\x01 \x01(\x03R\x10numericFailCount\x12)\n" +
	"\x11score_60_69_count\x18\x02 \x01(\x03R\x0escore6069Count\x12)\n" +
	"\x11score_70_79_count\x18\x03 \x01(\x03R\x0escore7079Count\x12)\n" +
	"\x11score_80_89_count\x18\x04 \x01(\x03R\x0escore8089Count\x12+\n" +
	"\x12score_90_100_count\x18\x05 \x01(\x03R\x0fscore90100Count\x122\n" +
	"\x15level_excellent_count\x18\x06 \x01(\x03R\x13levelExcellentCount\x12(\n" +
	"\x10level_good_count\x18\a \x01(\x03R\x0elevelGoodCount\x12,\n" +
	"\x12level_medium_count\x18\b \x01(\x03R\x10levelMediumCount\x12(\n" +
	"\x10level_pass_count\x18\t \x01(\x03R\x0elevelPassCount\x12(\n" +
	"\x10level_fail_count\x18\n" +
	" \x01(\x03R\x0elevelFailCount\"\xac\x03\n" +
	"\x0eCoursePassRate\x12'\n" +
	"\x0feducation_level\x18\x01 \x01(\tR\x0eeducationLevel\x12\x1f\n" +
	"\vcourse_code\x18\x02 \x01(\tR\n" +
	"courseCode\x12\x1f\n" +
	"\vcourse_name\x18\x03 \x01(\tR\n" +
	"courseName\x12\x1d\n" +
	"\n" +
	"term_count\x18\x04 \x01(\x03R\ttermCount\x12\x1f\n" +
	"\vvalid_count\x18\x05 \x01(\x03R\n" +
	"validCount\x12\x1d\n" +
	"\n" +
	"pass_count\x18\x06 \x01(\x03R\tpassCount\x12\x1d\n" +
	"\n" +
	"fail_count\x18\a \x01(\x03R\tfailCount\x12.\n" +
	"\x13numeric_score_count\x18\b \x01(\x03R\x11numericScoreCount\x123\n" +
	"\x16numeric_score_sum_x100\x18\t \x01(\x03R\x13numericScoreSumX100\x12L\n" +
	"\fdistribution\x18\n" +
	" \x01(\v2(.academic.analytics.v1.GradeDistributionR\fdistribution\"\x95\x04\n" +
	"\x12InstructorPassRate\x12'\n" +
	"\x0feducation_level\x18\x01 \x01(\tR\x0eeducationLevel\x12\x1f\n" +
	"\vcourse_code\x18\x02 \x01(\tR\n" +
	"courseCode\x12\x1f\n" +
	"\vcourse_name\x18\x03 \x01(\tR\n" +
	"courseName\x12\x1f\n" +
	"\vteacher_key\x18\x04 \x01(\tR\n" +
	"teacherKey\x12!\n" +
	"\fteacher_name\x18\x05 \x01(\tR\vteacherName\x12\x1d\n" +
	"\n" +
	"term_count\x18\x06 \x01(\x03R\ttermCount\x12\x1f\n" +
	"\vclass_count\x18\a \x01(\x03R\n" +
	"classCount\x12\x1f\n" +
	"\vvalid_count\x18\b \x01(\x03R\n" +
	"validCount\x12\x1d\n" +
	"\n" +
	"pass_count\x18\t \x01(\x03R\tpassCount\x12\x1d\n" +
	"\n" +
	"fail_count\x18\n" +
	" \x01(\x03R\tfailCount\x12.\n" +
	"\x13numeric_score_count\x18\v \x01(\x03R\x11numericScoreCount\x123\n" +
	"\x16numeric_score_sum_x100\x18\f \x01(\x03R\x13numericScoreSumX100\x12L\n" +
	"\fdistribution\x18\r \x01(\v2(.academic.analytics.v1.GradeDistributionR\fdistribution\"\xa8\x03\n" +
	"\x12PassRateTrendPoint\x12'\n" +
	"\x0feducation_level\x18\x01 \x01(\tR\x0eeducationLevel\x12\x1b\n" +
	"\tperiod_id\x18\x02 \x01(\tR\bperiodId\x12\x1d\n" +
	"\n" +
	"term_label\x18\x03 \x01(\tR\ttermLabel\x12\x1b\n" +
	"\tterm_code\x18\x04 \x01(\tR\btermCode\x12\x1f\n" +
	"\vvalid_count\x18\x05 \x01(\x03R\n" +
	"validCount\x12\x1d\n" +
	"\n" +
	"pass_count\x18\x06 \x01(\x03R\tpassCount\x12\x1d\n" +
	"\n" +
	"fail_count\x18\a \x01(\x03R\tfailCount\x12.\n" +
	"\x13numeric_score_count\x18\b \x01(\x03R\x11numericScoreCount\x123\n" +
	"\x16numeric_score_sum_x100\x18\t \x01(\x03R\x13numericScoreSumX100\x12L\n" +
	"\fdistribution\x18\n" +
	" \x01(\v2(.academic.analytics.v1.GradeDistributionR\fdistribution\"\xd8\x01\n" +
	"\rPassRateTrend\x12\x1f\n" +
	"\vcourse_code\x18\x01 \x01(\tR\n" +
	"courseCode\x12\x1f\n" +
	"\vcourse_name\x18\x02 \x01(\tR\n" +
	"courseName\x12\x1f\n" +
	"\vteacher_key\x18\x03 \x01(\tR\n" +
	"teacherKey\x12!\n" +
	"\fteacher_name\x18\x04 \x01(\tR\vteacherName\x12A\n" +
	"\x06points\x18\x05 \x03(\v2).academic.analytics.v1.PassRateTrendPointR\x06points\"\x9e\a\n" +
	"\x17AcademicStatisticsBatch\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12!\n" +
	"\ftrigger_type\x18\x03 \x01(\tR\vtriggerType\x12&\n" +
	"\ftriggered_by\x18\x04 \x01(\x04H\x00R\vtriggeredBy\x88\x01\x01\x12&\n" +
	"\ftrigger_note\x18\x05 \x01(\tH\x01R\vtriggerNote\x88\x01\x01\x12+\n" +
	"\x0ftrigger_task_id\x18\x06 \x01(\tH\x02R\rtriggerTaskId\x88\x01\x01\x12D\n" +
	"\x10source_cutoff_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x0esourceCutoffAt\x12!\n" +
	"\frule_version\x18\b \x01(\tR\vruleVersion\x12(\n" +
	"\x10source_row_count\x18\t \x01(\x03R\x0esourceRowCount\x12*\n" +
	"\x11course_stat_count\x18\n" +
	" \x01(\x03R\x0fcourseStatCount\x122\n" +
	"\x15instructor_stat_count\x18\v \x01(\x03R\x13instructorStatCount\x12(\n" +
	"\rerror_summary\x18\f \x01(\tH\x03R\ferrorSummary\x88\x01\x01\x129\n" +
	"\n" +
	"started_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12@\n" +
	"\vfinished_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampH\x04R\n" +
	"finishedAt\x88\x01\x01\x12B\n" +
	"\fpublished_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampH\x05R\vpublishedAt\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\x0f\n" +
	"\r_triggered_byB\x0f\n" +
	"\r_trigger_noteB\x12\n" +
	"\x10_trigger_task_idB\x10\n" +
	"\x0e_error_summaryB\x0e\n" +
	"\f_finished_atB\x0f\n" +
	"\r_published_at\"\xce\x01\n" +
	"\x1aListCoursePassRatesRequest\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12\x1f\n" +
	"\vcourse_code\x18\x02 \x01(\tR\n" +
	"courseCode\x12\x1b\n" +
	"\tterm_code\x18\x03 \x01(\tR\btermCode\x12'\n" +
	"\x0feducation_level\x18\x04 \x01(\tR\x0eeducationLevel\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x06 \x01(\x05R\bpageSize\"\xe9\x01\n" +
	"\x1bListCoursePassRatesResponse\x12F\n" +
	"\bmetadata\x18\x01 \x01(\v2*.academic.analytics.v1.PublicationMetadataR\bmetadata\x12;\n" +
	"\x05items\x18\x02 \x03(\v2%.academic.analytics.v1.CoursePassRateR\x05items\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\"\xdb\x01\n" +
	"\x1eListInstructorPassRatesRequest\x12\x1f\n" +
	"\vcourse_code\x18\x01 \x01(\tR\n" +
	"courseCode\x12!\n" +
	"\fteacher_name\x18\x02 \x01(\tR\vteacherName\x12\x1b\n" +
	"\tterm_code\x18\x03 \x01(\tR\btermCode\x12'\n" +
	"\x0feducation_level\x18\x04 \x01(\tR\x0eeducationLevel\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x06 \x01(\x05R\bpageSize\"\xf1\x01\n" +
	"\x1fListInstructorPassRatesResponse\x12F\n" +
	"\bmetadata\x18\x01 \x01(\v2*.academic.analytics.v1.PublicationMetadataR\bmetadata\x12?\n" +
	"\x05items\x18\x02 \x03(\v2).academic.analytics.v1.InstructorPassRateR\x05items\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\"@\n" +
	"\x1dGetCoursePassRateTrendRequest\x12\x1f\n" +
	"\vcourse_code\x18\x01 \x01(\tR\n" +
	"courseCode\"e\n" +
	"!GetInstructorPassRateTrendRequest\x12\x1f\n" +
	"\vcourse_code\x18\x01 \x01(\tR\n" +
	"courseCode\x12\x1f\n" +
	"\vteacher_key\x18\x02 \x01(\tR\n" +
	"teacherKey\"\xa4\x01\n" +
	"\x1eGetCoursePassRateTrendResponse\x12F\n" +
	"\bmetadata\x18\x01 \x01(\v2*.academic.analytics.v1.PublicationMetadataR\bmetadata\x12:\n" +
	"\x05trend\x18\x02 \x01(\v2$.academic.analytics.v1.PassRateTrendR\x05trend\"\xa8\x01\n" +
	"\"GetInstructorPassRateTrendResponse\x12F\n" +
	"\bmetadata\x18\x01 \x01(\v2*.academic.analytics.v1.PublicationMetadataR\bmetadata\x12:\n" +
	"\x05trend\x18\x02 \x01(\v2$.academic.analytics.v1.PassRateTrendR\x05trend\"]\n" +
	"\x12ListBatchesRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\xa2\x01\n" +
	"\x13ListBatchesResponse\x12D\n" +
	"\x05items\x18\x01 \x03(\v2..academic.analytics.v1.AcademicStatisticsBatchR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\x95\x01\n" +
	"\x17TriggerManualRunRequest\x12\x19\n" +
	"\bactor_id\x18\x01 \x01(\x04R\aactorId\x12\"\n" +
	"\fconfirmation\x18\x02 \x01(\tR\fconfirmation\x12\x12\n" +
	"\x04note\x18\x03 \x01(\tR\x04note\x12'\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tR\x0eidempotencyKey\"l\n" +
	"\x18TriggerManualRunResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x127\n" +
	"\tqueued_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bqueuedAt\"\x9e\x02\n" +
	"$ListClassDiscussionRecipientsRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12'\n" +
	"\x0feducation_level\x18\x02 \x01(\tR\x0eeducationLevel\x12\x1b\n" +
	"\tperiod_id\x18\x03 \x01(\tR\bperiodId\x12\x1b\n" +
	"\tclass_num\x18\x04 \x01(\tR\bclassNum\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06cursor\x18\x06 \x01(\tR\x06cursor\x12B\n" +
	"\x0fmin_observed_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\rminObservedAt\"\xb4\x01\n" +
	"\x18ClassDiscussionRecipient\x12\x1d\n" +
	"\n" +
	"student_no\x18\x01 \x01(\tR\tstudentNo\x12\x1b\n" +
	"\tclass_num\x18\x02 \x01(\tR\bclassNum\x12;\n" +
	"\vobserved_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"observedAt\x12\x1f\n" +
	"\vsource_mask\x18\x04 \x01(\rR\n" +
	"sourceMask\"\xd8\x01\n" +
	"%ListClassDiscussionRecipientsResponse\x12O\n" +
	"\n" +
	"recipients\x18\x01 \x03(\v2/.academic.analytics.v1.ClassDiscussionRecipientR\n" +
	"recipients\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\x12=\n" +
	"\fevaluated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vevaluatedAt\"\x9d\x01\n" +
	"\x1aGetStudentTimetableRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12'\n" +
	"\x0feducation_level\x18\x02 \x01(\tR\x0eeducationLevel\x12\x1d\n" +
	"\n" +
	"student_no\x18\x03 \x01(\tR\tstudentNo\x12\x1b\n" +
	"\tperiod_id\x18\x04 \x01(\tR\bperiodId\"\xb7\x01\n" +
	"\x0fTimetableCourse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\blocation\x18\x02 \x01(\tR\blocation\x12\x18\n" +
	"\aweekday\x18\x03 \x01(\x05R\aweekday\x12#\n" +
	"\rstart_section\x18\x04 \x01(\x05R\fstartSection\x12\x1f\n" +
	"\vend_section\x18\x05 \x01(\x05R\n" +
	"endSection\x12\x14\n" +
	"\x05weeks\x18\x06 \x03(\x05R\x05weeks\"\xa4\x02\n" +
	"\x1bGetStudentTimetableResponse\x12\x1c\n" +
	"\tavailable\x18\x01 \x01(\bR\tavailable\x12\x1a\n" +
	"\bcomplete\x18\x02 \x01(\bR\bcomplete\x12;\n" +
	"\vobserved_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"observedAt\x12L\n" +
	"\x14complete_observed_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x12completeObservedAt\x12@\n" +
	"\acourses\x18\x05 \x03(\v2&.academic.analytics.v1.TimetableCourseR\acourses2\x9a\x06\n" +
	"\x18AcademicAnalyticsService\x12|\n" +
	"\x13ListCoursePassRates\x121.academic.analytics.v1.ListCoursePassRatesRequest\x1a2.academic.analytics.v1.ListCoursePassRatesResponse\x12\x88\x01\n" +
	"\x17ListInstructorPassRates\x125.academic.analytics.v1.ListInstructorPassRatesRequest\x1a6.academic.analytics.v1.ListInstructorPassRatesResponse\x12\x85\x01\n" +
	"\x16GetCoursePassRateTrend\x124.academic.analytics.v1.GetCoursePassRateTrendRequest\x1a5.academic.analytics.v1.GetCoursePassRateTrendResponse\x12\x91\x01\n" +
	"\x1aGetInstructorPassRateTrend\x128.academic.analytics.v1.GetInstructorPassRateTrendRequest\x1a9.academic.analytics.v1.GetInstructorPassRateTrendResponse\x12d\n" +
	"\vListBatches\x12).academic.analytics.v1.ListBatchesRequest\x1a*.academic.analytics.v1.ListBatchesResponse\x12s\n" +
	"\x10TriggerManualRun\x12..academic.analytics.v1.TriggerManualRunRequest\x1a/.academic.analytics.v1.TriggerManualRunResponse2\xb7\x01\n" +
	"\x18AcademicRecipientService\x12\x9a\x01\n" +
	"\x1dListClassDiscussionRecipients\x12;.academic.analytics.v1.ListClassDiscussionRecipientsRequest\x1a<.academic.analytics.v1.ListClassDiscussionRecipientsResponse2\x98\x01\n" +
	"\x18AcademicTimetableService\x12|\n" +
	"\x13GetStudentTimetable\x121.academic.analytics.v1.GetStudentTimetableRequest\x1a2.academic.analytics.v1.GetStudentTimetableResponseBVZTgithub.com/LDouble/campus-academic-api/pkg/academic/analytics/v1;academicanalyticsv1b\x06proto3"

var (
	file_academic_analytics_v1_analytics_proto_rawDescOnce sync.Once
	file_academic_analytics_v1_analytics_proto_rawDescData []byte
)

func file_academic_analytics_v1_analytics_proto_rawDescGZIP() []byte {
	file_academic_analytics_v1_analytics_proto_rawDescOnce.Do(func() {
		file_academic_analytics_v1_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_academic_analytics_v1_analytics_proto_rawDesc), len(file_academic_analytics_v1_analytics_proto_rawDesc)))
	})
	return file_academic_analytics_v1_analytics_proto_rawDescData
}

var file_academic_analytics_v1_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_academic_analytics_v1_analytics_proto_goTypes = []any{
	(*PublicationMetadata)(nil),                   // 0: academic.analytics.v1.PublicationMetadata
	(*GradeDistribution)(nil),                     // 1: academic.analytics.v1.GradeDistribution
	(*CoursePassRate)(nil),                        // 2: academic.analytics.v1.CoursePassRate
	(*InstructorPassRate)(nil),                    // 3: academic.analytics.v1.InstructorPassRate
	(*PassRateTrendPoint)(nil),                    // 4: academic.analytics.v1.PassRateTrendPoint
	(*PassRateTrend)(nil),                         // 5: academic.analytics.v1.PassRateTrend
	(*AcademicStatisticsBatch)(nil),               // 6: academic.analytics.v1.AcademicStatisticsBatch
	(*ListCoursePassRatesRequest)(nil),            // 7: academic.analytics.v1.ListCoursePassRatesRequest
	(*ListCoursePassRatesResponse)(nil),           // 8: academic.analytics.v1.ListCoursePassRatesResponse
	(*ListInstructorPassRatesRequest)(nil),        // 9: academic.analytics.v1.ListInstructorPassRatesRequest
	(*ListInstructorPassRatesResponse)(nil),       // 10: academic.analytics.v1.ListInstructorPassRatesResponse
	(*GetCoursePassRateTrendRequest)(nil),         // 11: academic.analytics.v1.GetCoursePassRateTrendRequest
	(*GetInstructorPassRateTrendRequest)(nil),     // 12: academic.analytics.v1.GetInstructorPassRateTrendRequest
	(*GetCoursePassRateTrendResponse)(nil),        // 13: academic.analytics.v1.GetCoursePassRateTrendResponse
	(*GetInstructorPassRateTrendResponse)(nil),    // 14: academic.analytics.v1.GetInstructorPassRateTrendResponse
	(*ListBatchesRequest)(nil),                    // 15: academic.analytics.v1.ListBatchesRequest
	(*ListBatchesResponse)(nil),                   // 16: academic.analytics.v1.ListBatchesResponse
	(*TriggerManualRunRequest)(nil),               // 17: academic.analytics.v1.TriggerManualRunRequest
	(*TriggerManualRunResponse)(nil),              // 18: academic.analytics.v1.TriggerManualRunResponse
	(*ListClassDiscussionRecipientsRequest)(nil),  // 19: academic.analytics.v1.ListClassDiscussionRecipientsRequest
	(*ClassDiscussionRecipient)(nil),              // 20: academic.analytics.v1.ClassDiscussionRecipient
	(*ListClassDiscussionRecipientsResponse)(nil), // 21: academic.analytics.v1.ListClassDiscussionRecipientsResponse
	(*GetStudentTimetableRequest)(nil),            // 22: academic.analytics.v1.GetStudentTimetableRequest
	(*TimetableCourse)(nil),                       // 23: academic.analytics.v1.TimetableCourse
	(*GetStudentTimetableResponse)(nil),           // 24: academic.analytics.v1.GetStudentTimetableResponse
	(*timestamppb.Timestamp)(nil),                 // 25: google.protobuf.Timestamp
}
var file_academic_analytics_v1_analytics_proto_depIdxs = []int32{
	25, // 0: academic.analytics.v1.PublicationMetadata.source_cutoff_at:type_name -> google.protobuf.Timestamp
	25, // 1: academic.analytics.v1.PublicationMetadata.published_at:type_name -> google.protobuf.Timestamp
	1,  // 2: academic.analytics.v1.CoursePassRate.distribution:type_name -> academic.analytics.v1.GradeDistribution
	1,  // 3: academic.analytics.v1.InstructorPassRate.distribution:type_name -> academic.analytics.v1.GradeDistribution
	1,  // 4: academic.analytics.v1.PassRateTrendPoint.distribution:type_name -> academic.analytics.v1.GradeDistribution
	4,  // 5: academic.analytics.v1.PassRateTrend.points:type_name -> academic.analytics.v1.PassRateTrendPoint
	25, // 6: academic.analytics.v1.AcademicStatisticsBatch.source_cutoff_at:type_name -> google.protobuf.Timestamp
	25, // 7: academic.analytics.v1.AcademicStatisticsBatch.started_at:type_name -> google.protobuf.Timestamp
	25, // 8: academic.analytics.v1.AcademicStatisticsBatch.finished_at:type_name -> google.protobuf.Timestamp
	25, // 9: academic.analytics.v1.AcademicStatisticsBatch.published_at:type_name -> google.protobuf.Timestamp
	25, // 10: academic.analytics.v1.AcademicStatisticsBatch.created_at:type_name -> google.protobuf.Timestamp
	25, // 11: academic.analytics.v1.AcademicStatisticsBatch.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 12: academic.analytics.v1.ListCoursePassRatesResponse.metadata:type_name -> academic.analytics.v1.PublicationMetadata
	2,  // 13: academic.analytics.v1.ListCoursePassRatesResponse.items:type_name -> academic.analytics.v1.CoursePassRate
	0,  // 14: academic.analytics.v1.ListInstructorPassRatesResponse.metadata:type_name -> academic.analytics.v1.PublicationMetadata
	3,  // 15: academic.analytics.v1.ListInstructorPassRatesResponse.items:type_name -> academic.analytics.v1.InstructorPassRate
	0,  // 16: academic.analytics.v1.GetCoursePassRateTrendResponse.metadata:type_name -> academic.analytics.v1.PublicationMetadata
	5,  // 17: academic.analytics.v1.GetCoursePassRateTrendResponse.trend:type_name -> academic.analytics.v1.PassRateTrend
	0,  // 18: academic.analytics.v1.GetInstructorPassRateTrendResponse.metadata:type_name -> academic.analytics.v1.PublicationMetadata
	5,  // 19: academic.analytics.v1.GetInstructorPassRateTrendResponse.trend:type_name -> academic.analytics.v1.PassRateTrend
	6,  // 20: academic.analytics.v1.ListBatchesResponse.items:type_name -> academic.analytics.v1.AcademicStatisticsBatch
	25, // 21: academic.analytics.v1.TriggerManualRunResponse.queued_at:type_name -> google.protobuf.Timestamp
	25, // 22: academic.analytics.v1.ListClassDiscussionRecipientsRequest.min_observed_at:type_name -> google.protobuf.Timestamp
	25, // 23: academic.analytics.v1.ClassDiscussionRecipient.observed_at:type_name -> google.protobuf.Timestamp
	20, // 24: academic.analytics.v1.ListClassDiscussionRecipientsResponse.recipients:type_name -> academic.analytics.v1.ClassDiscussionRecipient
	25, // 25: academic.analytics.v1.ListClassDiscussionRecipientsResponse.evaluated_at:type_name -> google.protobuf.Timestamp
	25, // 26: academic.analytics.v1.GetStudentTimetableResponse.observed_at:type_name -> google.protobuf.Timestamp
	25, // 27: academic.analytics.v1.GetStudentTimetableResponse.complete_observed_at:type_name -> google.protobuf.Timestamp
	23, // 28: academic.analytics.v1.GetStudentTimetableResponse.courses:type_name -> academic.analytics.v1.TimetableCourse
	7,  // 29: academic.analytics.v1.AcademicAnalyticsService.ListCoursePassRates:input_type -> academic.analytics.v1.ListCoursePassRatesRequest
	9,  // 30: academic.analytics.v1.AcademicAnalyticsService.ListInstructorPassRates:input_type -> academic.analytics.v1.ListInstructorPassRatesRequest
	11, // 31: academic.analytics.v1.AcademicAnalyticsService.GetCoursePassRateTrend:input_type -> academic.analytics.v1.GetCoursePassRateTrendRequest
	12, // 32: academic.analytics.v1.AcademicAnalyticsService.GetInstructorPassRateTrend:input_type -> academic.analytics.v1.GetInstructorPassRateTrendRequest
	15, // 33: academic.analytics.v1.AcademicAnalyticsService.ListBatches:input_type -> academic.analytics.v1.ListBatchesRequest
	17, // 34: academic.analytics.v1.AcademicAnalyticsService.TriggerManualRun:input_type -> academic.analytics.v1.TriggerManualRunRequest
	19, // 35: academic.analytics.v1.AcademicRecipientService.ListClassDiscussionRecipients:input_type -> academic.analytics.v1.ListClassDiscussionRecipientsRequest
	22, // 36: academic.analytics.v1.AcademicTimetableService.GetStudentTimetable:input_type -> academic.analytics.v1.GetStudentTimetableRequest
	8,  // 37: academic.analytics.v1.AcademicAnalyticsService.ListCoursePassRates:output_type -> academic.analytics.v1.ListCoursePassRatesResponse
	10, // 38: academic.analytics.v1.AcademicAnalyticsService.ListInstructorPassRates:output_type -> academic.analytics.v1.ListInstructorPassRatesResponse
	13, // 39: academic.analytics.v1.AcademicAnalyticsService.GetCoursePassRateTrend:output_type -> academic.analytics.v1.GetCoursePassRateTrendResponse
	14, // 40: academic.analytics.v1.AcademicAnalyticsService.GetInstructorPassRateTrend:output_type -> academic.analytics.v1.GetInstructorPassRateTrendResponse
	16, // 41: academic.analytics.v1.AcademicAnalyticsService.ListBatches:output_type -> academic.analytics.v1.ListBatchesResponse
	18, // 42: academic.analytics.v1.AcademicAnalyticsService.TriggerManualRun:output_type -> academic.analytics.v1.TriggerManualRunResponse
	21, // 43: academic.analytics.v1.AcademicRecipientService.ListClassDiscussionRecipients:output_type -> academic.analytics.v1.ListClassDiscussionRecipientsResponse
	24, // 44: academic.analytics.v1.AcademicTimetableService.GetStudentTimetable:output_type -> academic.analytics.v1.GetStudentTimetableResponse
	37, // [37:45] is the sub-list for method output_type
	29, // [29:37] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_academic_analytics_v1_analytics_proto_init() }
func file_academic_analytics_v1_analytics_proto_init() {
	if File_academic_analytics_v1_analytics_proto != nil {
		return
	}
	file_academic_analytics_v1_analytics_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_academic_analytics_v1_analytics_proto_rawDesc), len(file_academic_analytics_v1_analytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_academic_analytics_v1_analytics_proto_goTypes,
		DependencyIndexes: file_academic_analytics_v1_analytics_proto_depIdxs,
		MessageInfos:      file_academic_analytics_v1_analytics_proto_msgTypes,
	}.Build()
	File_academic_analytics_v1_analytics_proto = out.File
	file_academic_analytics_v1_analytics_proto_goTypes = nil
	file_academic_analytics_v1_analytics_proto_depIdxs = nil
}
