// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: academic/credentials/v1/credentials.proto

package academiccredentialsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CredentialsService_GetCredentialMetadata_FullMethodName   = "/academic.credentials.v1.CredentialsService/GetCredentialMetadata"
	CredentialsService_ListCredentialMetadata_FullMethodName  = "/academic.credentials.v1.CredentialsService/ListCredentialMetadata"
	CredentialsService_ResolveCredential_FullMethodName       = "/academic.credentials.v1.CredentialsService/ResolveCredential"
	CredentialsService_ValidateCredentialUse_FullMethodName   = "/academic.credentials.v1.CredentialsService/ValidateCredentialUse"
	CredentialsService_ReportCredentialHealth_FullMethodName  = "/academic.credentials.v1.CredentialsService/ReportCredentialHealth"
	CredentialsService_CreateBindingIntent_FullMethodName     = "/academic.credentials.v1.CredentialsService/CreateBindingIntent"
	CredentialsService_GetHostingStatus_FullMethodName        = "/academic.credentials.v1.CredentialsService/GetHostingStatus"
	CredentialsService_UpdateGrant_FullMethodName             = "/academic.credentials.v1.CredentialsService/UpdateGrant"
	CredentialsService_RevokeCredential_FullMethodName        = "/academic.credentials.v1.CredentialsService/RevokeCredential"
	CredentialsService_FenceSubject_FullMethodName            = "/academic.credentials.v1.CredentialsService/FenceSubject"
	CredentialsService_CreateTask_FullMethodName              = "/academic.credentials.v1.CredentialsService/CreateTask"
	CredentialsService_GetTask_FullMethodName                 = "/academic.credentials.v1.CredentialsService/GetTask"
	CredentialsService_LeaseTask_FullMethodName               = "/academic.credentials.v1.CredentialsService/LeaseTask"
	CredentialsService_ResolveTaskCredential_FullMethodName   = "/academic.credentials.v1.CredentialsService/ResolveTaskCredential"
	CredentialsService_CheckExecutionAdmission_FullMethodName = "/academic.credentials.v1.CredentialsService/CheckExecutionAdmission"
	CredentialsService_CompleteTask_FullMethodName            = "/academic.credentials.v1.CredentialsService/CompleteTask"
)

// CredentialsServiceClient is the client API for CredentialsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CredentialsService 仅管理托管凭据及受控取用；实现层必须执行内部 mTLS 身份策略。
type CredentialsServiceClient interface {
	// 凭据元数据和受控取用不承担业务任务或调度状态。
	GetCredentialMetadata(ctx context.Context, in *GetCredentialMetadataRequest, opts ...grpc.CallOption) (*GetCredentialMetadataResponse, error)
	ListCredentialMetadata(ctx context.Context, in *ListCredentialMetadataRequest, opts ...grpc.CallOption) (*ListCredentialMetadataResponse, error)
	ResolveCredential(ctx context.Context, in *ResolveCredentialRequest, opts ...grpc.CallOption) (*ResolveCredentialResponse, error)
	ValidateCredentialUse(ctx context.Context, in *ValidateCredentialUseRequest, opts ...grpc.CallOption) (*ValidateCredentialUseResponse, error)
	ReportCredentialHealth(ctx context.Context, in *ReportCredentialHealthRequest, opts ...grpc.CallOption) (*ReportCredentialHealthResponse, error)
	CreateBindingIntent(ctx context.Context, in *CreateBindingIntentRequest, opts ...grpc.CallOption) (*CreateBindingIntentResponse, error)
	GetHostingStatus(ctx context.Context, in *GetHostingStatusRequest, opts ...grpc.CallOption) (*GetHostingStatusResponse, error)
	// Deprecated: Do not use.
	// 已停用；仅保留 wire 兼容，服务端不提供实现或授权。
	UpdateGrant(ctx context.Context, in *UpdateGrantRequest, opts ...grpc.CallOption) (*UpdateGrantResponse, error)
	RevokeCredential(ctx context.Context, in *RevokeCredentialRequest, opts ...grpc.CallOption) (*RevokeCredentialResponse, error)
	FenceSubject(ctx context.Context, in *FenceSubjectRequest, opts ...grpc.CallOption) (*FenceSubjectResponse, error)
	// Deprecated: Do not use.
	// 以下旧任务 RPC 已停用；仅保留 wire 兼容，服务端不提供实现或授权。
	CreateTask(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*CreateTaskResponse, error)
	// Deprecated: Do not use.
	GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*GetTaskResponse, error)
	// Deprecated: Do not use.
	LeaseTask(ctx context.Context, in *LeaseTaskRequest, opts ...grpc.CallOption) (*LeaseTaskResponse, error)
	// Deprecated: Do not use.
	ResolveTaskCredential(ctx context.Context, in *ResolveTaskCredentialRequest, opts ...grpc.CallOption) (*ResolveTaskCredentialResponse, error)
	// Deprecated: Do not use.
	CheckExecutionAdmission(ctx context.Context, in *CheckExecutionAdmissionRequest, opts ...grpc.CallOption) (*CheckExecutionAdmissionResponse, error)
	// Deprecated: Do not use.
	CompleteTask(ctx context.Context, in *CompleteTaskRequest, opts ...grpc.CallOption) (*CompleteTaskResponse, error)
}

type credentialsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCredentialsServiceClient(cc grpc.ClientConnInterface) CredentialsServiceClient {
	return &credentialsServiceClient{cc}
}

func (c *credentialsServiceClient) GetCredentialMetadata(ctx context.Context, in *GetCredentialMetadataRequest, opts ...grpc.CallOption) (*GetCredentialMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCredentialMetadataResponse)
	err := c.cc.Invoke(ctx, CredentialsService_GetCredentialMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *credentialsServiceClient) ListCredentialMetadata(ctx context.Context, in *ListCredentialMetadataRequest, opts ...grpc.CallOption) (*ListCredentialMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCredentialMetadataResponse)
	err := c.cc.Invoke(ctx, CredentialsService_ListCredentialMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *credentialsServiceClient) ResolveCredential(ctx context.Context, in *ResolveCredentialRequest, opts ...grpc.CallOption) (*ResolveCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveCredentialResponse)
	err := c.cc.Invoke(ctx, CredentialsService_ResolveCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *credentialsServiceClient) ValidateCredentialUse(ctx context.Context, in *ValidateCredentialUseRequest, opts ...grpc.CallOption) (*ValidateCredentialUseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateCredentialUseResponse)
	err := c.cc.Invoke(ctx, CredentialsService_ValidateCredentialUse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *credentialsServiceClient) ReportCredentialHealth(ctx context.Context, in *ReportCredentialHealthRequest, opts ...grpc.CallOption) (*ReportCredentialHealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportCredentialHealthResponse)
	err := c.cc.Invoke(ctx, CredentialsService_ReportCredentialHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *credentialsServiceClient) CreateBindingIntent(ctx context.Context, in *CreateBindingIntentRequest, opts ...grpc.CallOption) (*CreateBindingIntentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateBindingIntentResponse)
	err := c.cc.Invoke(ctx, CredentialsService_CreateBindingIntent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *credentialsServiceClient) GetHostingStatus(ctx context.Context, in *GetHostingStatusRequest, opts ...grpc.CallOption) (*GetHostingStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHostingStatusResponse)
	err := c.cc.Invoke(ctx, CredentialsService_GetHostingStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Deprecated: Do not use.
func (c *credentialsServiceClient) UpdateGrant(ctx context.Context, in *UpdateGrantRequest, opts ...grpc.CallOption) (*UpdateGrantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateGrantResponse)
	err := c.cc.Invoke(ctx, CredentialsService_UpdateGrant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *credentialsServiceClient) RevokeCredential(ctx context.Context, in *RevokeCredentialRequest, opts ...grpc.CallOption) (*RevokeCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeCredentialResponse)
	err := c.cc.Invoke(ctx, CredentialsService_RevokeCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *credentialsServiceClient) FenceSubject(ctx context.Context, in *FenceSubjectRequest, opts ...grpc.CallOption) (*FenceSubjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FenceSubjectResponse)
	err := c.cc.Invoke(ctx, CredentialsService_FenceSubject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Deprecated: Do not use.
func (c *credentialsServiceClient) CreateTask(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*CreateTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTaskResponse)
	err := c.cc.Invoke(ctx, CredentialsService_CreateTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Deprecated: Do not use.
func (c *credentialsServiceClient) GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*GetTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTaskResponse)
	err := c.cc.Invoke(ctx, CredentialsService_GetTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Deprecated: Do not use.
func (c *credentialsServiceClient) LeaseTask(ctx context.Context, in *LeaseTaskRequest, opts ...grpc.CallOption) (*LeaseTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LeaseTaskResponse)
	err := c.cc.Invoke(ctx, CredentialsService_LeaseTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Deprecated: Do not use.
func (c *credentialsServiceClient) ResolveTaskCredential(ctx context.Context, in *ResolveTaskCredentialRequest, opts ...grpc.CallOption) (*ResolveTaskCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveTaskCredentialResponse)
	err := c.cc.Invoke(ctx, CredentialsService_ResolveTaskCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Deprecated: Do not use.
func (c *credentialsServiceClient) CheckExecutionAdmission(ctx context.Context, in *CheckExecutionAdmissionRequest, opts ...grpc.CallOption) (*CheckExecutionAdmissionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckExecutionAdmissionResponse)
	err := c.cc.Invoke(ctx, CredentialsService_CheckExecutionAdmission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Deprecated: Do not use.
func (c *credentialsServiceClient) CompleteTask(ctx context.Context, in *CompleteTaskRequest, opts ...grpc.CallOption) (*CompleteTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteTaskResponse)
	err := c.cc.Invoke(ctx, CredentialsService_CompleteTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CredentialsServiceServer is the server API for CredentialsService service.
// All implementations must embed UnimplementedCredentialsServiceServer
// for forward compatibility.
//
// CredentialsService 仅管理托管凭据及受控取用；实现层必须执行内部 mTLS 身份策略。
type CredentialsServiceServer interface {
	// 凭据元数据和受控取用不承担业务任务或调度状态。
	GetCredentialMetadata(context.Context, *GetCredentialMetadataRequest) (*GetCredentialMetadataResponse, error)
	ListCredentialMetadata(context.Context, *ListCredentialMetadataRequest) (*ListCredentialMetadataResponse, error)
	ResolveCredential(context.Context, *ResolveCredentialRequest) (*ResolveCredentialResponse, error)
	ValidateCredentialUse(context.Context, *ValidateCredentialUseRequest) (*ValidateCredentialUseResponse, error)
	ReportCredentialHealth(context.Context, *ReportCredentialHealthRequest) (*ReportCredentialHealthResponse, error)
	CreateBindingIntent(context.Context, *CreateBindingIntentRequest) (*CreateBindingIntentResponse, error)
	GetHostingStatus(context.Context, *GetHostingStatusRequest) (*GetHostingStatusResponse, error)
	// Deprecated: Do not use.
	// 已停用；仅保留 wire 兼容，服务端不提供实现或授权。
	UpdateGrant(context.Context, *UpdateGrantRequest) (*UpdateGrantResponse, error)
	RevokeCredential(context.Context, *RevokeCredentialRequest) (*RevokeCredentialResponse, error)
	FenceSubject(context.Context, *FenceSubjectRequest) (*FenceSubjectResponse, error)
	// Deprecated: Do not use.
	// 以下旧任务 RPC 已停用；仅保留 wire 兼容，服务端不提供实现或授权。
	CreateTask(context.Context, *CreateTaskRequest) (*CreateTaskResponse, error)
	// Deprecated: Do not use.
	GetTask(context.Context, *GetTaskRequest) (*GetTaskResponse, error)
	// Deprecated: Do not use.
	LeaseTask(context.Context, *LeaseTaskRequest) (*LeaseTaskResponse, error)
	// Deprecated: Do not use.
	ResolveTaskCredential(context.Context, *ResolveTaskCredentialRequest) (*ResolveTaskCredentialResponse, error)
	// Deprecated: Do not use.
	CheckExecutionAdmission(context.Context, *CheckExecutionAdmissionRequest) (*CheckExecutionAdmissionResponse, error)
	// Deprecated: Do not use.
	CompleteTask(context.Context, *CompleteTaskRequest) (*CompleteTaskResponse, error)
	mustEmbedUnimplementedCredentialsServiceServer()
}

// UnimplementedCredentialsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCredentialsServiceServer struct{}

func (UnimplementedCredentialsServiceServer) GetCredentialMetadata(context.Context, *GetCredentialMetadataRequest) (*GetCredentialMetadataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCredentialMetadata not implemented")
}
func (UnimplementedCredentialsServiceServer) ListCredentialMetadata(context.Context, *ListCredentialMetadataRequest) (*ListCredentialMetadataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCredentialMetadata not implemented")
}
func (UnimplementedCredentialsServiceServer) ResolveCredential(context.Context, *ResolveCredentialRequest) (*ResolveCredentialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveCredential not implemented")
}
func (UnimplementedCredentialsServiceServer) ValidateCredentialUse(context.Context, *ValidateCredentialUseRequest) (*ValidateCredentialUseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateCredentialUse not implemented")
}
func (UnimplementedCredentialsServiceServer) ReportCredentialHealth(context.Context, *ReportCredentialHealthRequest) (*ReportCredentialHealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportCredentialHealth not implemented")
}
func (UnimplementedCredentialsServiceServer) CreateBindingIntent(context.Context, *CreateBindingIntentRequest) (*CreateBindingIntentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateBindingIntent not implemented")
}
func (UnimplementedCredentialsServiceServer) GetHostingStatus(context.Context, *GetHostingStatusRequest) (*GetHostingStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHostingStatus not implemented")
}
func (UnimplementedCredentialsServiceServer) UpdateGrant(context.Context, *UpdateGrantRequest) (*UpdateGrantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateGrant not implemented")
}
func (UnimplementedCredentialsServiceServer) RevokeCredential(context.Context, *RevokeCredentialRequest) (*RevokeCredentialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeCredential not implemented")
}
func (UnimplementedCredentialsServiceServer) FenceSubject(context.Context, *FenceSubjectRequest) (*FenceSubjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FenceSubject not implemented")
}
func (UnimplementedCredentialsServiceServer) CreateTask(context.Context, *CreateTaskRequest) (*CreateTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTask not implemented")
}
func (UnimplementedCredentialsServiceServer) GetTask(context.Context, *GetTaskRequest) (*GetTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTask not implemented")
}
func (UnimplementedCredentialsServiceServer) LeaseTask(context.Context, *LeaseTaskRequest) (*LeaseTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LeaseTask not implemented")
}
func (UnimplementedCredentialsServiceServer) ResolveTaskCredential(context.Context, *ResolveTaskCredentialRequest) (*ResolveTaskCredentialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveTaskCredential not implemented")
}
func (UnimplementedCredentialsServiceServer) CheckExecutionAdmission(context.Context, *CheckExecutionAdmissionRequest) (*CheckExecutionAdmissionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckExecutionAdmission not implemented")
}
func (UnimplementedCredentialsServiceServer) CompleteTask(context.Context, *CompleteTaskRequest) (*CompleteTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteTask not implemented")
}
func (UnimplementedCredentialsServiceServer) mustEmbedUnimplementedCredentialsServiceServer() {}
func (UnimplementedCredentialsServiceServer) testEmbeddedByValue()                            {}

// UnsafeCredentialsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CredentialsServiceServer will
// result in compilation errors.
type UnsafeCredentialsServiceServer interface {
	mustEmbedUnimplementedCredentialsServiceServer()
}

func RegisterCredentialsServiceServer(s grpc.ServiceRegistrar, srv CredentialsServiceServer) {
	// If the following call panics, it indicates UnimplementedCredentialsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CredentialsService_ServiceDesc, srv)
}

func _CredentialsService_GetCredentialMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCredentialMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredentialsServiceServer).GetCredentialMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CredentialsService_GetCredentialMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredentialsServiceServer).GetCredentialMetadata(ctx, req.(*GetCredentialMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CredentialsService_ListCredentialMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCredentialMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredentialsServiceServer).ListCredentialMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CredentialsService_ListCredentialMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredentialsServiceServer).ListCredentialMetadata(ctx, req.(*ListCredentialMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CredentialsService_ResolveCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredentialsServiceServer).ResolveCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CredentialsService_ResolveCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredentialsServiceServer).ResolveCredential(ctx, req.(*ResolveCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CredentialsService_ValidateCredentialUse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateCredentialUseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredentialsServiceServer).ValidateCredentialUse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CredentialsService_ValidateCredentialUse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredentialsServiceServer).ValidateCredentialUse(ctx, req.(*ValidateCredentialUseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CredentialsService_ReportCredentialHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportCredentialHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredentialsServiceServer).ReportCredentialHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CredentialsService_ReportCredentialHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredentialsServiceServer).ReportCredentialHealth(ctx, req.(*ReportCredentialHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CredentialsService_CreateBindingIntent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBindingIntentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredentialsServiceServer).CreateBindingIntent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CredentialsService_CreateBindingIntent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredentialsServiceServer).CreateBindingIntent(ctx, req.(*CreateBindingIntentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CredentialsService_GetHostingStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHostingStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredentialsServiceServer).GetHostingStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CredentialsService_GetHostingStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredentialsServiceServer).GetHostingStatus(ctx, req.(*GetHostingStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CredentialsService_UpdateGrant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGrantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredentialsServiceServer).UpdateGrant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CredentialsService_UpdateGrant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredentialsServiceServer).UpdateGrant(ctx, req.(*UpdateGrantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CredentialsService_RevokeCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredentialsServiceServer).RevokeCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CredentialsService_RevokeCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredentialsServiceServer).RevokeCredential(ctx, req.(*RevokeCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CredentialsService_FenceSubject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FenceSubjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredentialsServiceServer).FenceSubject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CredentialsService_FenceSubject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredentialsServiceServer).FenceSubject(ctx, req.(*FenceSubjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CredentialsService_CreateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredentialsServiceServer).CreateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CredentialsService_CreateTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredentialsServiceServer).CreateTask(ctx, req.(*CreateTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CredentialsService_GetTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredentialsServiceServer).GetTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CredentialsService_GetTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredentialsServiceServer).GetTask(ctx, req.(*GetTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CredentialsService_LeaseTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaseTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredentialsServiceServer).LeaseTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CredentialsService_LeaseTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredentialsServiceServer).LeaseTask(ctx, req.(*LeaseTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CredentialsService_ResolveTaskCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveTaskCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredentialsServiceServer).ResolveTaskCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CredentialsService_ResolveTaskCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredentialsServiceServer).ResolveTaskCredential(ctx, req.(*ResolveTaskCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CredentialsService_CheckExecutionAdmission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckExecutionAdmissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredentialsServiceServer).CheckExecutionAdmission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CredentialsService_CheckExecutionAdmission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredentialsServiceServer).CheckExecutionAdmission(ctx, req.(*CheckExecutionAdmissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CredentialsService_CompleteTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredentialsServiceServer).CompleteTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CredentialsService_CompleteTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredentialsServiceServer).CompleteTask(ctx, req.(*CompleteTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CredentialsService_ServiceDesc is the grpc.ServiceDesc for CredentialsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CredentialsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "academic.credentials.v1.CredentialsService",
	HandlerType: (*CredentialsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCredentialMetadata",
			Handler:    _CredentialsService_GetCredentialMetadata_Handler,
		},
		{
			MethodName: "ListCredentialMetadata",
			Handler:    _CredentialsService_ListCredentialMetadata_Handler,
		},
		{
			MethodName: "ResolveCredential",
			Handler:    _CredentialsService_ResolveCredential_Handler,
		},
		{
			MethodName: "ValidateCredentialUse",
			Handler:    _CredentialsService_ValidateCredentialUse_Handler,
		},
		{
			MethodName: "ReportCredentialHealth",
			Handler:    _CredentialsService_ReportCredentialHealth_Handler,
		},
		{
			MethodName: "CreateBindingIntent",
			Handler:    _CredentialsService_CreateBindingIntent_Handler,
		},
		{
			MethodName: "GetHostingStatus",
			Handler:    _CredentialsService_GetHostingStatus_Handler,
		},
		{
			MethodName: "UpdateGrant",
			Handler:    _CredentialsService_UpdateGrant_Handler,
		},
		{
			MethodName: "RevokeCredential",
			Handler:    _CredentialsService_RevokeCredential_Handler,
		},
		{
			MethodName: "FenceSubject",
			Handler:    _CredentialsService_FenceSubject_Handler,
		},
		{
			MethodName: "CreateTask",
			Handler:    _CredentialsService_CreateTask_Handler,
		},
		{
			MethodName: "GetTask",
			Handler:    _CredentialsService_GetTask_Handler,
		},
		{
			MethodName: "LeaseTask",
			Handler:    _CredentialsService_LeaseTask_Handler,
		},
		{
			MethodName: "ResolveTaskCredential",
			Handler:    _CredentialsService_ResolveTaskCredential_Handler,
		},
		{
			MethodName: "CheckExecutionAdmission",
			Handler:    _CredentialsService_CheckExecutionAdmission_Handler,
		},
		{
			MethodName: "CompleteTask",
			Handler:    _CredentialsService_CompleteTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "academic/credentials/v1/credentials.proto",
}

const (
	AcademicCredentialAuthorityService_GetEligibility_FullMethodName            = "/academic.credentials.v1.AcademicCredentialAuthorityService/GetEligibility"
	AcademicCredentialAuthorityService_ConfirmBinding_FullMethodName            = "/academic.credentials.v1.AcademicCredentialAuthorityService/ConfirmBinding"
	AcademicCredentialAuthorityService_AuthorizeCredentialAccess_FullMethodName = "/academic.credentials.v1.AcademicCredentialAuthorityService/AuthorizeCredentialAccess"
)

// AcademicCredentialAuthorityServiceClient is the client API for AcademicCredentialAuthorityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AcademicCredentialAuthorityService 提供强一致身份资格边界；实现层必须执行内部 mTLS 身份策略。
type AcademicCredentialAuthorityServiceClient interface {
	GetEligibility(ctx context.Context, in *GetEligibilityRequest, opts ...grpc.CallOption) (*GetEligibilityResponse, error)
	ConfirmBinding(ctx context.Context, in *ConfirmBindingRequest, opts ...grpc.CallOption) (*ConfirmBindingResponse, error)
	// 通用访问票据由平台签发；凭据服务只核对引用和访问权限。
	AuthorizeCredentialAccess(ctx context.Context, in *AuthorizeCredentialAccessRequest, opts ...grpc.CallOption) (*AuthorizeCredentialAccessResponse, error)
}

type academicCredentialAuthorityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAcademicCredentialAuthorityServiceClient(cc grpc.ClientConnInterface) AcademicCredentialAuthorityServiceClient {
	return &academicCredentialAuthorityServiceClient{cc}
}

func (c *academicCredentialAuthorityServiceClient) GetEligibility(ctx context.Context, in *GetEligibilityRequest, opts ...grpc.CallOption) (*GetEligibilityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEligibilityResponse)
	err := c.cc.Invoke(ctx, AcademicCredentialAuthorityService_GetEligibility_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *academicCredentialAuthorityServiceClient) ConfirmBinding(ctx context.Context, in *ConfirmBindingRequest, opts ...grpc.CallOption) (*ConfirmBindingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmBindingResponse)
	err := c.cc.Invoke(ctx, AcademicCredentialAuthorityService_ConfirmBinding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *academicCredentialAuthorityServiceClient) AuthorizeCredentialAccess(ctx context.Context, in *AuthorizeCredentialAccessRequest, opts ...grpc.CallOption) (*AuthorizeCredentialAccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthorizeCredentialAccessResponse)
	err := c.cc.Invoke(ctx, AcademicCredentialAuthorityService_AuthorizeCredentialAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AcademicCredentialAuthorityServiceServer is the server API for AcademicCredentialAuthorityService service.
// All implementations must embed UnimplementedAcademicCredentialAuthorityServiceServer
// for forward compatibility.
//
// AcademicCredentialAuthorityService 提供强一致身份资格边界；实现层必须执行内部 mTLS 身份策略。
type AcademicCredentialAuthorityServiceServer interface {
	GetEligibility(context.Context, *GetEligibilityRequest) (*GetEligibilityResponse, error)
	ConfirmBinding(context.Context, *ConfirmBindingRequest) (*ConfirmBindingResponse, error)
	// 通用访问票据由平台签发；凭据服务只核对引用和访问权限。
	AuthorizeCredentialAccess(context.Context, *AuthorizeCredentialAccessRequest) (*AuthorizeCredentialAccessResponse, error)
	mustEmbedUnimplementedAcademicCredentialAuthorityServiceServer()
}

// UnimplementedAcademicCredentialAuthorityServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAcademicCredentialAuthorityServiceServer struct{}

func (UnimplementedAcademicCredentialAuthorityServiceServer) GetEligibility(context.Context, *GetEligibilityRequest) (*GetEligibilityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEligibility not implemented")
}
func (UnimplementedAcademicCredentialAuthorityServiceServer) ConfirmBinding(context.Context, *ConfirmBindingRequest) (*ConfirmBindingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfirmBinding not implemented")
}
func (UnimplementedAcademicCredentialAuthorityServiceServer) AuthorizeCredentialAccess(context.Context, *AuthorizeCredentialAccessRequest) (*AuthorizeCredentialAccessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AuthorizeCredentialAccess not implemented")
}
func (UnimplementedAcademicCredentialAuthorityServiceServer) mustEmbedUnimplementedAcademicCredentialAuthorityServiceServer() {
}
func (UnimplementedAcademicCredentialAuthorityServiceServer) testEmbeddedByValue() {}

// UnsafeAcademicCredentialAuthorityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AcademicCredentialAuthorityServiceServer will
// result in compilation errors.
type UnsafeAcademicCredentialAuthorityServiceServer interface {
	mustEmbedUnimplementedAcademicCredentialAuthorityServiceServer()
}

func RegisterAcademicCredentialAuthorityServiceServer(s grpc.ServiceRegistrar, srv AcademicCredentialAuthorityServiceServer) {
	// If the following call panics, it indicates UnimplementedAcademicCredentialAuthorityServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AcademicCredentialAuthorityService_ServiceDesc, srv)
}

func _AcademicCredentialAuthorityService_GetEligibility_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEligibilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcademicCredentialAuthorityServiceServer).GetEligibility(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AcademicCredentialAuthorityService_GetEligibility_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcademicCredentialAuthorityServiceServer).GetEligibility(ctx, req.(*GetEligibilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AcademicCredentialAuthorityService_ConfirmBinding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmBindingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcademicCredentialAuthorityServiceServer).ConfirmBinding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AcademicCredentialAuthorityService_ConfirmBinding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcademicCredentialAuthorityServiceServer).ConfirmBinding(ctx, req.(*ConfirmBindingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AcademicCredentialAuthorityService_AuthorizeCredentialAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorizeCredentialAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcademicCredentialAuthorityServiceServer).AuthorizeCredentialAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AcademicCredentialAuthorityService_AuthorizeCredentialAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcademicCredentialAuthorityServiceServer).AuthorizeCredentialAccess(ctx, req.(*AuthorizeCredentialAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AcademicCredentialAuthorityService_ServiceDesc is the grpc.ServiceDesc for AcademicCredentialAuthorityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AcademicCredentialAuthorityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "academic.credentials.v1.AcademicCredentialAuthorityService",
	HandlerType: (*AcademicCredentialAuthorityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEligibility",
			Handler:    _AcademicCredentialAuthorityService_GetEligibility_Handler,
		},
		{
			MethodName: "ConfirmBinding",
			Handler:    _AcademicCredentialAuthorityService_ConfirmBinding_Handler,
		},
		{
			MethodName: "AuthorizeCredentialAccess",
			Handler:    _AcademicCredentialAuthorityService_AuthorizeCredentialAccess_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "academic/credentials/v1/credentials.proto",
}
