// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: academic/credentials/v1/credentials.proto

package academiccredentialsv1

import (
	v1 "github.com/LDouble/campus-academic-api/pkg/academic/provider/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Subject struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StudentNo       string                 `protobuf:"bytes,2,opt,name=student_no,json=studentNo,proto3" json:"student_no,omitempty"`
	Provider        string                 `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	EducationLevel  string                 `protobuf:"bytes,4,opt,name=education_level,json=educationLevel,proto3" json:"education_level,omitempty"`
	IdentityVersion uint64                 `protobuf:"varint,5,opt,name=identity_version,json=identityVersion,proto3" json:"identity_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Subject) Reset() {
	*x = Subject{}
	mi := &file_academic_credentials_v1_credentials_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subject) ProtoMessage() {}

func (x *Subject) ProtoReflect() protoreflect.Message {
	mi := &file_academic_credentials_v1_credentials_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subject.ProtoReflect.Descriptor instead.
func (*Subject) Descriptor() ([]byte, []int) {
	return file_academic_credentials_v1_credentials_proto_rawDescGZIP(), []int{0}
}

func (x *Subject) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Subject) GetStudentNo() string {
	if x != nil {
		return x.StudentNo
	}
	return ""
}

func (x *Subject) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *Subject) GetEducationLevel() string {
	if x != nil {
		return x.EducationLevel
	}
	return ""
}

func (x *Subject) GetIdentityVersion() uint64 {
	if x != nil {
		return x.IdentityVersion
	}
	return 0
}

type HostingStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Enabled 表示托管功能当前可用。
	Enabled      bool   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	CredentialId string `protobuf:"bytes,2,opt,name=credential_id,json=credentialId,proto3" json:"credential_id,omitempty"`
	Revision     uint64 `protobuf:"varint,3,opt,name=revision,proto3" json:"revision,omitempty"`
	// State 取值为 none、active、reauth_required、action_required 或 revoked。
	State         string `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	AutomaticSync bool   `protobuf:"varint,5,opt,name=automatic_sync,json=automaticSync,proto3" json:"automatic_sync,omitempty"`
	// PolicyVersion 是服务端生效的策略版本。
	PolicyVersion     string                 `protobuf:"bytes,6,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
	LastSyncAt        *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_sync_at,json=lastSyncAt,proto3" json:"last_sync_at,omitempty"`
	LastErrorCode     string                 `protobuf:"bytes,8,opt,name=last_error_code,json=lastErrorCode,proto3" json:"last_error_code,omitempty"`
	RevocationPending bool                   `protobuf:"varint,9,opt,name=revocation_pending,json=revocationPending,proto3" json:"revocation_pending,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HostingStatus) Reset() {
	*x = HostingStatus{}
	mi := &file_academic_credentials_v1_credentials_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostingStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostingStatus) ProtoMessage() {}

func (x *HostingStatus) ProtoReflect() protoreflect.Message {
	mi := &file_academic_credentials_v1_credentials_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostingStatus.ProtoReflect.Descriptor instead.
func (*HostingStatus) Descriptor() ([]byte, []int) {
	return file_academic_credentials_v1_credentials_proto_rawDescGZIP(), []int{1}
}

func (x *HostingStatus) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *HostingStatus) GetCredentialId() string {
	if x != nil {
		return x.CredentialId
	}
	return ""
}

func (x *HostingStatus) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *HostingStatus) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *HostingStatus) GetAutomaticSync() bool {
	if x != nil {
		return x.AutomaticSync
	}
	return false
}

func (x *HostingStatus) GetPolicyVersion() string {
	if x != nil {
		return x.PolicyVersion
	}
	return ""
}

func (x *HostingStatus) GetLastSyncAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSyncAt
	}
	return nil
}

func (x *HostingStatus) GetLastErrorCode() string {
	if x != nil {
		return x.LastErrorCode
	}
	return ""
}

func (x *HostingStatus) GetRevocationPending() bool {
	if x != nil {
		return x.RevocationPending
	}
	return false
}

type CreateBindingIntentRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EducationLevel   string                 `protobuf:"bytes,2,opt,name=education_level,json=educationLevel,proto3" json:"education_level,omitempty"`
	ExpectedRevision uint64                 `protobuf:"varint,3,opt,name=expected_revision,json=expectedRevision,proto3" json:"expected_revision,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateBindingIntentRequest) Reset() {
	*x = CreateBindingIntentRequest{}
	mi := &file_academic_credentials_v1_credentials_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBindingIntentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBindingIntentRequest) ProtoMessage() {}

func (x *CreateBindingIntentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_academic_credentials_v1_credentials_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBindingIntentRequest.ProtoReflect.Descriptor instead.
func (*CreateBindingIntentRequest) Descriptor() ([]byte, []int) {
	return file_academic_credentials_v1_credentials_proto_rawDescGZIP(), []int{2}
}

func (x *CreateBindingIntentRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateBindingIntentRequest) GetEducationLevel() string {
	if x != nil {
		return x.EducationLevel
	}
	return ""
}

func (x *CreateBindingIntentRequest) GetExpectedRevision() uint64 {
	if x != nil {
		return x.ExpectedRevision
	}
	return 0
}

type CreateBindingIntentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IntentId      string                 `protobuf:"bytes,1,opt,name=intent_id,json=intentId,proto3" json:"intent_id,omitempty"`
	SubmitUrl     string                 `protobuf:"bytes,2,opt,name=submit_url,json=submitUrl,proto3" json:"submit_url,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBindingIntentResponse) Reset() {
	*x = CreateBindingIntentResponse{}
	mi := &file_academic_credentials_v1_credentials_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBindingIntentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBindingIntentResponse) ProtoMessage() {}

func (x *CreateBindingIntentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_academic_credentials_v1_credentials_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBindingIntentResponse.ProtoReflect.Descriptor instead.
func (*CreateBindingIntentResponse) Descriptor() ([]byte, []int) {
	return file_academic_credentials_v1_credentials_proto_rawDescGZIP(), []int{3}
}

func (x *CreateBindingIntentResponse) GetIntentId() string {
	if x != nil {
		return x.IntentId
	}
	return ""
}

func (x *CreateBindingIntentResponse) GetSubmitUrl() string {
	if x != nil {
		return x.SubmitUrl
	}
	return ""
}

func (x *CreateBindingIntentResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CreateBindingIntentResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type GetHostingStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHostingStatusRequest) Reset() {
	*x = GetHostingStatusRequest{}
	mi := &file_academic_credentials_v1_credentials_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHostingStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHostingStatusRequest) ProtoMessage() {}

func (x *GetHostingStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_academic_credentials_v1_credentials_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHostingStatusRequest.ProtoReflect.Descriptor instead.
func (*GetHostingStatusRequest) Descriptor() ([]byte, []int) {
	return file_academic_credentials_v1_credentials_proto_rawDescGZIP(), []int{4}
}

func (x *GetHostingStatusRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetHostingStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *HostingStatus         `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHostingStatusResponse) Reset() {
	*x = GetHostingStatusResponse{}
	mi := &file_academic_credentials_v1_credentials_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHostingStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHostingStatusResponse) ProtoMessage() {}

func (x *GetHostingStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_academic_credentials_v1_credentials_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHostingStatusResponse.ProtoReflect.Descriptor instead.
func (*GetHostingStatusResponse) Descriptor() ([]byte, []int) {
	return file_academic_credentials_v1_credentials_proto_rawDescGZIP(), []int{5}
}

func (x *GetHostingStatusResponse) GetStatus() *HostingStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type UpdateGrantRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ExpectedRevision uint64                 `protobuf:"varint,2,opt,name=expected_revision,json=expectedRevision,proto3" json:"expected_revision,omitempty"`
	AutomaticSync    bool                   `protobuf:"varint,3,opt,name=automatic_sync,json=automaticSync,proto3" json:"automatic_sync,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateGrantRequest) Reset() {
	*x = UpdateGrantRequest{}
	mi := &file_academic_credentials_v1_credentials_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGrantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGrantRequest) ProtoMessage() {}

func (x *UpdateGrantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_academic_credentials_v1_credentials_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGrantRequest.ProtoReflect.Descriptor instead.
func (*UpdateGrantRequest) Descriptor() ([]byte, []int) {
	return file_academic_credentials_v1_credentials_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateGrantRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateGrantRequest) GetExpectedRevision() uint64 {
	if x != nil {
		return x.ExpectedRevision
	}
	return 0
}

func (x *UpdateGrantRequest) GetAutomaticSync() bool {
	if x != nil {
		return x.AutomaticSync
	}
	return false
}

type UpdateGrantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *HostingStatus         `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGrantResponse) Reset() {
	*x = UpdateGrantResponse{}
	mi := &file_academic_credentials_v1_credentials_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGrantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGrantResponse) ProtoMessage() {}

func (x *UpdateGrantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_academic_credentials_v1_credentials_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGrantResponse.ProtoReflect.Descriptor instead.
func (*UpdateGrantResponse) Descriptor() ([]byte, []int) {
	return file_academic_credentials_v1_credentials_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateGrantResponse) GetStatus() *HostingStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type RevokeCredentialRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ExpectedRevision uint64                 `protobuf:"varint,2,opt,name=expected_revision,json=expectedRevision,proto3" json:"expected_revision,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RevokeCredentialRequest) Reset() {
	*x = RevokeCredentialRequest{}
	mi := &file_academic_credentials_v1_credentials_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeCredentialRequest) ProtoMessage() {}

func (x *RevokeCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_academic_credentials_v1_credentials_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeCredentialRequest.ProtoReflect.Descriptor instead.
func (*RevokeCredentialRequest) Descriptor() ([]byte, []int) {
	return file_academic_credentials_v1_credentials_proto_rawDescGZIP(), []int{8}
}

func (x *RevokeCredentialRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RevokeCredentialRequest) GetExpectedRevision() uint64 {
	if x != nil {
		return x.ExpectedRevision
	}
	return 0
}

type RevokeCredentialResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *HostingStatus         `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeCredentialResponse) Reset() {
	*x = RevokeCredentialResponse{}
	mi := &file_academic_credentials_v1_credentials_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeCredentialResponse) ProtoMessage() {}

func (x *RevokeCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_academic_credentials_v1_credentials_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeCredentialResponse.ProtoReflect.Descriptor instead.
func (*RevokeCredentialResponse) Descriptor() ([]byte, []int) {
	return file_academic_credentials_v1_credentials_proto_rawDescGZIP(), []int{9}
}

func (x *RevokeCredentialResponse) GetStatus() *HostingStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type FenceSubjectRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IdentityVersion uint64                 `protobuf:"varint,2,opt,name=identity_version,json=identityVersion,proto3" json:"identity_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FenceSubjectRequest) Reset() {
	*x = FenceSubjectRequest{}
	mi := &file_academic_credentials_v1_credentials_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FenceSubjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FenceSubjectRequest) ProtoMessage() {}

func (x *FenceSubjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_academic_credentials_v1_credentials_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FenceSubjectRequest.ProtoReflect.Descriptor instead.
func (*FenceSubjectRequest) Descriptor() ([]byte, []int) {
	return file_academic_credentials_v1_credentials_proto_rawDescGZIP(), []int{10}
}

func (x *FenceSubjectRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FenceSubjectRequest) GetIdentityVersion() uint64 {
	if x != nil {
		return x.IdentityVersion
	}
	return 0
}

type FenceSubjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FenceSubjectResponse) Reset() {
	*x = FenceSubjectResponse{}
	mi := &file_academic_credentials_v1_credentials_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FenceSubjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FenceSubjectResponse) ProtoMessage() {}

func (x *FenceSubjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_academic_credentials_v1_credentials_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FenceSubjectResponse.ProtoReflect.Descriptor instead.
func (*FenceSubjectResponse) Descriptor() ([]byte, []int) {
	return file_academic_credentials_v1_credentials_proto_rawDescGZIP(), []int{11}
}

func (x *FenceSubjectResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

type CreateTaskRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	UserId uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// 后台自动任务每日仅创建 courses 和 exams；其他只读查询由用户主动触发。
	Purpose        string `protobuf:"bytes,2,opt,name=purpose,proto3" json:"purpose,omitempty"`
	PeriodId       string `protobuf:"bytes,3,opt,name=period_id,json=periodId,proto3" json:"period_id,omitempty"`
	IdempotencyKey string `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_academic_credentials_v1_credentials_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_academic_credentials_v1_credentials_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_academic_credentials_v1_credentials_proto_rawDescGZIP(), []int{12}
}

func (x *CreateTaskRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateTaskRequest) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *CreateTaskRequest) GetPeriodId() string {
	if x != nil {
		return x.PeriodId
	}
	return ""
}

func (x *CreateTaskRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type CreateTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskResponse) Reset() {
	*x = CreateTaskResponse{}
	mi := &file_academic_credentials_v1_credentials_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskResponse) ProtoMessage() {}

func (x *CreateTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_academic_credentials_v1_credentials_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskResponse.ProtoReflect.Descriptor instead.
func (*CreateTaskResponse) Descriptor() ([]byte, []int) {
	return file_academic_credentials_v1_credentials_proto_rawDescGZIP(), []int{13}
}

func (x *CreateTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_academic_credentials_v1_credentials_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_academic_credentials_v1_credentials_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_academic_credentials_v1_credentials_proto_rawDescGZIP(), []int{14}
}

func (x *GetTaskRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type GetTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskResponse) Reset() {
	*x = GetTaskResponse{}
	mi := &file_academic_credentials_v1_credentials_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskResponse) ProtoMessage() {}

func (x *GetTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_academic_credentials_v1_credentials_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskResponse.ProtoReflect.Descriptor instead.
func (*GetTaskResponse) Descriptor() ([]byte, []int) {
	return file_academic_credentials_v1_credentials_proto_rawDescGZIP(), []int{15}
}

func (x *GetTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type Task struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TaskId             string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Purpose            string                 `protobuf:"bytes,2,opt,name=purpose,proto3" json:"purpose,omitempty"`
	PeriodId           string                 `protobuf:"bytes,3,opt,name=period_id,json=periodId,proto3" json:"period_id,omitempty"`
	State              string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	CredentialRevision uint64                 `protobuf:"varint,5,opt,name=credential_revision,json=credentialRevision,proto3" json:"credential_revision,omitempty"`
	GrantEpoch         uint64                 `protobuf:"varint,6,opt,name=grant_epoch,json=grantEpoch,proto3" json:"grant_epoch,omitempty"`
	ErrorCode          string                 `protobuf:"bytes,7,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	CreatedAt          *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CompletedAt        *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	Result             *TaskResult            `protobuf:"bytes,10,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_academic_credentials_v1_credentials_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_academic_credentials_v1_credentials_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_academic_credentials_v1_credentials_proto_rawDescGZIP(), []int{16}
}

func (x *Task) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Task) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *Task) GetPeriodId() string {
	if x != nil {
		return x.PeriodId
	}
	return ""
}

func (x *Task) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Task) GetCredentialRevision() uint64 {
	if x != nil {
		return x.CredentialRevision
	}
	return 0
}

func (x *Task) GetGrantEpoch() uint64 {
	if x != nil {
		return x.GrantEpoch
	}
	return 0
}

func (x *Task) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *Task) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Task) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *Task) GetResult() *TaskResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type TaskResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 前台用户可主动查询所有既有只读结果；后台定时任务只允许 courses 和 exams。
	//
	// Types that are valid to be assigned to Result:
	//
	//	*TaskResult_Courses
	//	*TaskResult_Exams
	//	*TaskResult_Grades
	//	*TaskResult_CourseSelections
	//	*TaskResult_CourseSelectionSchedule
	//	*TaskResult_CourseAdditionResults
	Result        isTaskResult_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_academic_credentials_v1_credentials_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_academic_credentials_v1_credentials_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_academic_credentials_v1_credentials_proto_rawDescGZIP(), []int{17}
}

func (x *TaskResult) GetResult() isTaskResult_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *TaskResult) GetCourses() *v1.ListCoursesResponse {
	if x != nil {
		if x, ok := x.Result.(*TaskResult_Courses); ok {
			return x.Courses
		}
	}
	return nil
}

func (x *TaskResult) GetExams() *v1.ListExamsResponse {
	if x != nil {
		if x, ok := x.Result.(*TaskResult_Exams); ok {
			return x.Exams
		}
	}
	return nil
}

func (x *TaskResult) GetGrades() *v1.ListGradesResponse {
	if x != nil {
		if x, ok := x.Result.(*TaskResult_Grades); ok {
			return x.Grades
		}
	}
	return nil
}

func (x *TaskResult) GetCourseSelections() *v1.ListCourseSelectionsResponse {
	if x != nil {
		if x, ok := x.Result.(*TaskResult_CourseSelections); ok {
			return x.CourseSelections
		}
	}
	return nil
}

func (x *TaskResult) GetCourseSelectionSchedule() *v1.GetCourseSelectionScheduleResponse {
	if x != nil {
		if x, ok := x.Result.(*TaskResult_CourseSelectionSchedule); ok {
			return x.CourseSelectionSchedule
		}
	}
	return nil
}

func (x *TaskResult) GetCourseAdditionResults() *v1.ListCourseAdditionResultsResponse {
	if x != nil {
		if x, ok := x.Result.(*TaskResult_CourseAdditionResults); ok {
			return x.CourseAdditionResults
		}
	}
	return nil
}

type isTaskResult_Result interface {
	isTaskResult_Result()
}

type TaskResult_Courses struct {
	Courses *v1.ListCoursesResponse `protobuf:"bytes,1,opt,name=courses,proto3,oneof"`
}

type TaskResult_Exams struct {
	Exams *v1.ListExamsResponse `protobuf:"bytes,2,opt,name=exams,proto3,oneof"`
}

type TaskResult_Grades struct {
	Grades *v1.ListGradesResponse `protobuf:"bytes,3,opt,name=grades,proto3,oneof"`
}

type TaskResult_CourseSelections struct {
	CourseSelections *v1.ListCourseSelectionsResponse `protobuf:"bytes,4,opt,name=course_selections,json=courseSelections,proto3,oneof"`
}

type TaskResult_CourseSelectionSchedule struct {
	CourseSelectionSchedule *v1.GetCourseSelectionScheduleResponse `protobuf:"bytes,5,opt,name=course_selection_schedule,json=courseSelectionSchedule,proto3,oneof"`
}

type TaskResult_CourseAdditionResults struct {
	CourseAdditionResults *v1.ListCourseAdditionResultsResponse `protobuf:"bytes,6,opt,name=course_addition_results,json=courseAdditionResults,proto3,oneof"`
}

func (*TaskResult_Courses) isTaskResult_Result() {}

func (*TaskResult_Exams) isTaskResult_Result() {}

func (*TaskResult_Grades) isTaskResult_Result() {}

func (*TaskResult_CourseSelections) isTaskResult_Result() {}

func (*TaskResult_CourseSelectionSchedule) isTaskResult_Result() {}

func (*TaskResult_CourseAdditionResults) isTaskResult_Result() {}

// Worker 由内部客户端证书识别，因此请求不携带用户身份。
type LeaseTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaseTaskRequest) Reset() {
	*x = LeaseTaskRequest{}
	mi := &file_academic_credentials_v1_credentials_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseTaskRequest) ProtoMessage() {}

func (x *LeaseTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_academic_credentials_v1_credentials_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseTaskRequest.ProtoReflect.Descriptor instead.
func (*LeaseTaskRequest) Descriptor() ([]byte, []int) {
	return file_academic_credentials_v1_credentials_proto_rawDescGZIP(), []int{18}
}

type LeaseTaskResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Task 为空表示当前没有可执行任务。
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	LeaseToken    string                 `protobuf:"bytes,2,opt,name=lease_token,json=leaseToken,proto3" json:"lease_token,omitempty"`
	Fence         uint64                 `protobuf:"varint,3,opt,name=fence,proto3" json:"fence,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaseTaskResponse) Reset() {
	*x = LeaseTaskResponse{}
	mi := &file_academic_credentials_v1_credentials_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseTaskResponse) ProtoMessage() {}

func (x *LeaseTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_academic_credentials_v1_credentials_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseTaskResponse.ProtoReflect.Descriptor instead.
func (*LeaseTaskResponse) Descriptor() ([]byte, []int) {
	return file_academic_credentials_v1_credentials_proto_rawDescGZIP(), []int{19}
}

func (x *LeaseTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *LeaseTaskResponse) GetLeaseToken() string {
	if x != nil {
		return x.LeaseToken
	}
	return ""
}

func (x *LeaseTaskResponse) GetFence() uint64 {
	if x != nil {
		return x.Fence
	}
	return 0
}

func (x *LeaseTaskResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type ResolveTaskCredentialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	LeaseToken    string                 `protobuf:"bytes,2,opt,name=lease_token,json=leaseToken,proto3" json:"lease_token,omitempty"`
	Fence         uint64                 `protobuf:"varint,3,opt,name=fence,proto3" json:"fence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveTaskCredentialRequest) Reset() {
	*x = ResolveTaskCredentialRequest{}
	mi := &file_academic_credentials_v1_credentials_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveTaskCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveTaskCredentialRequest) ProtoMessage() {}

func (x *ResolveTaskCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_academic_credentials_v1_credentials_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveTaskCredentialRequest.ProtoReflect.Descriptor instead.
func (*ResolveTaskCredentialRequest) Descriptor() ([]byte, []int) {
	return file_academic_credentials_v1_credentials_proto_rawDescGZIP(), []int{20}
}

func (x *ResolveTaskCredentialRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ResolveTaskCredentialRequest) GetLeaseToken() string {
	if x != nil {
		return x.LeaseToken
	}
	return ""
}

func (x *ResolveTaskCredentialRequest) GetFence() uint64 {
	if x != nil {
		return x.Fence
	}
	return 0
}

type ResolveTaskCredentialResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Subject            *Subject               `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Credential         *v1.Credential         `protobuf:"bytes,2,opt,name=credential,proto3" json:"credential,omitempty"`
	CredentialId       string                 `protobuf:"bytes,3,opt,name=credential_id,json=credentialId,proto3" json:"credential_id,omitempty"`
	CredentialRevision uint64                 `protobuf:"varint,4,opt,name=credential_revision,json=credentialRevision,proto3" json:"credential_revision,omitempty"`
	GrantEpoch         uint64                 `protobuf:"varint,5,opt,name=grant_epoch,json=grantEpoch,proto3" json:"grant_epoch,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ResolveTaskCredentialResponse) Reset() {
	*x = ResolveTaskCredentialResponse{}
	mi := &file_academic_credentials_v1_credentials_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveTaskCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveTaskCredentialResponse) ProtoMessage() {}

func (x *ResolveTaskCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_academic_credentials_v1_credentials_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveTaskCredentialResponse.ProtoReflect.Descriptor instead.
func (*ResolveTaskCredentialResponse) Descriptor() ([]byte, []int) {
	return file_academic_credentials_v1_credentials_proto_rawDescGZIP(), []int{21}
}

func (x *ResolveTaskCredentialResponse) GetSubject() *Subject {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *ResolveTaskCredentialResponse) GetCredential() *v1.Credential {
	if x != nil {
		return x.Credential
	}
	return nil
}

func (x *ResolveTaskCredentialResponse) GetCredentialId() string {
	if x != nil {
		return x.CredentialId
	}
	return ""
}

func (x *ResolveTaskCredentialResponse) GetCredentialRevision() uint64 {
	if x != nil {
		return x.CredentialRevision
	}
	return 0
}

func (x *ResolveTaskCredentialResponse) GetGrantEpoch() uint64 {
	if x != nil {
		return x.GrantEpoch
	}
	return 0
}

type CheckExecutionAdmissionRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	TaskId     string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	LeaseToken string                 `protobuf:"bytes,2,opt,name=lease_token,json=leaseToken,proto3" json:"lease_token,omitempty"`
	Fence      uint64                 `protobuf:"varint,3,opt,name=fence,proto3" json:"fence,omitempty"`
	// Phase 取值为 external、result 或 session，表示本次需要准入的副作用阶段。
	Phase         string `protobuf:"bytes,4,opt,name=phase,proto3" json:"phase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckExecutionAdmissionRequest) Reset() {
	*x = CheckExecutionAdmissionRequest{}
	mi := &file_academic_credentials_v1_credentials_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckExecutionAdmissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckExecutionAdmissionRequest) ProtoMessage() {}

func (x *CheckExecutionAdmissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_academic_credentials_v1_credentials_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckExecutionAdmissionRequest.ProtoReflect.Descriptor instead.
func (*CheckExecutionAdmissionRequest) Descriptor() ([]byte, []int) {
	return file_academic_credentials_v1_credentials_proto_rawDescGZIP(), []int{22}
}

func (x *CheckExecutionAdmissionRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CheckExecutionAdmissionRequest) GetLeaseToken() string {
	if x != nil {
		return x.LeaseToken
	}
	return ""
}

func (x *CheckExecutionAdmissionRequest) GetFence() uint64 {
	if x != nil {
		return x.Fence
	}
	return 0
}

func (x *CheckExecutionAdmissionRequest) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

type CheckExecutionAdmissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckExecutionAdmissionResponse) Reset() {
	*x = CheckExecutionAdmissionResponse{}
	mi := &file_academic_credentials_v1_credentials_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckExecutionAdmissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckExecutionAdmissionResponse) ProtoMessage() {}

func (x *CheckExecutionAdmissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_academic_credentials_v1_credentials_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckExecutionAdmissionResponse.ProtoReflect.Descriptor instead.
func (*CheckExecutionAdmissionResponse) Descriptor() ([]byte, []int) {
	return file_academic_credentials_v1_credentials_proto_rawDescGZIP(), []int{23}
}

func (x *CheckExecutionAdmissionResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

type CompleteTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	LeaseToken    string                 `protobuf:"bytes,2,opt,name=lease_token,json=leaseToken,proto3" json:"lease_token,omitempty"`
	Fence         uint64                 `protobuf:"varint,3,opt,name=fence,proto3" json:"fence,omitempty"`
	Result        *TaskResult            `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,5,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteTaskRequest) Reset() {
	*x = CompleteTaskRequest{}
	mi := &file_academic_credentials_v1_credentials_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteTaskRequest) ProtoMessage() {}

func (x *CompleteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_academic_credentials_v1_credentials_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteTaskRequest.ProtoReflect.Descriptor instead.
func (*CompleteTaskRequest) Descriptor() ([]byte, []int) {
	return file_academic_credentials_v1_credentials_proto_rawDescGZIP(), []int{24}
}

func (x *CompleteTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CompleteTaskRequest) GetLeaseToken() string {
	if x != nil {
		return x.LeaseToken
	}
	return ""
}

func (x *CompleteTaskRequest) GetFence() uint64 {
	if x != nil {
		return x.Fence
	}
	return 0
}

func (x *CompleteTaskRequest) GetResult() *TaskResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *CompleteTaskRequest) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

type CompleteTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteTaskResponse) Reset() {
	*x = CompleteTaskResponse{}
	mi := &file_academic_credentials_v1_credentials_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteTaskResponse) ProtoMessage() {}

func (x *CompleteTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_academic_credentials_v1_credentials_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteTaskResponse.ProtoReflect.Descriptor instead.
func (*CompleteTaskResponse) Descriptor() ([]byte, []int) {
	return file_academic_credentials_v1_credentials_proto_rawDescGZIP(), []int{25}
}

func (x *CompleteTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type GetEligibilityRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	UserId  uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Purpose string                 `protobuf:"bytes,2,opt,name=purpose,proto3" json:"purpose,omitempty"`
	// 每次请求使用新的 operation_id；资格从强一致数据库读取，结果不缓存。
	OperationId   string `protobuf:"bytes,3,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEligibilityRequest) Reset() {
	*x = GetEligibilityRequest{}
	mi := &file_academic_credentials_v1_credentials_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEligibilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEligibilityRequest) ProtoMessage() {}

func (x *GetEligibilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_academic_credentials_v1_credentials_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEligibilityRequest.ProtoReflect.Descriptor instead.
func (*GetEligibilityRequest) Descriptor() ([]byte, []int) {
	return file_academic_credentials_v1_credentials_proto_rawDescGZIP(), []int{26}
}

func (x *GetEligibilityRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetEligibilityRequest) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *GetEligibilityRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

type GetEligibilityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Eligible      bool                   `protobuf:"varint,1,opt,name=eligible,proto3" json:"eligible,omitempty"`
	Subject       *Subject               `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	OperationId   string                 `protobuf:"bytes,3,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	ReasonCode    string                 `protobuf:"bytes,4,opt,name=reason_code,json=reasonCode,proto3" json:"reason_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEligibilityResponse) Reset() {
	*x = GetEligibilityResponse{}
	mi := &file_academic_credentials_v1_credentials_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEligibilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEligibilityResponse) ProtoMessage() {}

func (x *GetEligibilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_academic_credentials_v1_credentials_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEligibilityResponse.ProtoReflect.Descriptor instead.
func (*GetEligibilityResponse) Descriptor() ([]byte, []int) {
	return file_academic_credentials_v1_credentials_proto_rawDescGZIP(), []int{27}
}

func (x *GetEligibilityResponse) GetEligible() bool {
	if x != nil {
		return x.Eligible
	}
	return false
}

func (x *GetEligibilityResponse) GetSubject() *Subject {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *GetEligibilityResponse) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *GetEligibilityResponse) GetReasonCode() string {
	if x != nil {
		return x.ReasonCode
	}
	return ""
}

// ConfirmBindingRequest 中的身份字段必须与已验证身份精确匹配。
// ConfirmBindingRequest 的身份必须精确匹配已验证身份，不得覆盖原认证方式、角色或状态；首次身份事务由后端负责。
type ConfirmBindingRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IntentId       string                 `protobuf:"bytes,2,opt,name=intent_id,json=intentId,proto3" json:"intent_id,omitempty"`
	StudentNo      string                 `protobuf:"bytes,3,opt,name=student_no,json=studentNo,proto3" json:"student_no,omitempty"`
	RealName       string                 `protobuf:"bytes,4,opt,name=real_name,json=realName,proto3" json:"real_name,omitempty"`
	Provider       string                 `protobuf:"bytes,5,opt,name=provider,proto3" json:"provider,omitempty"`
	EducationLevel string                 `protobuf:"bytes,6,opt,name=education_level,json=educationLevel,proto3" json:"education_level,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConfirmBindingRequest) Reset() {
	*x = ConfirmBindingRequest{}
	mi := &file_academic_credentials_v1_credentials_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmBindingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmBindingRequest) ProtoMessage() {}

func (x *ConfirmBindingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_academic_credentials_v1_credentials_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmBindingRequest.ProtoReflect.Descriptor instead.
func (*ConfirmBindingRequest) Descriptor() ([]byte, []int) {
	return file_academic_credentials_v1_credentials_proto_rawDescGZIP(), []int{28}
}

func (x *ConfirmBindingRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ConfirmBindingRequest) GetIntentId() string {
	if x != nil {
		return x.IntentId
	}
	return ""
}

func (x *ConfirmBindingRequest) GetStudentNo() string {
	if x != nil {
		return x.StudentNo
	}
	return ""
}

func (x *ConfirmBindingRequest) GetRealName() string {
	if x != nil {
		return x.RealName
	}
	return ""
}

func (x *ConfirmBindingRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ConfirmBindingRequest) GetEducationLevel() string {
	if x != nil {
		return x.EducationLevel
	}
	return ""
}

type ConfirmBindingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Eligible      bool                   `protobuf:"varint,1,opt,name=eligible,proto3" json:"eligible,omitempty"`
	Subject       *Subject               `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	ReasonCode    string                 `protobuf:"bytes,3,opt,name=reason_code,json=reasonCode,proto3" json:"reason_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmBindingResponse) Reset() {
	*x = ConfirmBindingResponse{}
	mi := &file_academic_credentials_v1_credentials_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmBindingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmBindingResponse) ProtoMessage() {}

func (x *ConfirmBindingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_academic_credentials_v1_credentials_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmBindingResponse.ProtoReflect.Descriptor instead.
func (*ConfirmBindingResponse) Descriptor() ([]byte, []int) {
	return file_academic_credentials_v1_credentials_proto_rawDescGZIP(), []int{29}
}

func (x *ConfirmBindingResponse) GetEligible() bool {
	if x != nil {
		return x.Eligible
	}
	return false
}

func (x *ConfirmBindingResponse) GetSubject() *Subject {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *ConfirmBindingResponse) GetReasonCode() string {
	if x != nil {
		return x.ReasonCode
	}
	return ""
}

var File_academic_credentials_v1_credentials_proto protoreflect.FileDescriptor

const file_academic_credentials_v1_credentials_proto_rawDesc = "" +
	"\n" +
	")academic/credentials/v1/credentials.proto\x12\x17academic.credentials.v1\x1a#academic/provider/v1/provider.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb1\x01\n" +
	"\aSubject\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1d\n" +
	"\n" +
	"student_no\x18\x02 \x01(\tR\tstudentNo\x12\x1a\n" +
	"\bprovider\x18\x03 \x01(\tR\bprovider\x12'\n" +
	"\x0feducation_level\x18\x04 \x01(\tR\x0eeducationLevel\x12)\n" +
	"\x10identity_version\x18\x05 \x01(\x04R\x0fidentityVersion\"\xe3\x02\n" +
	"\rHostingStatus\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12#\n" +
	"\rcredential_id\x18\x02 \x01(\tR\fcredentialId\x12\x1a\n" +
	"\brevision\x18\x03 \x01(\x04R\brevision\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12%\n" +
	"\x0eautomatic_sync\x18\x05 \x01(\bR\rautomaticSync\x12%\n" +
	"\x0epolicy_version\x18\x06 \x01(\tR\rpolicyVersion\x12<\n" +
	"\flast_sync_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastSyncAt\x12&\n" +
	"\x0flast_error_code\x18\b \x01(\tR\rlastErrorCode\x12-\n" +
	"\x12revocation_pending\x18\t \x01(\bR\x11revocationPending\"\xca\x01\n" +
	"\x1aCreateBindingIntentRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12'\n" +
	"\x0feducation_level\x18\x02 \x01(\tR\x0eeducationLevel\x12+\n" +
	"\x11expected_revision\x18\x03 \x01(\x04R\x10expectedRevisionJ\x04\b\x04\x10\aR\x0fconsent_versionR\x12foreground_consentR\x12background_consent\"\xaa\x01\n" +
	"\x1bCreateBindingIntentResponse\x12\x1b\n" +
	"\tintent_id\x18\x01 \x01(\tR\bintentId\x12\x1d\n" +
	"\n" +
	"submit_url\x18\x02 \x01(\tR\tsubmitUrl\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"2\n" +
	"\x17GetHostingStatusRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"Z\n" +
	"\x18GetHostingStatusResponse\x12>\n" +
	"\x06status\x18\x01 \x01(\v2&.academic.credentials.v1.HostingStatusR\x06status\"\x81\x01\n" +
	"\x12UpdateGrantRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12+\n" +
	"\x11expected_revision\x18\x02 \x01(\x04R\x10expectedRevision\x12%\n" +
	"\x0eautomatic_sync\x18\x03 \x01(\bR\rautomaticSync\"U\n" +
	"\x13UpdateGrantResponse\x12>\n" +
	"\x06status\x18\x01 \x01(\v2&.academic.credentials.v1.HostingStatusR\x06status\"_\n" +
	"\x17RevokeCredentialRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12+\n" +
	"\x11expected_revision\x18\x02 \x01(\x04R\x10expectedRevision\"Z\n" +
	"\x18RevokeCredentialResponse\x12>\n" +
	"\x06status\x18\x01 \x01(\v2&.academic.credentials.v1.HostingStatusR\x06status\"Y\n" +
	"\x13FenceSubjectRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12)\n" +
	"\x10identity_version\x18\x02 \x01(\x04R\x0fidentityVersion\":\n" +
	"\x14FenceSubjectResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\"\x8c\x01\n" +
	"\x11CreateTaskRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x18\n" +
	"\apurpose\x18\x02 \x01(\tR\apurpose\x12\x1b\n" +
	"\tperiod_id\x18\x03 \x01(\tR\bperiodId\x12'\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tR\x0eidempotencyKey\"G\n" +
	"\x12CreateTaskResponse\x121\n" +
	"\x04task\x18\x01 \x01(\v2\x1d.academic.credentials.v1.TaskR\x04task\"B\n" +
	"\x0eGetTaskRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\"D\n" +
	"\x0fGetTaskResponse\x121\n" +
	"\x04task\x18\x01 \x01(\v2\x1d.academic.credentials.v1.TaskR\x04task\"\x94\x03\n" +
	"\x04Task\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x18\n" +
	"\apurpose\x18\x02 \x01(\tR\apurpose\x12\x1b\n" +
	"\tperiod_id\x18\x03 \x01(\tR\bperiodId\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12/\n" +
	"\x13credential_revision\x18\x05 \x01(\x04R\x12credentialRevision\x12\x1f\n" +
	"\vgrant_epoch\x18\x06 \x01(\x04R\n" +
	"grantEpoch\x12\x1d\n" +
	"\n" +
	"error_code\x18\a \x01(\tR\terrorCode\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12=\n" +
	"\fcompleted_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x12;\n" +
	"\x06result\x18\n" +
	" \x01(\v2#.academic.credentials.v1.TaskResultR\x06result\"\xb0\x04\n" +
	"\n" +
	"TaskResult\x12E\n" +
	"\acourses\x18\x01 \x01(\v2).academic.provider.v1.ListCoursesResponseH\x00R\acourses\x12?\n" +
	"\x05exams\x18\x02 \x01(\v2'.academic.provider.v1.ListExamsResponseH\x00R\x05exams\x12B\n" +
	"\x06grades\x18\x03 \x01(\v2(.academic.provider.v1.ListGradesResponseH\x00R\x06grades\x12a\n" +
	"\x11course_selections\x18\x04 \x01(\v22.academic.provider.v1.ListCourseSelectionsResponseH\x00R\x10courseSelections\x12v\n" +
	"\x19course_selection_schedule\x18\x05 \x01(\v28.academic.provider.v1.GetCourseSelectionScheduleResponseH\x00R\x17courseSelectionSchedule\x12q\n" +
	"\x17course_addition_results\x18\x06 \x01(\v27.academic.provider.v1.ListCourseAdditionResultsResponseH\x00R\x15courseAdditionResultsB\b\n" +
	"\x06result\"\x12\n" +
	"\x10LeaseTaskRequest\"\xb8\x01\n" +
	"\x11LeaseTaskResponse\x121\n" +
	"\x04task\x18\x01 \x01(\v2\x1d.academic.credentials.v1.TaskR\x04task\x12\x1f\n" +
	"\vlease_token\x18\x02 \x01(\tR\n" +
	"leaseToken\x12\x14\n" +
	"\x05fence\x18\x03 \x01(\x04R\x05fence\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"n\n" +
	"\x1cResolveTaskCredentialRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1f\n" +
	"\vlease_token\x18\x02 \x01(\tR\n" +
	"leaseToken\x12\x14\n" +
	"\x05fence\x18\x03 \x01(\x04R\x05fence\"\x94\x02\n" +
	"\x1dResolveTaskCredentialResponse\x12:\n" +
	"\asubject\x18\x01 \x01(\v2 .academic.credentials.v1.SubjectR\asubject\x12@\n" +
	"\n" +
	"credential\x18\x02 \x01(\v2 .academic.provider.v1.CredentialR\n" +
	"credential\x12#\n" +
	"\rcredential_id\x18\x03 \x01(\tR\fcredentialId\x12/\n" +
	"\x13credential_revision\x18\x04 \x01(\x04R\x12credentialRevision\x12\x1f\n" +
	"\vgrant_epoch\x18\x05 \x01(\x04R\n" +
	"grantEpoch\"\x86\x01\n" +
	"\x1eCheckExecutionAdmissionRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1f\n" +
	"\vlease_token\x18\x02 \x01(\tR\n" +
	"leaseToken\x12\x14\n" +
	"\x05fence\x18\x03 \x01(\x04R\x05fence\x12\x14\n" +
	"\x05phase\x18\x04 \x01(\tR\x05phase\";\n" +
	"\x1fCheckExecutionAdmissionResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\"\xc1\x01\n" +
	"\x13CompleteTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1f\n" +
	"\vlease_token\x18\x02 \x01(\tR\n" +
	"leaseToken\x12\x14\n" +
	"\x05fence\x18\x03 \x01(\x04R\x05fence\x12;\n" +
	"\x06result\x18\x04 \x01(\v2#.academic.credentials.v1.TaskResultR\x06result\x12\x1d\n" +
	"\n" +
	"error_code\x18\x05 \x01(\tR\terrorCode\"I\n" +
	"\x14CompleteTaskResponse\x121\n" +
	"\x04task\x18\x01 \x01(\v2\x1d.academic.credentials.v1.TaskR\x04task\"m\n" +
	"\x15GetEligibilityRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x18\n" +
	"\apurpose\x18\x02 \x01(\tR\apurpose\x12!\n" +
	"\foperation_id\x18\x03 \x01(\tR\voperationId\"\xb4\x01\n" +
	"\x16GetEligibilityResponse\x12\x1a\n" +
	"\beligible\x18\x01 \x01(\bR\beligible\x12:\n" +
	"\asubject\x18\x02 \x01(\v2 .academic.credentials.v1.SubjectR\asubject\x12!\n" +
	"\foperation_id\x18\x03 \x01(\tR\voperationId\x12\x1f\n" +
	"\vreason_code\x18\x04 \x01(\tR\n" +
	"reasonCode\"\xce\x01\n" +
	"\x15ConfirmBindingRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1b\n" +
	"\tintent_id\x18\x02 \x01(\tR\bintentId\x12\x1d\n" +
	"\n" +
	"student_no\x18\x03 \x01(\tR\tstudentNo\x12\x1b\n" +
	"\treal_name\x18\x04 \x01(\tR\brealName\x12\x1a\n" +
	"\bprovider\x18\x05 \x01(\tR\bprovider\x12'\n" +
	"\x0feducation_level\x18\x06 \x01(\tR\x0eeducationLevel\"\x91\x01\n" +
	"\x16ConfirmBindingResponse\x12\x1a\n" +
	"\beligible\x18\x01 \x01(\bR\beligible\x12:\n" +
	"\asubject\x18\x02 \x01(\v2 .academic.credentials.v1.SubjectR\asubject\x12\x1f\n" +
	"\vreason_code\x18\x03 \x01(\tR\n" +
	"reasonCode2\x8e\n" +
	"\n" +
	"\x12CredentialsService\x12\x80\x01\n" +
	"\x13CreateBindingIntent\x123.academic.credentials.v1.CreateBindingIntentRequest\x1a4.academic.credentials.v1.CreateBindingIntentResponse\x12w\n" +
	"\x10GetHostingStatus\x120.academic.credentials.v1.GetHostingStatusRequest\x1a1.academic.credentials.v1.GetHostingStatusResponse\x12h\n" +
	"\vUpdateGrant\x12+.academic.credentials.v1.UpdateGrantRequest\x1a,.academic.credentials.v1.UpdateGrantResponse\x12w\n" +
	"\x10RevokeCredential\x120.academic.credentials.v1.RevokeCredentialRequest\x1a1.academic.credentials.v1.RevokeCredentialResponse\x12k\n" +
	"\fFenceSubject\x12,.academic.credentials.v1.FenceSubjectRequest\x1a-.academic.credentials.v1.FenceSubjectResponse\x12e\n" +
	"\n" +
	"CreateTask\x12*.academic.credentials.v1.CreateTaskRequest\x1a+.academic.credentials.v1.CreateTaskResponse\x12\\\n" +
	"\aGetTask\x12'.academic.credentials.v1.GetTaskRequest\x1a(.academic.credentials.v1.GetTaskResponse\x12b\n" +
	"\tLeaseTask\x12).academic.credentials.v1.LeaseTaskRequest\x1a*.academic.credentials.v1.LeaseTaskResponse\x12\x86\x01\n" +
	"\x15ResolveTaskCredential\x125.academic.credentials.v1.ResolveTaskCredentialRequest\x1a6.academic.credentials.v1.ResolveTaskCredentialResponse\x12\x8c\x01\n" +
	"\x17CheckExecutionAdmission\x127.academic.credentials.v1.CheckExecutionAdmissionRequest\x1a8.academic.credentials.v1.CheckExecutionAdmissionResponse\x12k\n" +
	"\fCompleteTask\x12,.academic.credentials.v1.CompleteTaskRequest\x1a-.academic.credentials.v1.CompleteTaskResponse2\x8a\x02\n" +
	"\"AcademicCredentialAuthorityService\x12q\n" +
	"\x0eGetEligibility\x12..academic.credentials.v1.GetEligibilityRequest\x1a/.academic.credentials.v1.GetEligibilityResponse\x12q\n" +
	"\x0eConfirmBinding\x12..academic.credentials.v1.ConfirmBindingRequest\x1a/.academic.credentials.v1.ConfirmBindingResponseBZZXgithub.com/LDouble/campus-academic-api/pkg/academic/credentials/v1;academiccredentialsv1b\x06proto3"

var (
	file_academic_credentials_v1_credentials_proto_rawDescOnce sync.Once
	file_academic_credentials_v1_credentials_proto_rawDescData []byte
)

func file_academic_credentials_v1_credentials_proto_rawDescGZIP() []byte {
	file_academic_credentials_v1_credentials_proto_rawDescOnce.Do(func() {
		file_academic_credentials_v1_credentials_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_academic_credentials_v1_credentials_proto_rawDesc), len(file_academic_credentials_v1_credentials_proto_rawDesc)))
	})
	return file_academic_credentials_v1_credentials_proto_rawDescData
}

var file_academic_credentials_v1_credentials_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_academic_credentials_v1_credentials_proto_goTypes = []any{
	(*Subject)(nil),                               // 0: academic.credentials.v1.Subject
	(*HostingStatus)(nil),                         // 1: academic.credentials.v1.HostingStatus
	(*CreateBindingIntentRequest)(nil),            // 2: academic.credentials.v1.CreateBindingIntentRequest
	(*CreateBindingIntentResponse)(nil),           // 3: academic.credentials.v1.CreateBindingIntentResponse
	(*GetHostingStatusRequest)(nil),               // 4: academic.credentials.v1.GetHostingStatusRequest
	(*GetHostingStatusResponse)(nil),              // 5: academic.credentials.v1.GetHostingStatusResponse
	(*UpdateGrantRequest)(nil),                    // 6: academic.credentials.v1.UpdateGrantRequest
	(*UpdateGrantResponse)(nil),                   // 7: academic.credentials.v1.UpdateGrantResponse
	(*RevokeCredentialRequest)(nil),               // 8: academic.credentials.v1.RevokeCredentialRequest
	(*RevokeCredentialResponse)(nil),              // 9: academic.credentials.v1.RevokeCredentialResponse
	(*FenceSubjectRequest)(nil),                   // 10: academic.credentials.v1.FenceSubjectRequest
	(*FenceSubjectResponse)(nil),                  // 11: academic.credentials.v1.FenceSubjectResponse
	(*CreateTaskRequest)(nil),                     // 12: academic.credentials.v1.CreateTaskRequest
	(*CreateTaskResponse)(nil),                    // 13: academic.credentials.v1.CreateTaskResponse
	(*GetTaskRequest)(nil),                        // 14: academic.credentials.v1.GetTaskRequest
	(*GetTaskResponse)(nil),                       // 15: academic.credentials.v1.GetTaskResponse
	(*Task)(nil),                                  // 16: academic.credentials.v1.Task
	(*TaskResult)(nil),                            // 17: academic.credentials.v1.TaskResult
	(*LeaseTaskRequest)(nil),                      // 18: academic.credentials.v1.LeaseTaskRequest
	(*LeaseTaskResponse)(nil),                     // 19: academic.credentials.v1.LeaseTaskResponse
	(*ResolveTaskCredentialRequest)(nil),          // 20: academic.credentials.v1.ResolveTaskCredentialRequest
	(*ResolveTaskCredentialResponse)(nil),         // 21: academic.credentials.v1.ResolveTaskCredentialResponse
	(*CheckExecutionAdmissionRequest)(nil),        // 22: academic.credentials.v1.CheckExecutionAdmissionRequest
	(*CheckExecutionAdmissionResponse)(nil),       // 23: academic.credentials.v1.CheckExecutionAdmissionResponse
	(*CompleteTaskRequest)(nil),                   // 24: academic.credentials.v1.CompleteTaskRequest
	(*CompleteTaskResponse)(nil),                  // 25: academic.credentials.v1.CompleteTaskResponse
	(*GetEligibilityRequest)(nil),                 // 26: academic.credentials.v1.GetEligibilityRequest
	(*GetEligibilityResponse)(nil),                // 27: academic.credentials.v1.GetEligibilityResponse
	(*ConfirmBindingRequest)(nil),                 // 28: academic.credentials.v1.ConfirmBindingRequest
	(*ConfirmBindingResponse)(nil),                // 29: academic.credentials.v1.ConfirmBindingResponse
	(*timestamppb.Timestamp)(nil),                 // 30: google.protobuf.Timestamp
	(*v1.ListCoursesResponse)(nil),                // 31: academic.provider.v1.ListCoursesResponse
	(*v1.ListExamsResponse)(nil),                  // 32: academic.provider.v1.ListExamsResponse
	(*v1.ListGradesResponse)(nil),                 // 33: academic.provider.v1.ListGradesResponse
	(*v1.ListCourseSelectionsResponse)(nil),       // 34: academic.provider.v1.ListCourseSelectionsResponse
	(*v1.GetCourseSelectionScheduleResponse)(nil), // 35: academic.provider.v1.GetCourseSelectionScheduleResponse
	(*v1.ListCourseAdditionResultsResponse)(nil),  // 36: academic.provider.v1.ListCourseAdditionResultsResponse
	(*v1.Credential)(nil),                         // 37: academic.provider.v1.Credential
}
var file_academic_credentials_v1_credentials_proto_depIdxs = []int32{
	30, // 0: academic.credentials.v1.HostingStatus.last_sync_at:type_name -> google.protobuf.Timestamp
	30, // 1: academic.credentials.v1.CreateBindingIntentResponse.expires_at:type_name -> google.protobuf.Timestamp
	1,  // 2: academic.credentials.v1.GetHostingStatusResponse.status:type_name -> academic.credentials.v1.HostingStatus
	1,  // 3: academic.credentials.v1.UpdateGrantResponse.status:type_name -> academic.credentials.v1.HostingStatus
	1,  // 4: academic.credentials.v1.RevokeCredentialResponse.status:type_name -> academic.credentials.v1.HostingStatus
	16, // 5: academic.credentials.v1.CreateTaskResponse.task:type_name -> academic.credentials.v1.Task
	16, // 6: academic.credentials.v1.GetTaskResponse.task:type_name -> academic.credentials.v1.Task
	30, // 7: academic.credentials.v1.Task.created_at:type_name -> google.protobuf.Timestamp
	30, // 8: academic.credentials.v1.Task.completed_at:type_name -> google.protobuf.Timestamp
	17, // 9: academic.credentials.v1.Task.result:type_name -> academic.credentials.v1.TaskResult
	31, // 10: academic.credentials.v1.TaskResult.courses:type_name -> academic.provider.v1.ListCoursesResponse
	32, // 11: academic.credentials.v1.TaskResult.exams:type_name -> academic.provider.v1.ListExamsResponse
	33, // 12: academic.credentials.v1.TaskResult.grades:type_name -> academic.provider.v1.ListGradesResponse
	34, // 13: academic.credentials.v1.TaskResult.course_selections:type_name -> academic.provider.v1.ListCourseSelectionsResponse
	35, // 14: academic.credentials.v1.TaskResult.course_selection_schedule:type_name -> academic.provider.v1.GetCourseSelectionScheduleResponse
	36, // 15: academic.credentials.v1.TaskResult.course_addition_results:type_name -> academic.provider.v1.ListCourseAdditionResultsResponse
	16, // 16: academic.credentials.v1.LeaseTaskResponse.task:type_name -> academic.credentials.v1.Task
	30, // 17: academic.credentials.v1.LeaseTaskResponse.expires_at:type_name -> google.protobuf.Timestamp
	0,  // 18: academic.credentials.v1.ResolveTaskCredentialResponse.subject:type_name -> academic.credentials.v1.Subject
	37, // 19: academic.credentials.v1.ResolveTaskCredentialResponse.credential:type_name -> academic.provider.v1.Credential
	17, // 20: academic.credentials.v1.CompleteTaskRequest.result:type_name -> academic.credentials.v1.TaskResult
	16, // 21: academic.credentials.v1.CompleteTaskResponse.task:type_name -> academic.credentials.v1.Task
	0,  // 22: academic.credentials.v1.GetEligibilityResponse.subject:type_name -> academic.credentials.v1.Subject
	0,  // 23: academic.credentials.v1.ConfirmBindingResponse.subject:type_name -> academic.credentials.v1.Subject
	2,  // 24: academic.credentials.v1.CredentialsService.CreateBindingIntent:input_type -> academic.credentials.v1.CreateBindingIntentRequest
	4,  // 25: academic.credentials.v1.CredentialsService.GetHostingStatus:input_type -> academic.credentials.v1.GetHostingStatusRequest
	6,  // 26: academic.credentials.v1.CredentialsService.UpdateGrant:input_type -> academic.credentials.v1.UpdateGrantRequest
	8,  // 27: academic.credentials.v1.CredentialsService.RevokeCredential:input_type -> academic.credentials.v1.RevokeCredentialRequest
	10, // 28: academic.credentials.v1.CredentialsService.FenceSubject:input_type -> academic.credentials.v1.FenceSubjectRequest
	12, // 29: academic.credentials.v1.CredentialsService.CreateTask:input_type -> academic.credentials.v1.CreateTaskRequest
	14, // 30: academic.credentials.v1.CredentialsService.GetTask:input_type -> academic.credentials.v1.GetTaskRequest
	18, // 31: academic.credentials.v1.CredentialsService.LeaseTask:input_type -> academic.credentials.v1.LeaseTaskRequest
	20, // 32: academic.credentials.v1.CredentialsService.ResolveTaskCredential:input_type -> academic.credentials.v1.ResolveTaskCredentialRequest
	22, // 33: academic.credentials.v1.CredentialsService.CheckExecutionAdmission:input_type -> academic.credentials.v1.CheckExecutionAdmissionRequest
	24, // 34: academic.credentials.v1.CredentialsService.CompleteTask:input_type -> academic.credentials.v1.CompleteTaskRequest
	26, // 35: academic.credentials.v1.AcademicCredentialAuthorityService.GetEligibility:input_type -> academic.credentials.v1.GetEligibilityRequest
	28, // 36: academic.credentials.v1.AcademicCredentialAuthorityService.ConfirmBinding:input_type -> academic.credentials.v1.ConfirmBindingRequest
	3,  // 37: academic.credentials.v1.CredentialsService.CreateBindingIntent:output_type -> academic.credentials.v1.CreateBindingIntentResponse
	5,  // 38: academic.credentials.v1.CredentialsService.GetHostingStatus:output_type -> academic.credentials.v1.GetHostingStatusResponse
	7,  // 39: academic.credentials.v1.CredentialsService.UpdateGrant:output_type -> academic.credentials.v1.UpdateGrantResponse
	9,  // 40: academic.credentials.v1.CredentialsService.RevokeCredential:output_type -> academic.credentials.v1.RevokeCredentialResponse
	11, // 41: academic.credentials.v1.CredentialsService.FenceSubject:output_type -> academic.credentials.v1.FenceSubjectResponse
	13, // 42: academic.credentials.v1.CredentialsService.CreateTask:output_type -> academic.credentials.v1.CreateTaskResponse
	15, // 43: academic.credentials.v1.CredentialsService.GetTask:output_type -> academic.credentials.v1.GetTaskResponse
	19, // 44: academic.credentials.v1.CredentialsService.LeaseTask:output_type -> academic.credentials.v1.LeaseTaskResponse
	21, // 45: academic.credentials.v1.CredentialsService.ResolveTaskCredential:output_type -> academic.credentials.v1.ResolveTaskCredentialResponse
	23, // 46: academic.credentials.v1.CredentialsService.CheckExecutionAdmission:output_type -> academic.credentials.v1.CheckExecutionAdmissionResponse
	25, // 47: academic.credentials.v1.CredentialsService.CompleteTask:output_type -> academic.credentials.v1.CompleteTaskResponse
	27, // 48: academic.credentials.v1.AcademicCredentialAuthorityService.GetEligibility:output_type -> academic.credentials.v1.GetEligibilityResponse
	29, // 49: academic.credentials.v1.AcademicCredentialAuthorityService.ConfirmBinding:output_type -> academic.credentials.v1.ConfirmBindingResponse
	37, // [37:50] is the sub-list for method output_type
	24, // [24:37] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_academic_credentials_v1_credentials_proto_init() }
func file_academic_credentials_v1_credentials_proto_init() {
	if File_academic_credentials_v1_credentials_proto != nil {
		return
	}
	file_academic_credentials_v1_credentials_proto_msgTypes[17].OneofWrappers = []any{
		(*TaskResult_Courses)(nil),
		(*TaskResult_Exams)(nil),
		(*TaskResult_Grades)(nil),
		(*TaskResult_CourseSelections)(nil),
		(*TaskResult_CourseSelectionSchedule)(nil),
		(*TaskResult_CourseAdditionResults)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_academic_credentials_v1_credentials_proto_rawDesc), len(file_academic_credentials_v1_credentials_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_academic_credentials_v1_credentials_proto_goTypes,
		DependencyIndexes: file_academic_credentials_v1_credentials_proto_depIdxs,
		MessageInfos:      file_academic_credentials_v1_credentials_proto_msgTypes,
	}.Build()
	File_academic_credentials_v1_credentials_proto = out.File
	file_academic_credentials_v1_credentials_proto_goTypes = nil
	file_academic_credentials_v1_credentials_proto_depIdxs = nil
}
