// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: academic/provider/v1/provider.proto

package academicproviderv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AcademicProviderService_VerifyCredential_FullMethodName           = "/academic.provider.v1.AcademicProviderService/VerifyCredential"
	AcademicProviderService_VerifyManagedCredential_FullMethodName    = "/academic.provider.v1.AcademicProviderService/VerifyManagedCredential"
	AcademicProviderService_ListCourses_FullMethodName                = "/academic.provider.v1.AcademicProviderService/ListCourses"
	AcademicProviderService_GetCourseSelectionSchedule_FullMethodName = "/academic.provider.v1.AcademicProviderService/GetCourseSelectionSchedule"
	AcademicProviderService_ListGrades_FullMethodName                 = "/academic.provider.v1.AcademicProviderService/ListGrades"
	AcademicProviderService_ListExams_FullMethodName                  = "/academic.provider.v1.AcademicProviderService/ListExams"
	AcademicProviderService_ListCourseSelections_FullMethodName       = "/academic.provider.v1.AcademicProviderService/ListCourseSelections"
	AcademicProviderService_ListCourseAdditionResults_FullMethodName  = "/academic.provider.v1.AcademicProviderService/ListCourseAdditionResults"
	AcademicProviderService_ListCourseCatalogPage_FullMethodName      = "/academic.provider.v1.AcademicProviderService/ListCourseCatalogPage"
	AcademicProviderService_DeleteStudentSessions_FullMethodName      = "/academic.provider.v1.AcademicProviderService/DeleteStudentSessions"
)

// AcademicProviderServiceClient is the client API for AcademicProviderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AcademicProviderServiceClient interface {
	VerifyCredential(ctx context.Context, in *VerifyCredentialRequest, opts ...grpc.CallOption) (*VerifyCredentialResponse, error)
	// VerifyManagedCredential 仅验证托管凭据，不建立长期会话。
	VerifyManagedCredential(ctx context.Context, in *VerifyManagedCredentialRequest, opts ...grpc.CallOption) (*VerifyManagedCredentialResponse, error)
	ListCourses(ctx context.Context, in *ListCoursesRequest, opts ...grpc.CallOption) (*ListCoursesResponse, error)
	GetCourseSelectionSchedule(ctx context.Context, in *GetCourseSelectionScheduleRequest, opts ...grpc.CallOption) (*GetCourseSelectionScheduleResponse, error)
	ListGrades(ctx context.Context, in *ListGradesRequest, opts ...grpc.CallOption) (*ListGradesResponse, error)
	ListExams(ctx context.Context, in *ListExamsRequest, opts ...grpc.CallOption) (*ListExamsResponse, error)
	ListCourseSelections(ctx context.Context, in *ListCourseSelectionsRequest, opts ...grpc.CallOption) (*ListCourseSelectionsResponse, error)
	ListCourseAdditionResults(ctx context.Context, in *ListCourseAdditionResultsRequest, opts ...grpc.CallOption) (*ListCourseAdditionResultsResponse, error)
	ListCourseCatalogPage(ctx context.Context, in *ListCourseCatalogPageRequest, opts ...grpc.CallOption) (*ListCourseCatalogPageResponse, error)
	DeleteStudentSessions(ctx context.Context, in *DeleteStudentSessionsRequest, opts ...grpc.CallOption) (*DeleteStudentSessionsResponse, error)
}

type academicProviderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAcademicProviderServiceClient(cc grpc.ClientConnInterface) AcademicProviderServiceClient {
	return &academicProviderServiceClient{cc}
}

func (c *academicProviderServiceClient) VerifyCredential(ctx context.Context, in *VerifyCredentialRequest, opts ...grpc.CallOption) (*VerifyCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyCredentialResponse)
	err := c.cc.Invoke(ctx, AcademicProviderService_VerifyCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *academicProviderServiceClient) VerifyManagedCredential(ctx context.Context, in *VerifyManagedCredentialRequest, opts ...grpc.CallOption) (*VerifyManagedCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyManagedCredentialResponse)
	err := c.cc.Invoke(ctx, AcademicProviderService_VerifyManagedCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *academicProviderServiceClient) ListCourses(ctx context.Context, in *ListCoursesRequest, opts ...grpc.CallOption) (*ListCoursesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCoursesResponse)
	err := c.cc.Invoke(ctx, AcademicProviderService_ListCourses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *academicProviderServiceClient) GetCourseSelectionSchedule(ctx context.Context, in *GetCourseSelectionScheduleRequest, opts ...grpc.CallOption) (*GetCourseSelectionScheduleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCourseSelectionScheduleResponse)
	err := c.cc.Invoke(ctx, AcademicProviderService_GetCourseSelectionSchedule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *academicProviderServiceClient) ListGrades(ctx context.Context, in *ListGradesRequest, opts ...grpc.CallOption) (*ListGradesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListGradesResponse)
	err := c.cc.Invoke(ctx, AcademicProviderService_ListGrades_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *academicProviderServiceClient) ListExams(ctx context.Context, in *ListExamsRequest, opts ...grpc.CallOption) (*ListExamsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListExamsResponse)
	err := c.cc.Invoke(ctx, AcademicProviderService_ListExams_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *academicProviderServiceClient) ListCourseSelections(ctx context.Context, in *ListCourseSelectionsRequest, opts ...grpc.CallOption) (*ListCourseSelectionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCourseSelectionsResponse)
	err := c.cc.Invoke(ctx, AcademicProviderService_ListCourseSelections_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *academicProviderServiceClient) ListCourseAdditionResults(ctx context.Context, in *ListCourseAdditionResultsRequest, opts ...grpc.CallOption) (*ListCourseAdditionResultsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCourseAdditionResultsResponse)
	err := c.cc.Invoke(ctx, AcademicProviderService_ListCourseAdditionResults_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *academicProviderServiceClient) ListCourseCatalogPage(ctx context.Context, in *ListCourseCatalogPageRequest, opts ...grpc.CallOption) (*ListCourseCatalogPageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCourseCatalogPageResponse)
	err := c.cc.Invoke(ctx, AcademicProviderService_ListCourseCatalogPage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *academicProviderServiceClient) DeleteStudentSessions(ctx context.Context, in *DeleteStudentSessionsRequest, opts ...grpc.CallOption) (*DeleteStudentSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteStudentSessionsResponse)
	err := c.cc.Invoke(ctx, AcademicProviderService_DeleteStudentSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AcademicProviderServiceServer is the server API for AcademicProviderService service.
// All implementations must embed UnimplementedAcademicProviderServiceServer
// for forward compatibility.
type AcademicProviderServiceServer interface {
	VerifyCredential(context.Context, *VerifyCredentialRequest) (*VerifyCredentialResponse, error)
	// VerifyManagedCredential 仅验证托管凭据，不建立长期会话。
	VerifyManagedCredential(context.Context, *VerifyManagedCredentialRequest) (*VerifyManagedCredentialResponse, error)
	ListCourses(context.Context, *ListCoursesRequest) (*ListCoursesResponse, error)
	GetCourseSelectionSchedule(context.Context, *GetCourseSelectionScheduleRequest) (*GetCourseSelectionScheduleResponse, error)
	ListGrades(context.Context, *ListGradesRequest) (*ListGradesResponse, error)
	ListExams(context.Context, *ListExamsRequest) (*ListExamsResponse, error)
	ListCourseSelections(context.Context, *ListCourseSelectionsRequest) (*ListCourseSelectionsResponse, error)
	ListCourseAdditionResults(context.Context, *ListCourseAdditionResultsRequest) (*ListCourseAdditionResultsResponse, error)
	ListCourseCatalogPage(context.Context, *ListCourseCatalogPageRequest) (*ListCourseCatalogPageResponse, error)
	DeleteStudentSessions(context.Context, *DeleteStudentSessionsRequest) (*DeleteStudentSessionsResponse, error)
	mustEmbedUnimplementedAcademicProviderServiceServer()
}

// UnimplementedAcademicProviderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAcademicProviderServiceServer struct{}

func (UnimplementedAcademicProviderServiceServer) VerifyCredential(context.Context, *VerifyCredentialRequest) (*VerifyCredentialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyCredential not implemented")
}
func (UnimplementedAcademicProviderServiceServer) VerifyManagedCredential(context.Context, *VerifyManagedCredentialRequest) (*VerifyManagedCredentialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyManagedCredential not implemented")
}
func (UnimplementedAcademicProviderServiceServer) ListCourses(context.Context, *ListCoursesRequest) (*ListCoursesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCourses not implemented")
}
func (UnimplementedAcademicProviderServiceServer) GetCourseSelectionSchedule(context.Context, *GetCourseSelectionScheduleRequest) (*GetCourseSelectionScheduleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCourseSelectionSchedule not implemented")
}
func (UnimplementedAcademicProviderServiceServer) ListGrades(context.Context, *ListGradesRequest) (*ListGradesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListGrades not implemented")
}
func (UnimplementedAcademicProviderServiceServer) ListExams(context.Context, *ListExamsRequest) (*ListExamsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListExams not implemented")
}
func (UnimplementedAcademicProviderServiceServer) ListCourseSelections(context.Context, *ListCourseSelectionsRequest) (*ListCourseSelectionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCourseSelections not implemented")
}
func (UnimplementedAcademicProviderServiceServer) ListCourseAdditionResults(context.Context, *ListCourseAdditionResultsRequest) (*ListCourseAdditionResultsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCourseAdditionResults not implemented")
}
func (UnimplementedAcademicProviderServiceServer) ListCourseCatalogPage(context.Context, *ListCourseCatalogPageRequest) (*ListCourseCatalogPageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCourseCatalogPage not implemented")
}
func (UnimplementedAcademicProviderServiceServer) DeleteStudentSessions(context.Context, *DeleteStudentSessionsRequest) (*DeleteStudentSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteStudentSessions not implemented")
}
func (UnimplementedAcademicProviderServiceServer) mustEmbedUnimplementedAcademicProviderServiceServer() {
}
func (UnimplementedAcademicProviderServiceServer) testEmbeddedByValue() {}

// UnsafeAcademicProviderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AcademicProviderServiceServer will
// result in compilation errors.
type UnsafeAcademicProviderServiceServer interface {
	mustEmbedUnimplementedAcademicProviderServiceServer()
}

func RegisterAcademicProviderServiceServer(s grpc.ServiceRegistrar, srv AcademicProviderServiceServer) {
	// If the following call panics, it indicates UnimplementedAcademicProviderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AcademicProviderService_ServiceDesc, srv)
}

func _AcademicProviderService_VerifyCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcademicProviderServiceServer).VerifyCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AcademicProviderService_VerifyCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcademicProviderServiceServer).VerifyCredential(ctx, req.(*VerifyCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AcademicProviderService_VerifyManagedCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyManagedCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcademicProviderServiceServer).VerifyManagedCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AcademicProviderService_VerifyManagedCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcademicProviderServiceServer).VerifyManagedCredential(ctx, req.(*VerifyManagedCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AcademicProviderService_ListCourses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCoursesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcademicProviderServiceServer).ListCourses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AcademicProviderService_ListCourses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcademicProviderServiceServer).ListCourses(ctx, req.(*ListCoursesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AcademicProviderService_GetCourseSelectionSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCourseSelectionScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcademicProviderServiceServer).GetCourseSelectionSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AcademicProviderService_GetCourseSelectionSchedule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcademicProviderServiceServer).GetCourseSelectionSchedule(ctx, req.(*GetCourseSelectionScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AcademicProviderService_ListGrades_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGradesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcademicProviderServiceServer).ListGrades(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AcademicProviderService_ListGrades_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcademicProviderServiceServer).ListGrades(ctx, req.(*ListGradesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AcademicProviderService_ListExams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListExamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcademicProviderServiceServer).ListExams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AcademicProviderService_ListExams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcademicProviderServiceServer).ListExams(ctx, req.(*ListExamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AcademicProviderService_ListCourseSelections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCourseSelectionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcademicProviderServiceServer).ListCourseSelections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AcademicProviderService_ListCourseSelections_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcademicProviderServiceServer).ListCourseSelections(ctx, req.(*ListCourseSelectionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AcademicProviderService_ListCourseAdditionResults_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCourseAdditionResultsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcademicProviderServiceServer).ListCourseAdditionResults(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AcademicProviderService_ListCourseAdditionResults_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcademicProviderServiceServer).ListCourseAdditionResults(ctx, req.(*ListCourseAdditionResultsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AcademicProviderService_ListCourseCatalogPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCourseCatalogPageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcademicProviderServiceServer).ListCourseCatalogPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AcademicProviderService_ListCourseCatalogPage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcademicProviderServiceServer).ListCourseCatalogPage(ctx, req.(*ListCourseCatalogPageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AcademicProviderService_DeleteStudentSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteStudentSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcademicProviderServiceServer).DeleteStudentSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AcademicProviderService_DeleteStudentSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcademicProviderServiceServer).DeleteStudentSessions(ctx, req.(*DeleteStudentSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AcademicProviderService_ServiceDesc is the grpc.ServiceDesc for AcademicProviderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AcademicProviderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "academic.provider.v1.AcademicProviderService",
	HandlerType: (*AcademicProviderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VerifyCredential",
			Handler:    _AcademicProviderService_VerifyCredential_Handler,
		},
		{
			MethodName: "VerifyManagedCredential",
			Handler:    _AcademicProviderService_VerifyManagedCredential_Handler,
		},
		{
			MethodName: "ListCourses",
			Handler:    _AcademicProviderService_ListCourses_Handler,
		},
		{
			MethodName: "GetCourseSelectionSchedule",
			Handler:    _AcademicProviderService_GetCourseSelectionSchedule_Handler,
		},
		{
			MethodName: "ListGrades",
			Handler:    _AcademicProviderService_ListGrades_Handler,
		},
		{
			MethodName: "ListExams",
			Handler:    _AcademicProviderService_ListExams_Handler,
		},
		{
			MethodName: "ListCourseSelections",
			Handler:    _AcademicProviderService_ListCourseSelections_Handler,
		},
		{
			MethodName: "ListCourseAdditionResults",
			Handler:    _AcademicProviderService_ListCourseAdditionResults_Handler,
		},
		{
			MethodName: "ListCourseCatalogPage",
			Handler:    _AcademicProviderService_ListCourseCatalogPage_Handler,
		},
		{
			MethodName: "DeleteStudentSessions",
			Handler:    _AcademicProviderService_DeleteStudentSessions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "academic/provider/v1/provider.proto",
}
