// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: academic/provider/v1/provider.proto

package academicproviderv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Credential struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentNo     string                 `protobuf:"bytes,1,opt,name=student_no,json=studentNo,proto3" json:"student_no,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Credential) Reset() {
	*x = Credential{}
	mi := &file_academic_provider_v1_provider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Credential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Credential) ProtoMessage() {}

func (x *Credential) ProtoReflect() protoreflect.Message {
	mi := &file_academic_provider_v1_provider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Credential.ProtoReflect.Descriptor instead.
func (*Credential) Descriptor() ([]byte, []int) {
	return file_academic_provider_v1_provider_proto_rawDescGZIP(), []int{0}
}

func (x *Credential) GetStudentNo() string {
	if x != nil {
		return x.StudentNo
	}
	return ""
}

func (x *Credential) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type StudentReference struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StudentNo      string                 `protobuf:"bytes,2,opt,name=student_no,json=studentNo,proto3" json:"student_no,omitempty"`
	Provider       string                 `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	EducationLevel string                 `protobuf:"bytes,4,opt,name=education_level,json=educationLevel,proto3" json:"education_level,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StudentReference) Reset() {
	*x = StudentReference{}
	mi := &file_academic_provider_v1_provider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentReference) ProtoMessage() {}

func (x *StudentReference) ProtoReflect() protoreflect.Message {
	mi := &file_academic_provider_v1_provider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentReference.ProtoReflect.Descriptor instead.
func (*StudentReference) Descriptor() ([]byte, []int) {
	return file_academic_provider_v1_provider_proto_rawDescGZIP(), []int{1}
}

func (x *StudentReference) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *StudentReference) GetStudentNo() string {
	if x != nil {
		return x.StudentNo
	}
	return ""
}

func (x *StudentReference) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *StudentReference) GetEducationLevel() string {
	if x != nil {
		return x.EducationLevel
	}
	return ""
}

type VerifyCredentialRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Credential     *Credential            `protobuf:"bytes,1,opt,name=credential,proto3" json:"credential,omitempty"`
	EducationLevel string                 `protobuf:"bytes,2,opt,name=education_level,json=educationLevel,proto3" json:"education_level,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VerifyCredentialRequest) Reset() {
	*x = VerifyCredentialRequest{}
	mi := &file_academic_provider_v1_provider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyCredentialRequest) ProtoMessage() {}

func (x *VerifyCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_academic_provider_v1_provider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyCredentialRequest.ProtoReflect.Descriptor instead.
func (*VerifyCredentialRequest) Descriptor() ([]byte, []int) {
	return file_academic_provider_v1_provider_proto_rawDescGZIP(), []int{2}
}

func (x *VerifyCredentialRequest) GetCredential() *Credential {
	if x != nil {
		return x.Credential
	}
	return nil
}

func (x *VerifyCredentialRequest) GetEducationLevel() string {
	if x != nil {
		return x.EducationLevel
	}
	return ""
}

type VerifyCredentialResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RealName       string                 `protobuf:"bytes,1,opt,name=real_name,json=realName,proto3" json:"real_name,omitempty"`
	Provider       string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	EducationLevel string                 `protobuf:"bytes,3,opt,name=education_level,json=educationLevel,proto3" json:"education_level,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VerifyCredentialResponse) Reset() {
	*x = VerifyCredentialResponse{}
	mi := &file_academic_provider_v1_provider_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyCredentialResponse) ProtoMessage() {}

func (x *VerifyCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_academic_provider_v1_provider_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyCredentialResponse.ProtoReflect.Descriptor instead.
func (*VerifyCredentialResponse) Descriptor() ([]byte, []int) {
	return file_academic_provider_v1_provider_proto_rawDescGZIP(), []int{3}
}

func (x *VerifyCredentialResponse) GetRealName() string {
	if x != nil {
		return x.RealName
	}
	return ""
}

func (x *VerifyCredentialResponse) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *VerifyCredentialResponse) GetEducationLevel() string {
	if x != nil {
		return x.EducationLevel
	}
	return ""
}

type VerifyManagedCredentialRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Credential     *Credential            `protobuf:"bytes,1,opt,name=credential,proto3" json:"credential,omitempty"`
	EducationLevel string                 `protobuf:"bytes,2,opt,name=education_level,json=educationLevel,proto3" json:"education_level,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VerifyManagedCredentialRequest) Reset() {
	*x = VerifyManagedCredentialRequest{}
	mi := &file_academic_provider_v1_provider_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyManagedCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyManagedCredentialRequest) ProtoMessage() {}

func (x *VerifyManagedCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_academic_provider_v1_provider_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyManagedCredentialRequest.ProtoReflect.Descriptor instead.
func (*VerifyManagedCredentialRequest) Descriptor() ([]byte, []int) {
	return file_academic_provider_v1_provider_proto_rawDescGZIP(), []int{4}
}

func (x *VerifyManagedCredentialRequest) GetCredential() *Credential {
	if x != nil {
		return x.Credential
	}
	return nil
}

func (x *VerifyManagedCredentialRequest) GetEducationLevel() string {
	if x != nil {
		return x.EducationLevel
	}
	return ""
}

type VerifyManagedCredentialResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RealName       string                 `protobuf:"bytes,1,opt,name=real_name,json=realName,proto3" json:"real_name,omitempty"`
	Provider       string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	EducationLevel string                 `protobuf:"bytes,3,opt,name=education_level,json=educationLevel,proto3" json:"education_level,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VerifyManagedCredentialResponse) Reset() {
	*x = VerifyManagedCredentialResponse{}
	mi := &file_academic_provider_v1_provider_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyManagedCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyManagedCredentialResponse) ProtoMessage() {}

func (x *VerifyManagedCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_academic_provider_v1_provider_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyManagedCredentialResponse.ProtoReflect.Descriptor instead.
func (*VerifyManagedCredentialResponse) Descriptor() ([]byte, []int) {
	return file_academic_provider_v1_provider_proto_rawDescGZIP(), []int{5}
}

func (x *VerifyManagedCredentialResponse) GetRealName() string {
	if x != nil {
		return x.RealName
	}
	return ""
}

func (x *VerifyManagedCredentialResponse) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *VerifyManagedCredentialResponse) GetEducationLevel() string {
	if x != nil {
		return x.EducationLevel
	}
	return ""
}

type ListCoursesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Student       *StudentReference      `protobuf:"bytes,1,opt,name=student,proto3" json:"student,omitempty"`
	Credential    *Credential            `protobuf:"bytes,2,opt,name=credential,proto3" json:"credential,omitempty"`
	PeriodId      string                 `protobuf:"bytes,3,opt,name=period_id,json=periodId,proto3" json:"period_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCoursesRequest) Reset() {
	*x = ListCoursesRequest{}
	mi := &file_academic_provider_v1_provider_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCoursesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCoursesRequest) ProtoMessage() {}

func (x *ListCoursesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_academic_provider_v1_provider_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCoursesRequest.ProtoReflect.Descriptor instead.
func (*ListCoursesRequest) Descriptor() ([]byte, []int) {
	return file_academic_provider_v1_provider_proto_rawDescGZIP(), []int{6}
}

func (x *ListCoursesRequest) GetStudent() *StudentReference {
	if x != nil {
		return x.Student
	}
	return nil
}

func (x *ListCoursesRequest) GetCredential() *Credential {
	if x != nil {
		return x.Credential
	}
	return nil
}

func (x *ListCoursesRequest) GetPeriodId() string {
	if x != nil {
		return x.PeriodId
	}
	return ""
}

type ListCoursesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Courses       []*Course              `protobuf:"bytes,1,rep,name=courses,proto3" json:"courses,omitempty"`
	Cache         *CacheMetadata         `protobuf:"bytes,2,opt,name=cache,proto3" json:"cache,omitempty"`
	ScheduleNote  string                 `protobuf:"bytes,3,opt,name=schedule_note,json=scheduleNote,proto3" json:"schedule_note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCoursesResponse) Reset() {
	*x = ListCoursesResponse{}
	mi := &file_academic_provider_v1_provider_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCoursesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCoursesResponse) ProtoMessage() {}

func (x *ListCoursesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_academic_provider_v1_provider_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCoursesResponse.ProtoReflect.Descriptor instead.
func (*ListCoursesResponse) Descriptor() ([]byte, []int) {
	return file_academic_provider_v1_provider_proto_rawDescGZIP(), []int{7}
}

func (x *ListCoursesResponse) GetCourses() []*Course {
	if x != nil {
		return x.Courses
	}
	return nil
}

func (x *ListCoursesResponse) GetCache() *CacheMetadata {
	if x != nil {
		return x.Cache
	}
	return nil
}

func (x *ListCoursesResponse) GetScheduleNote() string {
	if x != nil {
		return x.ScheduleNote
	}
	return ""
}

// CacheMetadata is present only when the response was served from the
// provider's encrypted Redis result cache.
type CacheMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	CachedAt      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=cached_at,json=cachedAt,proto3" json:"cached_at,omitempty"`
	FreshUntil    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=fresh_until,json=freshUntil,proto3" json:"fresh_until,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheMetadata) Reset() {
	*x = CacheMetadata{}
	mi := &file_academic_provider_v1_provider_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheMetadata) ProtoMessage() {}

func (x *CacheMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_academic_provider_v1_provider_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheMetadata.ProtoReflect.Descriptor instead.
func (*CacheMetadata) Descriptor() ([]byte, []int) {
	return file_academic_provider_v1_provider_proto_rawDescGZIP(), []int{8}
}

func (x *CacheMetadata) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *CacheMetadata) GetCachedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CachedAt
	}
	return nil
}

func (x *CacheMetadata) GetFreshUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.FreshUntil
	}
	return nil
}

type Course struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Id           string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PeriodId     string                 `protobuf:"bytes,2,opt,name=period_id,json=periodId,proto3" json:"period_id,omitempty"`
	CourseCode   string                 `protobuf:"bytes,3,opt,name=course_code,json=courseCode,proto3" json:"course_code,omitempty"`
	Name         string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Teacher      string                 `protobuf:"bytes,5,opt,name=teacher,proto3" json:"teacher,omitempty"`
	Campus       string                 `protobuf:"bytes,6,opt,name=campus,proto3" json:"campus,omitempty"`
	Location     string                 `protobuf:"bytes,7,opt,name=location,proto3" json:"location,omitempty"`
	Weekday      int32                  `protobuf:"varint,8,opt,name=weekday,proto3" json:"weekday,omitempty"`
	StartSection int32                  `protobuf:"varint,9,opt,name=start_section,json=startSection,proto3" json:"start_section,omitempty"`
	EndSection   int32                  `protobuf:"varint,10,opt,name=end_section,json=endSection,proto3" json:"end_section,omitempty"`
	Weeks        []int32                `protobuf:"varint,11,rep,packed,name=weeks,proto3" json:"weeks,omitempty"`
	Note         string                 `protobuf:"bytes,12,opt,name=note,proto3" json:"note,omitempty"`
	// ClassNum is the school course-selection number. It is distinct from the
	// course code and is used by clients to reconcile simulated selections.
	ClassNum      string `protobuf:"bytes,13,opt,name=class_num,json=classNum,proto3" json:"class_num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Course) Reset() {
	*x = Course{}
	mi := &file_academic_provider_v1_provider_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Course) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Course) ProtoMessage() {}

func (x *Course) ProtoReflect() protoreflect.Message {
	mi := &file_academic_provider_v1_provider_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Course.ProtoReflect.Descriptor instead.
func (*Course) Descriptor() ([]byte, []int) {
	return file_academic_provider_v1_provider_proto_rawDescGZIP(), []int{9}
}

func (x *Course) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Course) GetPeriodId() string {
	if x != nil {
		return x.PeriodId
	}
	return ""
}

func (x *Course) GetCourseCode() string {
	if x != nil {
		return x.CourseCode
	}
	return ""
}

func (x *Course) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Course) GetTeacher() string {
	if x != nil {
		return x.Teacher
	}
	return ""
}

func (x *Course) GetCampus() string {
	if x != nil {
		return x.Campus
	}
	return ""
}

func (x *Course) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Course) GetWeekday() int32 {
	if x != nil {
		return x.Weekday
	}
	return 0
}

func (x *Course) GetStartSection() int32 {
	if x != nil {
		return x.StartSection
	}
	return 0
}

func (x *Course) GetEndSection() int32 {
	if x != nil {
		return x.EndSection
	}
	return 0
}

func (x *Course) GetWeeks() []int32 {
	if x != nil {
		return x.Weeks
	}
	return nil
}

func (x *Course) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *Course) GetClassNum() string {
	if x != nil {
		return x.ClassNum
	}
	return ""
}

type GetCourseSelectionScheduleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Student       *StudentReference      `protobuf:"bytes,1,opt,name=student,proto3" json:"student,omitempty"`
	Credential    *Credential            `protobuf:"bytes,2,opt,name=credential,proto3" json:"credential,omitempty"`
	PeriodId      string                 `protobuf:"bytes,3,opt,name=period_id,json=periodId,proto3" json:"period_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourseSelectionScheduleRequest) Reset() {
	*x = GetCourseSelectionScheduleRequest{}
	mi := &file_academic_provider_v1_provider_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourseSelectionScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseSelectionScheduleRequest) ProtoMessage() {}

func (x *GetCourseSelectionScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_academic_provider_v1_provider_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseSelectionScheduleRequest.ProtoReflect.Descriptor instead.
func (*GetCourseSelectionScheduleRequest) Descriptor() ([]byte, []int) {
	return file_academic_provider_v1_provider_proto_rawDescGZIP(), []int{10}
}

func (x *GetCourseSelectionScheduleRequest) GetStudent() *StudentReference {
	if x != nil {
		return x.Student
	}
	return nil
}

func (x *GetCourseSelectionScheduleRequest) GetCredential() *Credential {
	if x != nil {
		return x.Credential
	}
	return nil
}

func (x *GetCourseSelectionScheduleRequest) GetPeriodId() string {
	if x != nil {
		return x.PeriodId
	}
	return ""
}

type GetCourseSelectionScheduleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Courses       []*Course              `protobuf:"bytes,1,rep,name=courses,proto3" json:"courses,omitempty"`
	Cache         *CacheMetadata         `protobuf:"bytes,2,opt,name=cache,proto3" json:"cache,omitempty"`
	ScheduleNote  string                 `protobuf:"bytes,3,opt,name=schedule_note,json=scheduleNote,proto3" json:"schedule_note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourseSelectionScheduleResponse) Reset() {
	*x = GetCourseSelectionScheduleResponse{}
	mi := &file_academic_provider_v1_provider_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourseSelectionScheduleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseSelectionScheduleResponse) ProtoMessage() {}

func (x *GetCourseSelectionScheduleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_academic_provider_v1_provider_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseSelectionScheduleResponse.ProtoReflect.Descriptor instead.
func (*GetCourseSelectionScheduleResponse) Descriptor() ([]byte, []int) {
	return file_academic_provider_v1_provider_proto_rawDescGZIP(), []int{11}
}

func (x *GetCourseSelectionScheduleResponse) GetCourses() []*Course {
	if x != nil {
		return x.Courses
	}
	return nil
}

func (x *GetCourseSelectionScheduleResponse) GetCache() *CacheMetadata {
	if x != nil {
		return x.Cache
	}
	return nil
}

func (x *GetCourseSelectionScheduleResponse) GetScheduleNote() string {
	if x != nil {
		return x.ScheduleNote
	}
	return ""
}

type ListGradesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Student       *StudentReference      `protobuf:"bytes,1,opt,name=student,proto3" json:"student,omitempty"`
	Credential    *Credential            `protobuf:"bytes,2,opt,name=credential,proto3" json:"credential,omitempty"`
	PeriodId      string                 `protobuf:"bytes,3,opt,name=period_id,json=periodId,proto3" json:"period_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGradesRequest) Reset() {
	*x = ListGradesRequest{}
	mi := &file_academic_provider_v1_provider_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGradesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGradesRequest) ProtoMessage() {}

func (x *ListGradesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_academic_provider_v1_provider_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGradesRequest.ProtoReflect.Descriptor instead.
func (*ListGradesRequest) Descriptor() ([]byte, []int) {
	return file_academic_provider_v1_provider_proto_rawDescGZIP(), []int{12}
}

func (x *ListGradesRequest) GetStudent() *StudentReference {
	if x != nil {
		return x.Student
	}
	return nil
}

func (x *ListGradesRequest) GetCredential() *Credential {
	if x != nil {
		return x.Credential
	}
	return nil
}

func (x *ListGradesRequest) GetPeriodId() string {
	if x != nil {
		return x.PeriodId
	}
	return ""
}

type ListGradesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Grades        []*Grade               `protobuf:"bytes,1,rep,name=grades,proto3" json:"grades,omitempty"`
	Cache         *CacheMetadata         `protobuf:"bytes,2,opt,name=cache,proto3" json:"cache,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGradesResponse) Reset() {
	*x = ListGradesResponse{}
	mi := &file_academic_provider_v1_provider_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGradesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGradesResponse) ProtoMessage() {}

func (x *ListGradesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_academic_provider_v1_provider_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGradesResponse.ProtoReflect.Descriptor instead.
func (*ListGradesResponse) Descriptor() ([]byte, []int) {
	return file_academic_provider_v1_provider_proto_rawDescGZIP(), []int{13}
}

func (x *ListGradesResponse) GetGrades() []*Grade {
	if x != nil {
		return x.Grades
	}
	return nil
}

func (x *ListGradesResponse) GetCache() *CacheMetadata {
	if x != nil {
		return x.Cache
	}
	return nil
}

type Grade struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PeriodId      string                 `protobuf:"bytes,2,opt,name=period_id,json=periodId,proto3" json:"period_id,omitempty"`
	CourseCode    string                 `protobuf:"bytes,3,opt,name=course_code,json=courseCode,proto3" json:"course_code,omitempty"`
	CourseName    string                 `protobuf:"bytes,4,opt,name=course_name,json=courseName,proto3" json:"course_name,omitempty"`
	CourseType    string                 `protobuf:"bytes,5,opt,name=course_type,json=courseType,proto3" json:"course_type,omitempty"`
	Credit        float64                `protobuf:"fixed64,6,opt,name=credit,proto3" json:"credit,omitempty"`
	GradeType     string                 `protobuf:"bytes,7,opt,name=grade_type,json=gradeType,proto3" json:"grade_type,omitempty"`
	Score         *float64               `protobuf:"fixed64,8,opt,name=score,proto3,oneof" json:"score,omitempty"`
	GradeLevel    *string                `protobuf:"bytes,9,opt,name=grade_level,json=gradeLevel,proto3,oneof" json:"grade_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Grade) Reset() {
	*x = Grade{}
	mi := &file_academic_provider_v1_provider_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Grade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Grade) ProtoMessage() {}

func (x *Grade) ProtoReflect() protoreflect.Message {
	mi := &file_academic_provider_v1_provider_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Grade.ProtoReflect.Descriptor instead.
func (*Grade) Descriptor() ([]byte, []int) {
	return file_academic_provider_v1_provider_proto_rawDescGZIP(), []int{14}
}

func (x *Grade) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Grade) GetPeriodId() string {
	if x != nil {
		return x.PeriodId
	}
	return ""
}

func (x *Grade) GetCourseCode() string {
	if x != nil {
		return x.CourseCode
	}
	return ""
}

func (x *Grade) GetCourseName() string {
	if x != nil {
		return x.CourseName
	}
	return ""
}

func (x *Grade) GetCourseType() string {
	if x != nil {
		return x.CourseType
	}
	return ""
}

func (x *Grade) GetCredit() float64 {
	if x != nil {
		return x.Credit
	}
	return 0
}

func (x *Grade) GetGradeType() string {
	if x != nil {
		return x.GradeType
	}
	return ""
}

func (x *Grade) GetScore() float64 {
	if x != nil && x.Score != nil {
		return *x.Score
	}
	return 0
}

func (x *Grade) GetGradeLevel() string {
	if x != nil && x.GradeLevel != nil {
		return *x.GradeLevel
	}
	return ""
}

type ListExamsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Student       *StudentReference      `protobuf:"bytes,1,opt,name=student,proto3" json:"student,omitempty"`
	Credential    *Credential            `protobuf:"bytes,2,opt,name=credential,proto3" json:"credential,omitempty"`
	PeriodId      string                 `protobuf:"bytes,3,opt,name=period_id,json=periodId,proto3" json:"period_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExamsRequest) Reset() {
	*x = ListExamsRequest{}
	mi := &file_academic_provider_v1_provider_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExamsRequest) ProtoMessage() {}

func (x *ListExamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_academic_provider_v1_provider_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExamsRequest.ProtoReflect.Descriptor instead.
func (*ListExamsRequest) Descriptor() ([]byte, []int) {
	return file_academic_provider_v1_provider_proto_rawDescGZIP(), []int{15}
}

func (x *ListExamsRequest) GetStudent() *StudentReference {
	if x != nil {
		return x.Student
	}
	return nil
}

func (x *ListExamsRequest) GetCredential() *Credential {
	if x != nil {
		return x.Credential
	}
	return nil
}

func (x *ListExamsRequest) GetPeriodId() string {
	if x != nil {
		return x.PeriodId
	}
	return ""
}

type ListExamsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exams         []*Exam                `protobuf:"bytes,1,rep,name=exams,proto3" json:"exams,omitempty"`
	Cache         *CacheMetadata         `protobuf:"bytes,2,opt,name=cache,proto3" json:"cache,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExamsResponse) Reset() {
	*x = ListExamsResponse{}
	mi := &file_academic_provider_v1_provider_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExamsResponse) ProtoMessage() {}

func (x *ListExamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_academic_provider_v1_provider_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExamsResponse.ProtoReflect.Descriptor instead.
func (*ListExamsResponse) Descriptor() ([]byte, []int) {
	return file_academic_provider_v1_provider_proto_rawDescGZIP(), []int{16}
}

func (x *ListExamsResponse) GetExams() []*Exam {
	if x != nil {
		return x.Exams
	}
	return nil
}

func (x *ListExamsResponse) GetCache() *CacheMetadata {
	if x != nil {
		return x.Cache
	}
	return nil
}

type Exam struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PeriodId      string                 `protobuf:"bytes,2,opt,name=period_id,json=periodId,proto3" json:"period_id,omitempty"`
	CourseCode    string                 `protobuf:"bytes,3,opt,name=course_code,json=courseCode,proto3" json:"course_code,omitempty"`
	CourseName    string                 `protobuf:"bytes,4,opt,name=course_name,json=courseName,proto3" json:"course_name,omitempty"`
	StartAt       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	EndAt         *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
	Campus        string                 `protobuf:"bytes,7,opt,name=campus,proto3" json:"campus,omitempty"`
	Location      string                 `protobuf:"bytes,8,opt,name=location,proto3" json:"location,omitempty"`
	Seat          string                 `protobuf:"bytes,9,opt,name=seat,proto3" json:"seat,omitempty"`
	Phase         string                 `protobuf:"bytes,10,opt,name=phase,proto3" json:"phase,omitempty"`
	Method        string                 `protobuf:"bytes,11,opt,name=method,proto3" json:"method,omitempty"`
	Materials     string                 `protobuf:"bytes,12,opt,name=materials,proto3" json:"materials,omitempty"`
	Notice        string                 `protobuf:"bytes,13,opt,name=notice,proto3" json:"notice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Exam) Reset() {
	*x = Exam{}
	mi := &file_academic_provider_v1_provider_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Exam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Exam) ProtoMessage() {}

func (x *Exam) ProtoReflect() protoreflect.Message {
	mi := &file_academic_provider_v1_provider_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Exam.ProtoReflect.Descriptor instead.
func (*Exam) Descriptor() ([]byte, []int) {
	return file_academic_provider_v1_provider_proto_rawDescGZIP(), []int{17}
}

func (x *Exam) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Exam) GetPeriodId() string {
	if x != nil {
		return x.PeriodId
	}
	return ""
}

func (x *Exam) GetCourseCode() string {
	if x != nil {
		return x.CourseCode
	}
	return ""
}

func (x *Exam) GetCourseName() string {
	if x != nil {
		return x.CourseName
	}
	return ""
}

func (x *Exam) GetStartAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartAt
	}
	return nil
}

func (x *Exam) GetEndAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndAt
	}
	return nil
}

func (x *Exam) GetCampus() string {
	if x != nil {
		return x.Campus
	}
	return ""
}

func (x *Exam) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Exam) GetSeat() string {
	if x != nil {
		return x.Seat
	}
	return ""
}

func (x *Exam) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *Exam) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Exam) GetMaterials() string {
	if x != nil {
		return x.Materials
	}
	return ""
}

func (x *Exam) GetNotice() string {
	if x != nil {
		return x.Notice
	}
	return ""
}

type ListCourseSelectionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Student       *StudentReference      `protobuf:"bytes,1,opt,name=student,proto3" json:"student,omitempty"`
	Credential    *Credential            `protobuf:"bytes,2,opt,name=credential,proto3" json:"credential,omitempty"`
	PeriodId      string                 `protobuf:"bytes,3,opt,name=period_id,json=periodId,proto3" json:"period_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCourseSelectionsRequest) Reset() {
	*x = ListCourseSelectionsRequest{}
	mi := &file_academic_provider_v1_provider_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCourseSelectionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCourseSelectionsRequest) ProtoMessage() {}

func (x *ListCourseSelectionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_academic_provider_v1_provider_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCourseSelectionsRequest.ProtoReflect.Descriptor instead.
func (*ListCourseSelectionsRequest) Descriptor() ([]byte, []int) {
	return file_academic_provider_v1_provider_proto_rawDescGZIP(), []int{18}
}

func (x *ListCourseSelectionsRequest) GetStudent() *StudentReference {
	if x != nil {
		return x.Student
	}
	return nil
}

func (x *ListCourseSelectionsRequest) GetCredential() *Credential {
	if x != nil {
		return x.Credential
	}
	return nil
}

func (x *ListCourseSelectionsRequest) GetPeriodId() string {
	if x != nil {
		return x.PeriodId
	}
	return ""
}

type ListCourseSelectionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Selections    []*CourseSelection     `protobuf:"bytes,1,rep,name=selections,proto3" json:"selections,omitempty"`
	Cache         *CacheMetadata         `protobuf:"bytes,2,opt,name=cache,proto3" json:"cache,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCourseSelectionsResponse) Reset() {
	*x = ListCourseSelectionsResponse{}
	mi := &file_academic_provider_v1_provider_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCourseSelectionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCourseSelectionsResponse) ProtoMessage() {}

func (x *ListCourseSelectionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_academic_provider_v1_provider_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCourseSelectionsResponse.ProtoReflect.Descriptor instead.
func (*ListCourseSelectionsResponse) Descriptor() ([]byte, []int) {
	return file_academic_provider_v1_provider_proto_rawDescGZIP(), []int{19}
}

func (x *ListCourseSelectionsResponse) GetSelections() []*CourseSelection {
	if x != nil {
		return x.Selections
	}
	return nil
}

func (x *ListCourseSelectionsResponse) GetCache() *CacheMetadata {
	if x != nil {
		return x.Cache
	}
	return nil
}

type CourseSelection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PeriodId      string                 `protobuf:"bytes,2,opt,name=period_id,json=periodId,proto3" json:"period_id,omitempty"`
	CourseCode    string                 `protobuf:"bytes,3,opt,name=course_code,json=courseCode,proto3" json:"course_code,omitempty"`
	CourseName    string                 `protobuf:"bytes,4,opt,name=course_name,json=courseName,proto3" json:"course_name,omitempty"`
	CourseType    string                 `protobuf:"bytes,5,opt,name=course_type,json=courseType,proto3" json:"course_type,omitempty"`
	Credit        float64                `protobuf:"fixed64,6,opt,name=credit,proto3" json:"credit,omitempty"`
	Teacher       string                 `protobuf:"bytes,7,opt,name=teacher,proto3" json:"teacher,omitempty"`
	Campus        string                 `protobuf:"bytes,8,opt,name=campus,proto3" json:"campus,omitempty"`
	Location      string                 `protobuf:"bytes,9,opt,name=location,proto3" json:"location,omitempty"`
	Schedule      string                 `protobuf:"bytes,10,opt,name=schedule,proto3" json:"schedule,omitempty"`
	Capacity      int32                  `protobuf:"varint,11,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Enrolled      int32                  `protobuf:"varint,12,opt,name=enrolled,proto3" json:"enrolled,omitempty"`
	Status        string                 `protobuf:"bytes,13,opt,name=status,proto3" json:"status,omitempty"`
	SelectedAt    *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=selected_at,json=selectedAt,proto3,oneof" json:"selected_at,omitempty"`
	ResultText    *string                `protobuf:"bytes,15,opt,name=result_text,json=resultText,proto3,oneof" json:"result_text,omitempty"`
	Note          *string                `protobuf:"bytes,16,opt,name=note,proto3,oneof" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CourseSelection) Reset() {
	*x = CourseSelection{}
	mi := &file_academic_provider_v1_provider_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CourseSelection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourseSelection) ProtoMessage() {}

func (x *CourseSelection) ProtoReflect() protoreflect.Message {
	mi := &file_academic_provider_v1_provider_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourseSelection.ProtoReflect.Descriptor instead.
func (*CourseSelection) Descriptor() ([]byte, []int) {
	return file_academic_provider_v1_provider_proto_rawDescGZIP(), []int{20}
}

func (x *CourseSelection) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CourseSelection) GetPeriodId() string {
	if x != nil {
		return x.PeriodId
	}
	return ""
}

func (x *CourseSelection) GetCourseCode() string {
	if x != nil {
		return x.CourseCode
	}
	return ""
}

func (x *CourseSelection) GetCourseName() string {
	if x != nil {
		return x.CourseName
	}
	return ""
}

func (x *CourseSelection) GetCourseType() string {
	if x != nil {
		return x.CourseType
	}
	return ""
}

func (x *CourseSelection) GetCredit() float64 {
	if x != nil {
		return x.Credit
	}
	return 0
}

func (x *CourseSelection) GetTeacher() string {
	if x != nil {
		return x.Teacher
	}
	return ""
}

func (x *CourseSelection) GetCampus() string {
	if x != nil {
		return x.Campus
	}
	return ""
}

func (x *CourseSelection) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *CourseSelection) GetSchedule() string {
	if x != nil {
		return x.Schedule
	}
	return ""
}

func (x *CourseSelection) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *CourseSelection) GetEnrolled() int32 {
	if x != nil {
		return x.Enrolled
	}
	return 0
}

func (x *CourseSelection) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CourseSelection) GetSelectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SelectedAt
	}
	return nil
}

func (x *CourseSelection) GetResultText() string {
	if x != nil && x.ResultText != nil {
		return *x.ResultText
	}
	return ""
}

func (x *CourseSelection) GetNote() string {
	if x != nil && x.Note != nil {
		return *x.Note
	}
	return ""
}

type ListCourseAdditionResultsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Student       *StudentReference      `protobuf:"bytes,1,opt,name=student,proto3" json:"student,omitempty"`
	Credential    *Credential            `protobuf:"bytes,2,opt,name=credential,proto3" json:"credential,omitempty"`
	PeriodId      string                 `protobuf:"bytes,3,opt,name=period_id,json=periodId,proto3" json:"period_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCourseAdditionResultsRequest) Reset() {
	*x = ListCourseAdditionResultsRequest{}
	mi := &file_academic_provider_v1_provider_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCourseAdditionResultsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCourseAdditionResultsRequest) ProtoMessage() {}

func (x *ListCourseAdditionResultsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_academic_provider_v1_provider_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCourseAdditionResultsRequest.ProtoReflect.Descriptor instead.
func (*ListCourseAdditionResultsRequest) Descriptor() ([]byte, []int) {
	return file_academic_provider_v1_provider_proto_rawDescGZIP(), []int{21}
}

func (x *ListCourseAdditionResultsRequest) GetStudent() *StudentReference {
	if x != nil {
		return x.Student
	}
	return nil
}

func (x *ListCourseAdditionResultsRequest) GetCredential() *Credential {
	if x != nil {
		return x.Credential
	}
	return nil
}

func (x *ListCourseAdditionResultsRequest) GetPeriodId() string {
	if x != nil {
		return x.PeriodId
	}
	return ""
}

type ListCourseAdditionResultsResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Results       []*CourseAdditionResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Cache         *CacheMetadata          `protobuf:"bytes,2,opt,name=cache,proto3" json:"cache,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCourseAdditionResultsResponse) Reset() {
	*x = ListCourseAdditionResultsResponse{}
	mi := &file_academic_provider_v1_provider_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCourseAdditionResultsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCourseAdditionResultsResponse) ProtoMessage() {}

func (x *ListCourseAdditionResultsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_academic_provider_v1_provider_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCourseAdditionResultsResponse.ProtoReflect.Descriptor instead.
func (*ListCourseAdditionResultsResponse) Descriptor() ([]byte, []int) {
	return file_academic_provider_v1_provider_proto_rawDescGZIP(), []int{22}
}

func (x *ListCourseAdditionResultsResponse) GetResults() []*CourseAdditionResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *ListCourseAdditionResultsResponse) GetCache() *CacheMetadata {
	if x != nil {
		return x.Cache
	}
	return nil
}

// CourseAdditionResult is one undergraduate course-addition application
// result. It deliberately excludes student identity fields (xh, xm) and
// upstream flags whose semantics are not defined (sfbmdsq, sftsqk).
type CourseAdditionResult struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Id       string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PeriodId string                 `protobuf:"bytes,2,opt,name=period_id,json=periodId,proto3" json:"period_id,omitempty"`
	// PeriodName is the upstream display name of the period, kept separate from
	// the period ID so clients never derive spring/autumn from the ID.
	PeriodName    string `protobuf:"bytes,3,opt,name=period_name,json=periodName,proto3" json:"period_name,omitempty"`
	CourseCode    string `protobuf:"bytes,4,opt,name=course_code,json=courseCode,proto3" json:"course_code,omitempty"`
	CourseName    string `protobuf:"bytes,5,opt,name=course_name,json=courseName,proto3" json:"course_name,omitempty"`
	SelectionCode string `protobuf:"bytes,6,opt,name=selection_code,json=selectionCode,proto3" json:"selection_code,omitempty"`
	Teacher       string `protobuf:"bytes,7,opt,name=teacher,proto3" json:"teacher,omitempty"`
	TeachingClass string `protobuf:"bytes,8,opt,name=teaching_class,json=teachingClass,proto3" json:"teaching_class,omitempty"`
	// AuditText is the authoritative review-status text returned verbatim by
	// the school (e.g. "审核中"). Unknown values are preserved, never coerced.
	AuditText     string `protobuf:"bytes,9,opt,name=audit_text,json=auditText,proto3" json:"audit_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CourseAdditionResult) Reset() {
	*x = CourseAdditionResult{}
	mi := &file_academic_provider_v1_provider_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CourseAdditionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourseAdditionResult) ProtoMessage() {}

func (x *CourseAdditionResult) ProtoReflect() protoreflect.Message {
	mi := &file_academic_provider_v1_provider_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourseAdditionResult.ProtoReflect.Descriptor instead.
func (*CourseAdditionResult) Descriptor() ([]byte, []int) {
	return file_academic_provider_v1_provider_proto_rawDescGZIP(), []int{23}
}

func (x *CourseAdditionResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CourseAdditionResult) GetPeriodId() string {
	if x != nil {
		return x.PeriodId
	}
	return ""
}

func (x *CourseAdditionResult) GetPeriodName() string {
	if x != nil {
		return x.PeriodName
	}
	return ""
}

func (x *CourseAdditionResult) GetCourseCode() string {
	if x != nil {
		return x.CourseCode
	}
	return ""
}

func (x *CourseAdditionResult) GetCourseName() string {
	if x != nil {
		return x.CourseName
	}
	return ""
}

func (x *CourseAdditionResult) GetSelectionCode() string {
	if x != nil {
		return x.SelectionCode
	}
	return ""
}

func (x *CourseAdditionResult) GetTeacher() string {
	if x != nil {
		return x.Teacher
	}
	return ""
}

func (x *CourseAdditionResult) GetTeachingClass() string {
	if x != nil {
		return x.TeachingClass
	}
	return ""
}

func (x *CourseAdditionResult) GetAuditText() string {
	if x != nil {
		return x.AuditText
	}
	return ""
}

type DeleteStudentSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentNo     string                 `protobuf:"bytes,1,opt,name=student_no,json=studentNo,proto3" json:"student_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteStudentSessionsRequest) Reset() {
	*x = DeleteStudentSessionsRequest{}
	mi := &file_academic_provider_v1_provider_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteStudentSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStudentSessionsRequest) ProtoMessage() {}

func (x *DeleteStudentSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_academic_provider_v1_provider_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStudentSessionsRequest.ProtoReflect.Descriptor instead.
func (*DeleteStudentSessionsRequest) Descriptor() ([]byte, []int) {
	return file_academic_provider_v1_provider_proto_rawDescGZIP(), []int{24}
}

func (x *DeleteStudentSessionsRequest) GetStudentNo() string {
	if x != nil {
		return x.StudentNo
	}
	return ""
}

type DeleteStudentSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteStudentSessionsResponse) Reset() {
	*x = DeleteStudentSessionsResponse{}
	mi := &file_academic_provider_v1_provider_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteStudentSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStudentSessionsResponse) ProtoMessage() {}

func (x *DeleteStudentSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_academic_provider_v1_provider_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStudentSessionsResponse.ProtoReflect.Descriptor instead.
func (*DeleteStudentSessionsResponse) Descriptor() ([]byte, []int) {
	return file_academic_provider_v1_provider_proto_rawDescGZIP(), []int{25}
}

type ListCourseCatalogPageRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Credential     *Credential            `protobuf:"bytes,1,opt,name=credential,proto3" json:"credential,omitempty"`
	EducationLevel string                 `protobuf:"bytes,2,opt,name=education_level,json=educationLevel,proto3" json:"education_level,omitempty"`
	PeriodId       string                 `protobuf:"bytes,3,opt,name=period_id,json=periodId,proto3" json:"period_id,omitempty"`
	Page           int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListCourseCatalogPageRequest) Reset() {
	*x = ListCourseCatalogPageRequest{}
	mi := &file_academic_provider_v1_provider_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCourseCatalogPageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCourseCatalogPageRequest) ProtoMessage() {}

func (x *ListCourseCatalogPageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_academic_provider_v1_provider_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCourseCatalogPageRequest.ProtoReflect.Descriptor instead.
func (*ListCourseCatalogPageRequest) Descriptor() ([]byte, []int) {
	return file_academic_provider_v1_provider_proto_rawDescGZIP(), []int{26}
}

func (x *ListCourseCatalogPageRequest) GetCredential() *Credential {
	if x != nil {
		return x.Credential
	}
	return nil
}

func (x *ListCourseCatalogPageRequest) GetEducationLevel() string {
	if x != nil {
		return x.EducationLevel
	}
	return ""
}

func (x *ListCourseCatalogPageRequest) GetPeriodId() string {
	if x != nil {
		return x.PeriodId
	}
	return ""
}

func (x *ListCourseCatalogPageRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type ListCourseCatalogPageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*CourseCatalogEntry  `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	TotalCount    int32                  `protobuf:"varint,4,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	TotalPages    int32                  `protobuf:"varint,5,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	HasMore       bool                   `protobuf:"varint,6,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCourseCatalogPageResponse) Reset() {
	*x = ListCourseCatalogPageResponse{}
	mi := &file_academic_provider_v1_provider_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCourseCatalogPageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCourseCatalogPageResponse) ProtoMessage() {}

func (x *ListCourseCatalogPageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_academic_provider_v1_provider_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCourseCatalogPageResponse.ProtoReflect.Descriptor instead.
func (*ListCourseCatalogPageResponse) Descriptor() ([]byte, []int) {
	return file_academic_provider_v1_provider_proto_rawDescGZIP(), []int{27}
}

func (x *ListCourseCatalogPageResponse) GetEntries() []*CourseCatalogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *ListCourseCatalogPageResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListCourseCatalogPageResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListCourseCatalogPageResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListCourseCatalogPageResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *ListCourseCatalogPageResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type CourseCatalogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceKey     string                 `protobuf:"bytes,1,opt,name=source_key,json=sourceKey,proto3" json:"source_key,omitempty"`
	PeriodId      string                 `protobuf:"bytes,2,opt,name=period_id,json=periodId,proto3" json:"period_id,omitempty"`
	OpeningCode   string                 `protobuf:"bytes,3,opt,name=opening_code,json=openingCode,proto3" json:"opening_code,omitempty"`
	CourseCode    string                 `protobuf:"bytes,4,opt,name=course_code,json=courseCode,proto3" json:"course_code,omitempty"`
	CourseName    string                 `protobuf:"bytes,5,opt,name=course_name,json=courseName,proto3" json:"course_name,omitempty"`
	CourseType    string                 `protobuf:"bytes,6,opt,name=course_type,json=courseType,proto3" json:"course_type,omitempty"`
	Department    string                 `protobuf:"bytes,7,opt,name=department,proto3" json:"department,omitempty"`
	Teachers      string                 `protobuf:"bytes,8,opt,name=teachers,proto3" json:"teachers,omitempty"`
	Campus        string                 `protobuf:"bytes,9,opt,name=campus,proto3" json:"campus,omitempty"`
	Classes       string                 `protobuf:"bytes,10,opt,name=classes,proto3" json:"classes,omitempty"`
	Schedule      string                 `protobuf:"bytes,11,opt,name=schedule,proto3" json:"schedule,omitempty"`
	Location      string                 `protobuf:"bytes,12,opt,name=location,proto3" json:"location,omitempty"`
	Language      string                 `protobuf:"bytes,13,opt,name=language,proto3" json:"language,omitempty"`
	Capacity      int32                  `protobuf:"varint,14,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Enrolled      int32                  `protobuf:"varint,15,opt,name=enrolled,proto3" json:"enrolled,omitempty"`
	Note          string                 `protobuf:"bytes,16,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CourseCatalogEntry) Reset() {
	*x = CourseCatalogEntry{}
	mi := &file_academic_provider_v1_provider_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CourseCatalogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourseCatalogEntry) ProtoMessage() {}

func (x *CourseCatalogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_academic_provider_v1_provider_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourseCatalogEntry.ProtoReflect.Descriptor instead.
func (*CourseCatalogEntry) Descriptor() ([]byte, []int) {
	return file_academic_provider_v1_provider_proto_rawDescGZIP(), []int{28}
}

func (x *CourseCatalogEntry) GetSourceKey() string {
	if x != nil {
		return x.SourceKey
	}
	return ""
}

func (x *CourseCatalogEntry) GetPeriodId() string {
	if x != nil {
		return x.PeriodId
	}
	return ""
}

func (x *CourseCatalogEntry) GetOpeningCode() string {
	if x != nil {
		return x.OpeningCode
	}
	return ""
}

func (x *CourseCatalogEntry) GetCourseCode() string {
	if x != nil {
		return x.CourseCode
	}
	return ""
}

func (x *CourseCatalogEntry) GetCourseName() string {
	if x != nil {
		return x.CourseName
	}
	return ""
}

func (x *CourseCatalogEntry) GetCourseType() string {
	if x != nil {
		return x.CourseType
	}
	return ""
}

func (x *CourseCatalogEntry) GetDepartment() string {
	if x != nil {
		return x.Department
	}
	return ""
}

func (x *CourseCatalogEntry) GetTeachers() string {
	if x != nil {
		return x.Teachers
	}
	return ""
}

func (x *CourseCatalogEntry) GetCampus() string {
	if x != nil {
		return x.Campus
	}
	return ""
}

func (x *CourseCatalogEntry) GetClasses() string {
	if x != nil {
		return x.Classes
	}
	return ""
}

func (x *CourseCatalogEntry) GetSchedule() string {
	if x != nil {
		return x.Schedule
	}
	return ""
}

func (x *CourseCatalogEntry) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *CourseCatalogEntry) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *CourseCatalogEntry) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *CourseCatalogEntry) GetEnrolled() int32 {
	if x != nil {
		return x.Enrolled
	}
	return 0
}

func (x *CourseCatalogEntry) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

var File_academic_provider_v1_provider_proto protoreflect.FileDescriptor

const file_academic_provider_v1_provider_proto_rawDesc = "" +
	"\n" +
	"#academic/provider/v1/provider.proto\x12\x14academic.provider.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"G\n" +
	"\n" +
	"Credential\x12\x1d\n" +
	"\n" +
	"student_no\x18\x01 \x01(\tR\tstudentNo\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x8f\x01\n" +
	"\x10StudentReference\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1d\n" +
	"\n" +
	"student_no\x18\x02 \x01(\tR\tstudentNo\x12\x1a\n" +
	"\bprovider\x18\x03 \x01(\tR\bprovider\x12'\n" +
	"\x0feducation_level\x18\x04 \x01(\tR\x0eeducationLevel\"\x84\x01\n" +
	"\x17VerifyCredentialRequest\x12@\n" +
	"\n" +
	"credential\x18\x01 \x01(\v2 .academic.provider.v1.CredentialR\n" +
	"credential\x12'\n" +
	"\x0feducation_level\x18\x02 \x01(\tR\x0eeducationLevel\"|\n" +
	"\x18VerifyCredentialResponse\x12\x1b\n" +
	"\treal_name\x18\x01 \x01(\tR\brealName\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12'\n" +
	"\x0feducation_level\x18\x03 \x01(\tR\x0eeducationLevel\"\x8b\x01\n" +
	"\x1eVerifyManagedCredentialRequest\x12@\n" +
	"\n" +
	"credential\x18\x01 \x01(\v2 .academic.provider.v1.CredentialR\n" +
	"credential\x12'\n" +
	"\x0feducation_level\x18\x02 \x01(\tR\x0eeducationLevel\"\x83\x01\n" +
	"\x1fVerifyManagedCredentialResponse\x12\x1b\n" +
	"\treal_name\x18\x01 \x01(\tR\brealName\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12'\n" +
	"\x0feducation_level\x18\x03 \x01(\tR\x0eeducationLevel\"\xb5\x01\n" +
	"\x12ListCoursesRequest\x12@\n" +
	"\astudent\x18\x01 \x01(\v2&.academic.provider.v1.StudentReferenceR\astudent\x12@\n" +
	"\n" +
	"credential\x18\x02 \x01(\v2 .academic.provider.v1.CredentialR\n" +
	"credential\x12\x1b\n" +
	"\tperiod_id\x18\x03 \x01(\tR\bperiodId\"\xad\x01\n" +
	"\x13ListCoursesResponse\x126\n" +
	"\acourses\x18\x01 \x03(\v2\x1c.academic.provider.v1.CourseR\acourses\x129\n" +
	"\x05cache\x18\x02 \x01(\v2#.academic.provider.v1.CacheMetadataR\x05cache\x12#\n" +
	"\rschedule_note\x18\x03 \x01(\tR\fscheduleNote\"\x9b\x01\n" +
	"\rCacheMetadata\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x127\n" +
	"\tcached_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bcachedAt\x12;\n" +
	"\vfresh_until\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"freshUntil\"\xdf\x02\n" +
	"\x06Course\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tperiod_id\x18\x02 \x01(\tR\bperiodId\x12\x1f\n" +
	"\vcourse_code\x18\x03 \x01(\tR\n" +
	"courseCode\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x18\n" +
	"\ateacher\x18\x05 \x01(\tR\ateacher\x12\x16\n" +
	"\x06campus\x18\x06 \x01(\tR\x06campus\x12\x1a\n" +
	"\blocation\x18\a \x01(\tR\blocation\x12\x18\n" +
	"\aweekday\x18\b \x01(\x05R\aweekday\x12#\n" +
	"\rstart_section\x18\t \x01(\x05R\fstartSection\x12\x1f\n" +
	"\vend_section\x18\n" +
	" \x01(\x05R\n" +
	"endSection\x12\x14\n" +
	"\x05weeks\x18\v \x03(\x05R\x05weeks\x12\x12\n" +
	"\x04note\x18\f \x01(\tR\x04note\x12\x1b\n" +
	"\tclass_num\x18\r \x01(\tR\bclassNum\"\xc4\x01\n" +
	"!GetCourseSelectionScheduleRequest\x12@\n" +
	"\astudent\x18\x01 \x01(\v2&.academic.provider.v1.StudentReferenceR\astudent\x12@\n" +
	"\n" +
	"credential\x18\x02 \x01(\v2 .academic.provider.v1.CredentialR\n" +
	"credential\x12\x1b\n" +
	"\tperiod_id\x18\x03 \x01(\tR\bperiodId\"\xbc\x01\n" +
	"\"GetCourseSelectionScheduleResponse\x126\n" +
	"\acourses\x18\x01 \x03(\v2\x1c.academic.provider.v1.CourseR\acourses\x129\n" +
	"\x05cache\x18\x02 \x01(\v2#.academic.provider.v1.CacheMetadataR\x05cache\x12#\n" +
	"\rschedule_note\x18\x03 \x01(\tR\fscheduleNote\"\xb4\x01\n" +
	"\x11ListGradesRequest\x12@\n" +
	"\astudent\x18\x01 \x01(\v2&.academic.provider.v1.StudentReferenceR\astudent\x12@\n" +
	"\n" +
	"credential\x18\x02 \x01(\v2 .academic.provider.v1.CredentialR\n" +
	"credential\x12\x1b\n" +
	"\tperiod_id\x18\x03 \x01(\tR\bperiodId\"\x84\x01\n" +
	"\x12ListGradesResponse\x123\n" +
	"\x06grades\x18\x01 \x03(\v2\x1b.academic.provider.v1.GradeR\x06grades\x129\n" +
	"\x05cache\x18\x02 \x01(\v2#.academic.provider.v1.CacheMetadataR\x05cache\"\xa9\x02\n" +
	"\x05Grade\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tperiod_id\x18\x02 \x01(\tR\bperiodId\x12\x1f\n" +
	"\vcourse_code\x18\x03 \x01(\tR\n" +
	"courseCode\x12\x1f\n" +
	"\vcourse_name\x18\x04 \x01(\tR\n" +
	"courseName\x12\x1f\n" +
	"\vcourse_type\x18\x05 \x01(\tR\n" +
	"courseType\x12\x16\n" +
	"\x06credit\x18\x06 \x01(\x01R\x06credit\x12\x1d\n" +
	"\n" +
	"grade_type\x18\a \x01(\tR\tgradeType\x12\x19\n" +
	"\x05score\x18\b \x01(\x01H\x00R\x05score\x88\x01\x01\x12$\n" +
	"\vgrade_level\x18\t \x01(\tH\x01R\n" +
	"gradeLevel\x88\x01\x01B\b\n" +
	"\x06_scoreB\x0e\n" +
	"\f_grade_level\"\xb3\x01\n" +
	"\x10ListExamsRequest\x12@\n" +
	"\astudent\x18\x01 \x01(\v2&.academic.provider.v1.StudentReferenceR\astudent\x12@\n" +
	"\n" +
	"credential\x18\x02 \x01(\v2 .academic.provider.v1.CredentialR\n" +
	"credential\x12\x1b\n" +
	"\tperiod_id\x18\x03 \x01(\tR\bperiodId\"\x80\x01\n" +
	"\x11ListExamsResponse\x120\n" +
	"\x05exams\x18\x01 \x03(\v2\x1a.academic.provider.v1.ExamR\x05exams\x129\n" +
	"\x05cache\x18\x02 \x01(\v2#.academic.provider.v1.CacheMetadataR\x05cache\"\x8b\x03\n" +
	"\x04Exam\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tperiod_id\x18\x02 \x01(\tR\bperiodId\x12\x1f\n" +
	"\vcourse_code\x18\x03 \x01(\tR\n" +
	"courseCode\x12\x1f\n" +
	"\vcourse_name\x18\x04 \x01(\tR\n" +
	"courseName\x125\n" +
	"\bstart_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\astartAt\x121\n" +
	"\x06end_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x05endAt\x12\x16\n" +
	"\x06campus\x18\a \x01(\tR\x06campus\x12\x1a\n" +
	"\blocation\x18\b \x01(\tR\blocation\x12\x12\n" +
	"\x04seat\x18\t \x01(\tR\x04seat\x12\x14\n" +
	"\x05phase\x18\n" +
	" \x01(\tR\x05phase\x12\x16\n" +
	"\x06method\x18\v \x01(\tR\x06method\x12\x1c\n" +
	"\tmaterials\x18\f \x01(\tR\tmaterials\x12\x16\n" +
	"\x06notice\x18\r \x01(\tR\x06notice\"\xbe\x01\n" +
	"\x1bListCourseSelectionsRequest\x12@\n" +
	"\astudent\x18\x01 \x01(\v2&.academic.provider.v1.StudentReferenceR\astudent\x12@\n" +
	"\n" +
	"credential\x18\x02 \x01(\v2 .academic.provider.v1.CredentialR\n" +
	"credential\x12\x1b\n" +
	"\tperiod_id\x18\x03 \x01(\tR\bperiodId\"\xa0\x01\n" +
	"\x1cListCourseSelectionsResponse\x12E\n" +
	"\n" +
	"selections\x18\x01 \x03(\v2%.academic.provider.v1.CourseSelectionR\n" +
	"selections\x129\n" +
	"\x05cache\x18\x02 \x01(\v2#.academic.provider.v1.CacheMetadataR\x05cache\"\x9d\x04\n" +
	"\x0fCourseSelection\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tperiod_id\x18\x02 \x01(\tR\bperiodId\x12\x1f\n" +
	"\vcourse_code\x18\x03 \x01(\tR\n" +
	"courseCode\x12\x1f\n" +
	"\vcourse_name\x18\x04 \x01(\tR\n" +
	"courseName\x12\x1f\n" +
	"\vcourse_type\x18\x05 \x01(\tR\n" +
	"courseType\x12\x16\n" +
	"\x06credit\x18\x06 \x01(\x01R\x06credit\x12\x18\n" +
	"\ateacher\x18\a \x01(\tR\ateacher\x12\x16\n" +
	"\x06campus\x18\b \x01(\tR\x06campus\x12\x1a\n" +
	"\blocation\x18\t \x01(\tR\blocation\x12\x1a\n" +
	"\bschedule\x18\n" +
	" \x01(\tR\bschedule\x12\x1a\n" +
	"\bcapacity\x18\v \x01(\x05R\bcapacity\x12\x1a\n" +
	"\benrolled\x18\f \x01(\x05R\benrolled\x12\x16\n" +
	"\x06status\x18\r \x01(\tR\x06status\x12@\n" +
	"\vselected_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampH\x00R\n" +
	"selectedAt\x88\x01\x01\x12$\n" +
	"\vresult_text\x18\x0f \x01(\tH\x01R\n" +
	"resultText\x88\x01\x01\x12\x17\n" +
	"\x04note\x18\x10 \x01(\tH\x02R\x04note\x88\x01\x01B\x0e\n" +
	"\f_selected_atB\x0e\n" +
	"\f_result_textB\a\n" +
	"\x05_note\"\xc3\x01\n" +
	" ListCourseAdditionResultsRequest\x12@\n" +
	"\astudent\x18\x01 \x01(\v2&.academic.provider.v1.StudentReferenceR\astudent\x12@\n" +
	"\n" +
	"credential\x18\x02 \x01(\v2 .academic.provider.v1.CredentialR\n" +
	"credential\x12\x1b\n" +
	"\tperiod_id\x18\x03 \x01(\tR\bperiodId\"\xa4\x01\n" +
	"!ListCourseAdditionResultsResponse\x12D\n" +
	"\aresults\x18\x01 \x03(\v2*.academic.provider.v1.CourseAdditionResultR\aresults\x129\n" +
	"\x05cache\x18\x02 \x01(\v2#.academic.provider.v1.CacheMetadataR\x05cache\"\xad\x02\n" +
	"\x14CourseAdditionResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tperiod_id\x18\x02 \x01(\tR\bperiodId\x12\x1f\n" +
	"\vperiod_name\x18\x03 \x01(\tR\n" +
	"periodName\x12\x1f\n" +
	"\vcourse_code\x18\x04 \x01(\tR\n" +
	"courseCode\x12\x1f\n" +
	"\vcourse_name\x18\x05 \x01(\tR\n" +
	"courseName\x12%\n" +
	"\x0eselection_code\x18\x06 \x01(\tR\rselectionCode\x12\x18\n" +
	"\ateacher\x18\a \x01(\tR\ateacher\x12%\n" +
	"\x0eteaching_class\x18\b \x01(\tR\rteachingClass\x12\x1d\n" +
	"\n" +
	"audit_text\x18\t \x01(\tR\tauditText\"=\n" +
	"\x1cDeleteStudentSessionsRequest\x12\x1d\n" +
	"\n" +
	"student_no\x18\x01 \x01(\tR\tstudentNo\"\x1f\n" +
	"\x1dDeleteStudentSessionsResponse\"\xba\x01\n" +
	"\x1cListCourseCatalogPageRequest\x12@\n" +
	"\n" +
	"credential\x18\x01 \x01(\v2 .academic.provider.v1.CredentialR\n" +
	"credential\x12'\n" +
	"\x0feducation_level\x18\x02 \x01(\tR\x0eeducationLevel\x12\x1b\n" +
	"\tperiod_id\x18\x03 \x01(\tR\bperiodId\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\"\xf1\x01\n" +
	"\x1dListCourseCatalogPageResponse\x12B\n" +
	"\aentries\x18\x01 \x03(\v2(.academic.provider.v1.CourseCatalogEntryR\aentries\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1f\n" +
	"\vtotal_count\x18\x04 \x01(\x05R\n" +
	"totalCount\x12\x1f\n" +
	"\vtotal_pages\x18\x05 \x01(\x05R\n" +
	"totalPages\x12\x19\n" +
	"\bhas_more\x18\x06 \x01(\bR\ahasMore\"\xe4\x03\n" +
	"\x12CourseCatalogEntry\x12\x1d\n" +
	"\n" +
	"source_key\x18\x01 \x01(\tR\tsourceKey\x12\x1b\n" +
	"\tperiod_id\x18\x02 \x01(\tR\bperiodId\x12!\n" +
	"\fopening_code\x18\x03 \x01(\tR\vopeningCode\x12\x1f\n" +
	"\vcourse_code\x18\x04 \x01(\tR\n" +
	"courseCode\x12\x1f\n" +
	"\vcourse_name\x18\x05 \x01(\tR\n" +
	"courseName\x12\x1f\n" +
	"\vcourse_type\x18\x06 \x01(\tR\n" +
	"courseType\x12\x1e\n" +
	"\n" +
	"department\x18\a \x01(\tR\n" +
	"department\x12\x1a\n" +
	"\bteachers\x18\b \x01(\tR\bteachers\x12\x16\n" +
	"\x06campus\x18\t \x01(\tR\x06campus\x12\x18\n" +
	"\aclasses\x18\n" +
	" \x01(\tR\aclasses\x12\x1a\n" +
	"\bschedule\x18\v \x01(\tR\bschedule\x12\x1a\n" +
	"\blocation\x18\f \x01(\tR\blocation\x12\x1a\n" +
	"\blanguage\x18\r \x01(\tR\blanguage\x12\x1a\n" +
	"\bcapacity\x18\x0e \x01(\x05R\bcapacity\x12\x1a\n" +
	"\benrolled\x18\x0f \x01(\x05R\benrolled\x12\x12\n" +
	"\x04note\x18\x10 \x01(\tR\x04note2\xde\t\n" +
	"\x17AcademicProviderService\x12q\n" +
	"\x10VerifyCredential\x12-.academic.provider.v1.VerifyCredentialRequest\x1a..academic.provider.v1.VerifyCredentialResponse\x12\x86\x01\n" +
	"\x17VerifyManagedCredential\x124.academic.provider.v1.VerifyManagedCredentialRequest\x1a5.academic.provider.v1.VerifyManagedCredentialResponse\x12b\n" +
	"\vListCourses\x12(.academic.provider.v1.ListCoursesRequest\x1a).academic.provider.v1.ListCoursesResponse\x12\x8f\x01\n" +
	"\x1aGetCourseSelectionSchedule\x127.academic.provider.v1.GetCourseSelectionScheduleRequest\x1a8.academic.provider.v1.GetCourseSelectionScheduleResponse\x12_\n" +
	"\n" +
	"ListGrades\x12'.academic.provider.v1.ListGradesRequest\x1a(.academic.provider.v1.ListGradesResponse\x12\\\n" +
	"\tListExams\x12&.academic.provider.v1.ListExamsRequest\x1a'.academic.provider.v1.ListExamsResponse\x12}\n" +
	"\x14ListCourseSelections\x121.academic.provider.v1.ListCourseSelectionsRequest\x1a2.academic.provider.v1.ListCourseSelectionsResponse\x12\x8c\x01\n" +
	"\x19ListCourseAdditionResults\x126.academic.provider.v1.ListCourseAdditionResultsRequest\x1a7.academic.provider.v1.ListCourseAdditionResultsResponse\x12\x80\x01\n" +
	"\x15ListCourseCatalogPage\x122.academic.provider.v1.ListCourseCatalogPageRequest\x1a3.academic.provider.v1.ListCourseCatalogPageResponse\x12\x80\x01\n" +
	"\x15DeleteStudentSessions\x122.academic.provider.v1.DeleteStudentSessionsRequest\x1a3.academic.provider.v1.DeleteStudentSessionsResponseBTZRgithub.com/LDouble/campus-academic-api/pkg/academic/provider/v1;academicproviderv1b\x06proto3"

var (
	file_academic_provider_v1_provider_proto_rawDescOnce sync.Once
	file_academic_provider_v1_provider_proto_rawDescData []byte
)

func file_academic_provider_v1_provider_proto_rawDescGZIP() []byte {
	file_academic_provider_v1_provider_proto_rawDescOnce.Do(func() {
		file_academic_provider_v1_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_academic_provider_v1_provider_proto_rawDesc), len(file_academic_provider_v1_provider_proto_rawDesc)))
	})
	return file_academic_provider_v1_provider_proto_rawDescData
}

var file_academic_provider_v1_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_academic_provider_v1_provider_proto_goTypes = []any{
	(*Credential)(nil),                         // 0: academic.provider.v1.Credential
	(*StudentReference)(nil),                   // 1: academic.provider.v1.StudentReference
	(*VerifyCredentialRequest)(nil),            // 2: academic.provider.v1.VerifyCredentialRequest
	(*VerifyCredentialResponse)(nil),           // 3: academic.provider.v1.VerifyCredentialResponse
	(*VerifyManagedCredentialRequest)(nil),     // 4: academic.provider.v1.VerifyManagedCredentialRequest
	(*VerifyManagedCredentialResponse)(nil),    // 5: academic.provider.v1.VerifyManagedCredentialResponse
	(*ListCoursesRequest)(nil),                 // 6: academic.provider.v1.ListCoursesRequest
	(*ListCoursesResponse)(nil),                // 7: academic.provider.v1.ListCoursesResponse
	(*CacheMetadata)(nil),                      // 8: academic.provider.v1.CacheMetadata
	(*Course)(nil),                             // 9: academic.provider.v1.Course
	(*GetCourseSelectionScheduleRequest)(nil),  // 10: academic.provider.v1.GetCourseSelectionScheduleRequest
	(*GetCourseSelectionScheduleResponse)(nil), // 11: academic.provider.v1.GetCourseSelectionScheduleResponse
	(*ListGradesRequest)(nil),                  // 12: academic.provider.v1.ListGradesRequest
	(*ListGradesResponse)(nil),                 // 13: academic.provider.v1.ListGradesResponse
	(*Grade)(nil),                              // 14: academic.provider.v1.Grade
	(*ListExamsRequest)(nil),                   // 15: academic.provider.v1.ListExamsRequest
	(*ListExamsResponse)(nil),                  // 16: academic.provider.v1.ListExamsResponse
	(*Exam)(nil),                               // 17: academic.provider.v1.Exam
	(*ListCourseSelectionsRequest)(nil),        // 18: academic.provider.v1.ListCourseSelectionsRequest
	(*ListCourseSelectionsResponse)(nil),       // 19: academic.provider.v1.ListCourseSelectionsResponse
	(*CourseSelection)(nil),                    // 20: academic.provider.v1.CourseSelection
	(*ListCourseAdditionResultsRequest)(nil),   // 21: academic.provider.v1.ListCourseAdditionResultsRequest
	(*ListCourseAdditionResultsResponse)(nil),  // 22: academic.provider.v1.ListCourseAdditionResultsResponse
	(*CourseAdditionResult)(nil),               // 23: academic.provider.v1.CourseAdditionResult
	(*DeleteStudentSessionsRequest)(nil),       // 24: academic.provider.v1.DeleteStudentSessionsRequest
	(*DeleteStudentSessionsResponse)(nil),      // 25: academic.provider.v1.DeleteStudentSessionsResponse
	(*ListCourseCatalogPageRequest)(nil),       // 26: academic.provider.v1.ListCourseCatalogPageRequest
	(*ListCourseCatalogPageResponse)(nil),      // 27: academic.provider.v1.ListCourseCatalogPageResponse
	(*CourseCatalogEntry)(nil),                 // 28: academic.provider.v1.CourseCatalogEntry
	(*timestamppb.Timestamp)(nil),              // 29: google.protobuf.Timestamp
}
var file_academic_provider_v1_provider_proto_depIdxs = []int32{
	0,  // 0: academic.provider.v1.VerifyCredentialRequest.credential:type_name -> academic.provider.v1.Credential
	0,  // 1: academic.provider.v1.VerifyManagedCredentialRequest.credential:type_name -> academic.provider.v1.Credential
	1,  // 2: academic.provider.v1.ListCoursesRequest.student:type_name -> academic.provider.v1.StudentReference
	0,  // 3: academic.provider.v1.ListCoursesRequest.credential:type_name -> academic.provider.v1.Credential
	9,  // 4: academic.provider.v1.ListCoursesResponse.courses:type_name -> academic.provider.v1.Course
	8,  // 5: academic.provider.v1.ListCoursesResponse.cache:type_name -> academic.provider.v1.CacheMetadata
	29, // 6: academic.provider.v1.CacheMetadata.cached_at:type_name -> google.protobuf.Timestamp
	29, // 7: academic.provider.v1.CacheMetadata.fresh_until:type_name -> google.protobuf.Timestamp
	1,  // 8: academic.provider.v1.GetCourseSelectionScheduleRequest.student:type_name -> academic.provider.v1.StudentReference
	0,  // 9: academic.provider.v1.GetCourseSelectionScheduleRequest.credential:type_name -> academic.provider.v1.Credential
	9,  // 10: academic.provider.v1.GetCourseSelectionScheduleResponse.courses:type_name -> academic.provider.v1.Course
	8,  // 11: academic.provider.v1.GetCourseSelectionScheduleResponse.cache:type_name -> academic.provider.v1.CacheMetadata
	1,  // 12: academic.provider.v1.ListGradesRequest.student:type_name -> academic.provider.v1.StudentReference
	0,  // 13: academic.provider.v1.ListGradesRequest.credential:type_name -> academic.provider.v1.Credential
	14, // 14: academic.provider.v1.ListGradesResponse.grades:type_name -> academic.provider.v1.Grade
	8,  // 15: academic.provider.v1.ListGradesResponse.cache:type_name -> academic.provider.v1.CacheMetadata
	1,  // 16: academic.provider.v1.ListExamsRequest.student:type_name -> academic.provider.v1.StudentReference
	0,  // 17: academic.provider.v1.ListExamsRequest.credential:type_name -> academic.provider.v1.Credential
	17, // 18: academic.provider.v1.ListExamsResponse.exams:type_name -> academic.provider.v1.Exam
	8,  // 19: academic.provider.v1.ListExamsResponse.cache:type_name -> academic.provider.v1.CacheMetadata
	29, // 20: academic.provider.v1.Exam.start_at:type_name -> google.protobuf.Timestamp
	29, // 21: academic.provider.v1.Exam.end_at:type_name -> google.protobuf.Timestamp
	1,  // 22: academic.provider.v1.ListCourseSelectionsRequest.student:type_name -> academic.provider.v1.StudentReference
	0,  // 23: academic.provider.v1.ListCourseSelectionsRequest.credential:type_name -> academic.provider.v1.Credential
	20, // 24: academic.provider.v1.ListCourseSelectionsResponse.selections:type_name -> academic.provider.v1.CourseSelection
	8,  // 25: academic.provider.v1.ListCourseSelectionsResponse.cache:type_name -> academic.provider.v1.CacheMetadata
	29, // 26: academic.provider.v1.CourseSelection.selected_at:type_name -> google.protobuf.Timestamp
	1,  // 27: academic.provider.v1.ListCourseAdditionResultsRequest.student:type_name -> academic.provider.v1.StudentReference
	0,  // 28: academic.provider.v1.ListCourseAdditionResultsRequest.credential:type_name -> academic.provider.v1.Credential
	23, // 29: academic.provider.v1.ListCourseAdditionResultsResponse.results:type_name -> academic.provider.v1.CourseAdditionResult
	8,  // 30: academic.provider.v1.ListCourseAdditionResultsResponse.cache:type_name -> academic.provider.v1.CacheMetadata
	0,  // 31: academic.provider.v1.ListCourseCatalogPageRequest.credential:type_name -> academic.provider.v1.Credential
	28, // 32: academic.provider.v1.ListCourseCatalogPageResponse.entries:type_name -> academic.provider.v1.CourseCatalogEntry
	2,  // 33: academic.provider.v1.AcademicProviderService.VerifyCredential:input_type -> academic.provider.v1.VerifyCredentialRequest
	4,  // 34: academic.provider.v1.AcademicProviderService.VerifyManagedCredential:input_type -> academic.provider.v1.VerifyManagedCredentialRequest
	6,  // 35: academic.provider.v1.AcademicProviderService.ListCourses:input_type -> academic.provider.v1.ListCoursesRequest
	10, // 36: academic.provider.v1.AcademicProviderService.GetCourseSelectionSchedule:input_type -> academic.provider.v1.GetCourseSelectionScheduleRequest
	12, // 37: academic.provider.v1.AcademicProviderService.ListGrades:input_type -> academic.provider.v1.ListGradesRequest
	15, // 38: academic.provider.v1.AcademicProviderService.ListExams:input_type -> academic.provider.v1.ListExamsRequest
	18, // 39: academic.provider.v1.AcademicProviderService.ListCourseSelections:input_type -> academic.provider.v1.ListCourseSelectionsRequest
	21, // 40: academic.provider.v1.AcademicProviderService.ListCourseAdditionResults:input_type -> academic.provider.v1.ListCourseAdditionResultsRequest
	26, // 41: academic.provider.v1.AcademicProviderService.ListCourseCatalogPage:input_type -> academic.provider.v1.ListCourseCatalogPageRequest
	24, // 42: academic.provider.v1.AcademicProviderService.DeleteStudentSessions:input_type -> academic.provider.v1.DeleteStudentSessionsRequest
	3,  // 43: academic.provider.v1.AcademicProviderService.VerifyCredential:output_type -> academic.provider.v1.VerifyCredentialResponse
	5,  // 44: academic.provider.v1.AcademicProviderService.VerifyManagedCredential:output_type -> academic.provider.v1.VerifyManagedCredentialResponse
	7,  // 45: academic.provider.v1.AcademicProviderService.ListCourses:output_type -> academic.provider.v1.ListCoursesResponse
	11, // 46: academic.provider.v1.AcademicProviderService.GetCourseSelectionSchedule:output_type -> academic.provider.v1.GetCourseSelectionScheduleResponse
	13, // 47: academic.provider.v1.AcademicProviderService.ListGrades:output_type -> academic.provider.v1.ListGradesResponse
	16, // 48: academic.provider.v1.AcademicProviderService.ListExams:output_type -> academic.provider.v1.ListExamsResponse
	19, // 49: academic.provider.v1.AcademicProviderService.ListCourseSelections:output_type -> academic.provider.v1.ListCourseSelectionsResponse
	22, // 50: academic.provider.v1.AcademicProviderService.ListCourseAdditionResults:output_type -> academic.provider.v1.ListCourseAdditionResultsResponse
	27, // 51: academic.provider.v1.AcademicProviderService.ListCourseCatalogPage:output_type -> academic.provider.v1.ListCourseCatalogPageResponse
	25, // 52: academic.provider.v1.AcademicProviderService.DeleteStudentSessions:output_type -> academic.provider.v1.DeleteStudentSessionsResponse
	43, // [43:53] is the sub-list for method output_type
	33, // [33:43] is the sub-list for method input_type
	33, // [33:33] is the sub-list for extension type_name
	33, // [33:33] is the sub-list for extension extendee
	0,  // [0:33] is the sub-list for field type_name
}

func init() { file_academic_provider_v1_provider_proto_init() }
func file_academic_provider_v1_provider_proto_init() {
	if File_academic_provider_v1_provider_proto != nil {
		return
	}
	file_academic_provider_v1_provider_proto_msgTypes[14].OneofWrappers = []any{}
	file_academic_provider_v1_provider_proto_msgTypes[20].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_academic_provider_v1_provider_proto_rawDesc), len(file_academic_provider_v1_provider_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_academic_provider_v1_provider_proto_goTypes,
		DependencyIndexes: file_academic_provider_v1_provider_proto_depIdxs,
		MessageInfos:      file_academic_provider_v1_provider_proto_msgTypes,
	}.Build()
	File_academic_provider_v1_provider_proto = out.File
	file_academic_provider_v1_provider_proto_goTypes = nil
	file_academic_provider_v1_provider_proto_depIdxs = nil
}
