// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: academic/execution/v1/execution.proto

package academicexecutionv1

import (
	v11 "github.com/LDouble/campus-academic-api/pkg/academic/archive/v1"
	v1 "github.com/LDouble/campus-academic-api/pkg/academic/credentials/v1"
	v12 "github.com/LDouble/campus-academic-api/pkg/academic/provider/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ExecutionLease 仅通过受保护 RPC 传递，租约票据不得写入队列或日志。
type ExecutionLease struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	AttemptId     string                 `protobuf:"bytes,2,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	LeaseToken    string                 `protobuf:"bytes,3,opt,name=lease_token,json=leaseToken,proto3" json:"lease_token,omitempty"`
	Fence         uint64                 `protobuf:"varint,4,opt,name=fence,proto3" json:"fence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionLease) Reset() {
	*x = ExecutionLease{}
	mi := &file_academic_execution_v1_execution_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionLease) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionLease) ProtoMessage() {}

func (x *ExecutionLease) ProtoReflect() protoreflect.Message {
	mi := &file_academic_execution_v1_execution_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionLease.ProtoReflect.Descriptor instead.
func (*ExecutionLease) Descriptor() ([]byte, []int) {
	return file_academic_execution_v1_execution_proto_rawDescGZIP(), []int{0}
}

func (x *ExecutionLease) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ExecutionLease) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *ExecutionLease) GetLeaseToken() string {
	if x != nil {
		return x.LeaseToken
	}
	return ""
}

func (x *ExecutionLease) GetFence() uint64 {
	if x != nil {
		return x.Fence
	}
	return 0
}

type ExecuteManagedQueryRequest struct {
	state                 protoimpl.MessageState  `protogen:"open.v1"`
	Lease                 *ExecutionLease         `protobuf:"bytes,1,opt,name=lease,proto3" json:"lease,omitempty"`
	Credential            *v1.CredentialReference `protobuf:"bytes,2,opt,name=credential,proto3" json:"credential,omitempty"`
	CredentialAccessToken string                  `protobuf:"bytes,3,opt,name=credential_access_token,json=credentialAccessToken,proto3" json:"credential_access_token,omitempty"`
	Purpose               string                  `protobuf:"bytes,4,opt,name=purpose,proto3" json:"purpose,omitempty"`
	PeriodId              string                  `protobuf:"bytes,5,opt,name=period_id,json=periodId,proto3" json:"period_id,omitempty"`
	ForceRefresh          bool                    `protobuf:"varint,6,opt,name=force_refresh,json=forceRefresh,proto3" json:"force_refresh,omitempty"`
	OmitResult            bool                    `protobuf:"varint,7,opt,name=omit_result,json=omitResult,proto3" json:"omit_result,omitempty"`
	ExpiresAt             *timestamppb.Timestamp  `protobuf:"bytes,8,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ExecuteManagedQueryRequest) Reset() {
	*x = ExecuteManagedQueryRequest{}
	mi := &file_academic_execution_v1_execution_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteManagedQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteManagedQueryRequest) ProtoMessage() {}

func (x *ExecuteManagedQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_academic_execution_v1_execution_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteManagedQueryRequest.ProtoReflect.Descriptor instead.
func (*ExecuteManagedQueryRequest) Descriptor() ([]byte, []int) {
	return file_academic_execution_v1_execution_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteManagedQueryRequest) GetLease() *ExecutionLease {
	if x != nil {
		return x.Lease
	}
	return nil
}

func (x *ExecuteManagedQueryRequest) GetCredential() *v1.CredentialReference {
	if x != nil {
		return x.Credential
	}
	return nil
}

func (x *ExecuteManagedQueryRequest) GetCredentialAccessToken() string {
	if x != nil {
		return x.CredentialAccessToken
	}
	return ""
}

func (x *ExecuteManagedQueryRequest) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *ExecuteManagedQueryRequest) GetPeriodId() string {
	if x != nil {
		return x.PeriodId
	}
	return ""
}

func (x *ExecuteManagedQueryRequest) GetForceRefresh() bool {
	if x != nil {
		return x.ForceRefresh
	}
	return false
}

func (x *ExecuteManagedQueryRequest) GetOmitResult() bool {
	if x != nil {
		return x.OmitResult
	}
	return false
}

func (x *ExecuteManagedQueryRequest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type ExecuteManagedQueryResponse struct {
	state       protoimpl.MessageState    `protogen:"open.v1"`
	Result      *QueryResult              `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Observation *v11.ObservationReference `protobuf:"bytes,2,opt,name=observation,proto3" json:"observation,omitempty"`
	// CacheSource 取值为 upstream、fresh 或 stale。
	CacheSource   string `protobuf:"bytes,3,opt,name=cache_source,json=cacheSource,proto3" json:"cache_source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteManagedQueryResponse) Reset() {
	*x = ExecuteManagedQueryResponse{}
	mi := &file_academic_execution_v1_execution_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteManagedQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteManagedQueryResponse) ProtoMessage() {}

func (x *ExecuteManagedQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_academic_execution_v1_execution_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteManagedQueryResponse.ProtoReflect.Descriptor instead.
func (*ExecuteManagedQueryResponse) Descriptor() ([]byte, []int) {
	return file_academic_execution_v1_execution_proto_rawDescGZIP(), []int{2}
}

func (x *ExecuteManagedQueryResponse) GetResult() *QueryResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ExecuteManagedQueryResponse) GetObservation() *v11.ObservationReference {
	if x != nil {
		return x.Observation
	}
	return nil
}

func (x *ExecuteManagedQueryResponse) GetCacheSource() string {
	if x != nil {
		return x.CacheSource
	}
	return ""
}

type QueryResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*QueryResult_Courses
	//	*QueryResult_Exams
	//	*QueryResult_Grades
	//	*QueryResult_CourseSelections
	//	*QueryResult_CourseSelectionSchedule
	//	*QueryResult_CourseAdditionResults
	Result        isQueryResult_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResult) Reset() {
	*x = QueryResult{}
	mi := &file_academic_execution_v1_execution_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResult) ProtoMessage() {}

func (x *QueryResult) ProtoReflect() protoreflect.Message {
	mi := &file_academic_execution_v1_execution_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResult.ProtoReflect.Descriptor instead.
func (*QueryResult) Descriptor() ([]byte, []int) {
	return file_academic_execution_v1_execution_proto_rawDescGZIP(), []int{3}
}

func (x *QueryResult) GetResult() isQueryResult_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *QueryResult) GetCourses() *v12.ListCoursesResponse {
	if x != nil {
		if x, ok := x.Result.(*QueryResult_Courses); ok {
			return x.Courses
		}
	}
	return nil
}

func (x *QueryResult) GetExams() *v12.ListExamsResponse {
	if x != nil {
		if x, ok := x.Result.(*QueryResult_Exams); ok {
			return x.Exams
		}
	}
	return nil
}

func (x *QueryResult) GetGrades() *v12.ListGradesResponse {
	if x != nil {
		if x, ok := x.Result.(*QueryResult_Grades); ok {
			return x.Grades
		}
	}
	return nil
}

func (x *QueryResult) GetCourseSelections() *v12.ListCourseSelectionsResponse {
	if x != nil {
		if x, ok := x.Result.(*QueryResult_CourseSelections); ok {
			return x.CourseSelections
		}
	}
	return nil
}

func (x *QueryResult) GetCourseSelectionSchedule() *v12.GetCourseSelectionScheduleResponse {
	if x != nil {
		if x, ok := x.Result.(*QueryResult_CourseSelectionSchedule); ok {
			return x.CourseSelectionSchedule
		}
	}
	return nil
}

func (x *QueryResult) GetCourseAdditionResults() *v12.ListCourseAdditionResultsResponse {
	if x != nil {
		if x, ok := x.Result.(*QueryResult_CourseAdditionResults); ok {
			return x.CourseAdditionResults
		}
	}
	return nil
}

type isQueryResult_Result interface {
	isQueryResult_Result()
}

type QueryResult_Courses struct {
	Courses *v12.ListCoursesResponse `protobuf:"bytes,1,opt,name=courses,proto3,oneof"`
}

type QueryResult_Exams struct {
	Exams *v12.ListExamsResponse `protobuf:"bytes,2,opt,name=exams,proto3,oneof"`
}

type QueryResult_Grades struct {
	Grades *v12.ListGradesResponse `protobuf:"bytes,3,opt,name=grades,proto3,oneof"`
}

type QueryResult_CourseSelections struct {
	CourseSelections *v12.ListCourseSelectionsResponse `protobuf:"bytes,4,opt,name=course_selections,json=courseSelections,proto3,oneof"`
}

type QueryResult_CourseSelectionSchedule struct {
	CourseSelectionSchedule *v12.GetCourseSelectionScheduleResponse `protobuf:"bytes,5,opt,name=course_selection_schedule,json=courseSelectionSchedule,proto3,oneof"`
}

type QueryResult_CourseAdditionResults struct {
	CourseAdditionResults *v12.ListCourseAdditionResultsResponse `protobuf:"bytes,6,opt,name=course_addition_results,json=courseAdditionResults,proto3,oneof"`
}

func (*QueryResult_Courses) isQueryResult_Result() {}

func (*QueryResult_Exams) isQueryResult_Result() {}

func (*QueryResult_Grades) isQueryResult_Result() {}

func (*QueryResult_CourseSelections) isQueryResult_Result() {}

func (*QueryResult_CourseSelectionSchedule) isQueryResult_Result() {}

func (*QueryResult_CourseAdditionResults) isQueryResult_Result() {}

type CheckExecutionAdmissionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Lease *ExecutionLease        `protobuf:"bytes,1,opt,name=lease,proto3" json:"lease,omitempty"`
	// Phase 取值为 begin、external、session 或 result；begin 只可获准一次。
	Phase         string `protobuf:"bytes,2,opt,name=phase,proto3" json:"phase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckExecutionAdmissionRequest) Reset() {
	*x = CheckExecutionAdmissionRequest{}
	mi := &file_academic_execution_v1_execution_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckExecutionAdmissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckExecutionAdmissionRequest) ProtoMessage() {}

func (x *CheckExecutionAdmissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_academic_execution_v1_execution_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckExecutionAdmissionRequest.ProtoReflect.Descriptor instead.
func (*CheckExecutionAdmissionRequest) Descriptor() ([]byte, []int) {
	return file_academic_execution_v1_execution_proto_rawDescGZIP(), []int{4}
}

func (x *CheckExecutionAdmissionRequest) GetLease() *ExecutionLease {
	if x != nil {
		return x.Lease
	}
	return nil
}

func (x *CheckExecutionAdmissionRequest) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

type CheckExecutionAdmissionResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Allowed       bool                    `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Subject       *v1.Subject             `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Credential    *v1.CredentialReference `protobuf:"bytes,3,opt,name=credential,proto3" json:"credential,omitempty"`
	Purpose       string                  `protobuf:"bytes,4,opt,name=purpose,proto3" json:"purpose,omitempty"`
	PeriodId      string                  `protobuf:"bytes,5,opt,name=period_id,json=periodId,proto3" json:"period_id,omitempty"`
	ForceRefresh  bool                    `protobuf:"varint,6,opt,name=force_refresh,json=forceRefresh,proto3" json:"force_refresh,omitempty"`
	OmitResult    bool                    `protobuf:"varint,7,opt,name=omit_result,json=omitResult,proto3" json:"omit_result,omitempty"`
	ExpiresAt     *timestamppb.Timestamp  `protobuf:"bytes,8,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	ErrorCode     string                  `protobuf:"bytes,9,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckExecutionAdmissionResponse) Reset() {
	*x = CheckExecutionAdmissionResponse{}
	mi := &file_academic_execution_v1_execution_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckExecutionAdmissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckExecutionAdmissionResponse) ProtoMessage() {}

func (x *CheckExecutionAdmissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_academic_execution_v1_execution_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckExecutionAdmissionResponse.ProtoReflect.Descriptor instead.
func (*CheckExecutionAdmissionResponse) Descriptor() ([]byte, []int) {
	return file_academic_execution_v1_execution_proto_rawDescGZIP(), []int{5}
}

func (x *CheckExecutionAdmissionResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *CheckExecutionAdmissionResponse) GetSubject() *v1.Subject {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *CheckExecutionAdmissionResponse) GetCredential() *v1.CredentialReference {
	if x != nil {
		return x.Credential
	}
	return nil
}

func (x *CheckExecutionAdmissionResponse) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *CheckExecutionAdmissionResponse) GetPeriodId() string {
	if x != nil {
		return x.PeriodId
	}
	return ""
}

func (x *CheckExecutionAdmissionResponse) GetForceRefresh() bool {
	if x != nil {
		return x.ForceRefresh
	}
	return false
}

func (x *CheckExecutionAdmissionResponse) GetOmitResult() bool {
	if x != nil {
		return x.OmitResult
	}
	return false
}

func (x *CheckExecutionAdmissionResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *CheckExecutionAdmissionResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

type RegisterObservationRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Lease         *ExecutionLease           `protobuf:"bytes,1,opt,name=lease,proto3" json:"lease,omitempty"`
	Observation   *v11.ObservationReference `protobuf:"bytes,2,opt,name=observation,proto3" json:"observation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterObservationRequest) Reset() {
	*x = RegisterObservationRequest{}
	mi := &file_academic_execution_v1_execution_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterObservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterObservationRequest) ProtoMessage() {}

func (x *RegisterObservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_academic_execution_v1_execution_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterObservationRequest.ProtoReflect.Descriptor instead.
func (*RegisterObservationRequest) Descriptor() ([]byte, []int) {
	return file_academic_execution_v1_execution_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterObservationRequest) GetLease() *ExecutionLease {
	if x != nil {
		return x.Lease
	}
	return nil
}

func (x *RegisterObservationRequest) GetObservation() *v11.ObservationReference {
	if x != nil {
		return x.Observation
	}
	return nil
}

type RegisterObservationResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Allowed bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	// 同一尝试只能绑定相同观察；成功后取消不得改写该固定观察。
	Observation   *v11.ObservationReference `protobuf:"bytes,2,opt,name=observation,proto3" json:"observation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterObservationResponse) Reset() {
	*x = RegisterObservationResponse{}
	mi := &file_academic_execution_v1_execution_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterObservationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterObservationResponse) ProtoMessage() {}

func (x *RegisterObservationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_academic_execution_v1_execution_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterObservationResponse.ProtoReflect.Descriptor instead.
func (*RegisterObservationResponse) Descriptor() ([]byte, []int) {
	return file_academic_execution_v1_execution_proto_rawDescGZIP(), []int{7}
}

func (x *RegisterObservationResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *RegisterObservationResponse) GetObservation() *v11.ObservationReference {
	if x != nil {
		return x.Observation
	}
	return nil
}

// FenceExecutionRequest 隔离旧身份或指定凭据版本；两种水位不可互相替代。
type FenceExecutionRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	UserId uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// 非零时拒绝该用户所有不高于此值的身份版本。
	IdentityVersion uint64 `protobuf:"varint,2,opt,name=identity_version,json=identityVersion,proto3" json:"identity_version,omitempty"`
	// 凭据级隔离必须同时给出这三个字段，且不阻止其他凭据引用。
	CredentialId       string `protobuf:"bytes,3,opt,name=credential_id,json=credentialId,proto3" json:"credential_id,omitempty"`
	CredentialRevision uint64 `protobuf:"varint,4,opt,name=credential_revision,json=credentialRevision,proto3" json:"credential_revision,omitempty"`
	GrantEpoch         uint64 `protobuf:"varint,5,opt,name=grant_epoch,json=grantEpoch,proto3" json:"grant_epoch,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *FenceExecutionRequest) Reset() {
	*x = FenceExecutionRequest{}
	mi := &file_academic_execution_v1_execution_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FenceExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FenceExecutionRequest) ProtoMessage() {}

func (x *FenceExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_academic_execution_v1_execution_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FenceExecutionRequest.ProtoReflect.Descriptor instead.
func (*FenceExecutionRequest) Descriptor() ([]byte, []int) {
	return file_academic_execution_v1_execution_proto_rawDescGZIP(), []int{8}
}

func (x *FenceExecutionRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FenceExecutionRequest) GetIdentityVersion() uint64 {
	if x != nil {
		return x.IdentityVersion
	}
	return 0
}

func (x *FenceExecutionRequest) GetCredentialId() string {
	if x != nil {
		return x.CredentialId
	}
	return ""
}

func (x *FenceExecutionRequest) GetCredentialRevision() uint64 {
	if x != nil {
		return x.CredentialRevision
	}
	return 0
}

func (x *FenceExecutionRequest) GetGrantEpoch() uint64 {
	if x != nil {
		return x.GrantEpoch
	}
	return 0
}

type FenceExecutionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FenceExecutionResponse) Reset() {
	*x = FenceExecutionResponse{}
	mi := &file_academic_execution_v1_execution_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FenceExecutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FenceExecutionResponse) ProtoMessage() {}

func (x *FenceExecutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_academic_execution_v1_execution_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FenceExecutionResponse.ProtoReflect.Descriptor instead.
func (*FenceExecutionResponse) Descriptor() ([]byte, []int) {
	return file_academic_execution_v1_execution_proto_rawDescGZIP(), []int{9}
}

func (x *FenceExecutionResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

var File_academic_execution_v1_execution_proto protoreflect.FileDescriptor

const file_academic_execution_v1_execution_proto_rawDesc = "" +
	"\n" +
	"%academic/execution/v1/execution.proto\x12\x15academic.execution.v1\x1a!academic/archive/v1/archive.proto\x1a)academic/credentials/v1/credentials.proto\x1a#academic/provider/v1/provider.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x7f\n" +
	"\x0eExecutionLease\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x02 \x01(\tR\tattemptId\x12\x1f\n" +
	"\vlease_token\x18\x03 \x01(\tR\n" +
	"leaseToken\x12\x14\n" +
	"\x05fence\x18\x04 \x01(\x04R\x05fence\"\x97\x03\n" +
	"\x1aExecuteManagedQueryRequest\x12;\n" +
	"\x05lease\x18\x01 \x01(\v2%.academic.execution.v1.ExecutionLeaseR\x05lease\x12L\n" +
	"\n" +
	"credential\x18\x02 \x01(\v2,.academic.credentials.v1.CredentialReferenceR\n" +
	"credential\x126\n" +
	"\x17credential_access_token\x18\x03 \x01(\tR\x15credentialAccessToken\x12\x18\n" +
	"\apurpose\x18\x04 \x01(\tR\apurpose\x12\x1b\n" +
	"\tperiod_id\x18\x05 \x01(\tR\bperiodId\x12#\n" +
	"\rforce_refresh\x18\x06 \x01(\bR\fforceRefresh\x12\x1f\n" +
	"\vomit_result\x18\a \x01(\bR\n" +
	"omitResult\x129\n" +
	"\n" +
	"expires_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\xc9\x01\n" +
	"\x1bExecuteManagedQueryResponse\x12:\n" +
	"\x06result\x18\x01 \x01(\v2\".academic.execution.v1.QueryResultR\x06result\x12K\n" +
	"\vobservation\x18\x02 \x01(\v2).academic.archive.v1.ObservationReferenceR\vobservation\x12!\n" +
	"\fcache_source\x18\x03 \x01(\tR\vcacheSource\"\xb1\x04\n" +
	"\vQueryResult\x12E\n" +
	"\acourses\x18\x01 \x01(\v2).academic.provider.v1.ListCoursesResponseH\x00R\acourses\x12?\n" +
	"\x05exams\x18\x02 \x01(\v2'.academic.provider.v1.ListExamsResponseH\x00R\x05exams\x12B\n" +
	"\x06grades\x18\x03 \x01(\v2(.academic.provider.v1.ListGradesResponseH\x00R\x06grades\x12a\n" +
	"\x11course_selections\x18\x04 \x01(\v22.academic.provider.v1.ListCourseSelectionsResponseH\x00R\x10courseSelections\x12v\n" +
	"\x19course_selection_schedule\x18\x05 \x01(\v28.academic.provider.v1.GetCourseSelectionScheduleResponseH\x00R\x17courseSelectionSchedule\x12q\n" +
	"\x17course_addition_results\x18\x06 \x01(\v27.academic.provider.v1.ListCourseAdditionResultsResponseH\x00R\x15courseAdditionResultsB\b\n" +
	"\x06result\"s\n" +
	"\x1eCheckExecutionAdmissionRequest\x12;\n" +
	"\x05lease\x18\x01 \x01(\v2%.academic.execution.v1.ExecutionLeaseR\x05lease\x12\x14\n" +
	"\x05phase\x18\x02 \x01(\tR\x05phase\"\x9c\x03\n" +
	"\x1fCheckExecutionAdmissionResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12:\n" +
	"\asubject\x18\x02 \x01(\v2 .academic.credentials.v1.SubjectR\asubject\x12L\n" +
	"\n" +
	"credential\x18\x03 \x01(\v2,.academic.credentials.v1.CredentialReferenceR\n" +
	"credential\x12\x18\n" +
	"\apurpose\x18\x04 \x01(\tR\apurpose\x12\x1b\n" +
	"\tperiod_id\x18\x05 \x01(\tR\bperiodId\x12#\n" +
	"\rforce_refresh\x18\x06 \x01(\bR\fforceRefresh\x12\x1f\n" +
	"\vomit_result\x18\a \x01(\bR\n" +
	"omitResult\x129\n" +
	"\n" +
	"expires_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x1d\n" +
	"\n" +
	"error_code\x18\t \x01(\tR\terrorCode\"\xa6\x01\n" +
	"\x1aRegisterObservationRequest\x12;\n" +
	"\x05lease\x18\x01 \x01(\v2%.academic.execution.v1.ExecutionLeaseR\x05lease\x12K\n" +
	"\vobservation\x18\x02 \x01(\v2).academic.archive.v1.ObservationReferenceR\vobservation\"\x84\x01\n" +
	"\x1bRegisterObservationResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12K\n" +
	"\vobservation\x18\x02 \x01(\v2).academic.archive.v1.ObservationReferenceR\vobservation\"\xd2\x01\n" +
	"\x15FenceExecutionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12)\n" +
	"\x10identity_version\x18\x02 \x01(\x04R\x0fidentityVersion\x12#\n" +
	"\rcredential_id\x18\x03 \x01(\tR\fcredentialId\x12/\n" +
	"\x13credential_revision\x18\x04 \x01(\x04R\x12credentialRevision\x12\x1f\n" +
	"\vgrant_epoch\x18\x05 \x01(\x04R\n" +
	"grantEpoch\"<\n" +
	"\x16FenceExecutionResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged2\x87\x02\n" +
	"\x18AcademicExecutionService\x12|\n" +
	"\x13ExecuteManagedQuery\x121.academic.execution.v1.ExecuteManagedQueryRequest\x1a2.academic.execution.v1.ExecuteManagedQueryResponse\x12m\n" +
	"\x0eFenceExecution\x12,.academic.execution.v1.FenceExecutionRequest\x1a-.academic.execution.v1.FenceExecutionResponse2\xac\x02\n" +
	"!AcademicExecutionAuthorityService\x12\x88\x01\n" +
	"\x17CheckExecutionAdmission\x125.academic.execution.v1.CheckExecutionAdmissionRequest\x1a6.academic.execution.v1.CheckExecutionAdmissionResponse\x12|\n" +
	"\x13RegisterObservation\x121.academic.execution.v1.RegisterObservationRequest\x1a2.academic.execution.v1.RegisterObservationResponseBVZTgithub.com/LDouble/campus-academic-api/pkg/academic/execution/v1;academicexecutionv1b\x06proto3"

var (
	file_academic_execution_v1_execution_proto_rawDescOnce sync.Once
	file_academic_execution_v1_execution_proto_rawDescData []byte
)

func file_academic_execution_v1_execution_proto_rawDescGZIP() []byte {
	file_academic_execution_v1_execution_proto_rawDescOnce.Do(func() {
		file_academic_execution_v1_execution_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_academic_execution_v1_execution_proto_rawDesc), len(file_academic_execution_v1_execution_proto_rawDesc)))
	})
	return file_academic_execution_v1_execution_proto_rawDescData
}

var file_academic_execution_v1_execution_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_academic_execution_v1_execution_proto_goTypes = []any{
	(*ExecutionLease)(nil),                         // 0: academic.execution.v1.ExecutionLease
	(*ExecuteManagedQueryRequest)(nil),             // 1: academic.execution.v1.ExecuteManagedQueryRequest
	(*ExecuteManagedQueryResponse)(nil),            // 2: academic.execution.v1.ExecuteManagedQueryResponse
	(*QueryResult)(nil),                            // 3: academic.execution.v1.QueryResult
	(*CheckExecutionAdmissionRequest)(nil),         // 4: academic.execution.v1.CheckExecutionAdmissionRequest
	(*CheckExecutionAdmissionResponse)(nil),        // 5: academic.execution.v1.CheckExecutionAdmissionResponse
	(*RegisterObservationRequest)(nil),             // 6: academic.execution.v1.RegisterObservationRequest
	(*RegisterObservationResponse)(nil),            // 7: academic.execution.v1.RegisterObservationResponse
	(*FenceExecutionRequest)(nil),                  // 8: academic.execution.v1.FenceExecutionRequest
	(*FenceExecutionResponse)(nil),                 // 9: academic.execution.v1.FenceExecutionResponse
	(*v1.CredentialReference)(nil),                 // 10: academic.credentials.v1.CredentialReference
	(*timestamppb.Timestamp)(nil),                  // 11: google.protobuf.Timestamp
	(*v11.ObservationReference)(nil),               // 12: academic.archive.v1.ObservationReference
	(*v12.ListCoursesResponse)(nil),                // 13: academic.provider.v1.ListCoursesResponse
	(*v12.ListExamsResponse)(nil),                  // 14: academic.provider.v1.ListExamsResponse
	(*v12.ListGradesResponse)(nil),                 // 15: academic.provider.v1.ListGradesResponse
	(*v12.ListCourseSelectionsResponse)(nil),       // 16: academic.provider.v1.ListCourseSelectionsResponse
	(*v12.GetCourseSelectionScheduleResponse)(nil), // 17: academic.provider.v1.GetCourseSelectionScheduleResponse
	(*v12.ListCourseAdditionResultsResponse)(nil),  // 18: academic.provider.v1.ListCourseAdditionResultsResponse
	(*v1.Subject)(nil),                             // 19: academic.credentials.v1.Subject
}
var file_academic_execution_v1_execution_proto_depIdxs = []int32{
	0,  // 0: academic.execution.v1.ExecuteManagedQueryRequest.lease:type_name -> academic.execution.v1.ExecutionLease
	10, // 1: academic.execution.v1.ExecuteManagedQueryRequest.credential:type_name -> academic.credentials.v1.CredentialReference
	11, // 2: academic.execution.v1.ExecuteManagedQueryRequest.expires_at:type_name -> google.protobuf.Timestamp
	3,  // 3: academic.execution.v1.ExecuteManagedQueryResponse.result:type_name -> academic.execution.v1.QueryResult
	12, // 4: academic.execution.v1.ExecuteManagedQueryResponse.observation:type_name -> academic.archive.v1.ObservationReference
	13, // 5: academic.execution.v1.QueryResult.courses:type_name -> academic.provider.v1.ListCoursesResponse
	14, // 6: academic.execution.v1.QueryResult.exams:type_name -> academic.provider.v1.ListExamsResponse
	15, // 7: academic.execution.v1.QueryResult.grades:type_name -> academic.provider.v1.ListGradesResponse
	16, // 8: academic.execution.v1.QueryResult.course_selections:type_name -> academic.provider.v1.ListCourseSelectionsResponse
	17, // 9: academic.execution.v1.QueryResult.course_selection_schedule:type_name -> academic.provider.v1.GetCourseSelectionScheduleResponse
	18, // 10: academic.execution.v1.QueryResult.course_addition_results:type_name -> academic.provider.v1.ListCourseAdditionResultsResponse
	0,  // 11: academic.execution.v1.CheckExecutionAdmissionRequest.lease:type_name -> academic.execution.v1.ExecutionLease
	19, // 12: academic.execution.v1.CheckExecutionAdmissionResponse.subject:type_name -> academic.credentials.v1.Subject
	10, // 13: academic.execution.v1.CheckExecutionAdmissionResponse.credential:type_name -> academic.credentials.v1.CredentialReference
	11, // 14: academic.execution.v1.CheckExecutionAdmissionResponse.expires_at:type_name -> google.protobuf.Timestamp
	0,  // 15: academic.execution.v1.RegisterObservationRequest.lease:type_name -> academic.execution.v1.ExecutionLease
	12, // 16: academic.execution.v1.RegisterObservationRequest.observation:type_name -> academic.archive.v1.ObservationReference
	12, // 17: academic.execution.v1.RegisterObservationResponse.observation:type_name -> academic.archive.v1.ObservationReference
	1,  // 18: academic.execution.v1.AcademicExecutionService.ExecuteManagedQuery:input_type -> academic.execution.v1.ExecuteManagedQueryRequest
	8,  // 19: academic.execution.v1.AcademicExecutionService.FenceExecution:input_type -> academic.execution.v1.FenceExecutionRequest
	4,  // 20: academic.execution.v1.AcademicExecutionAuthorityService.CheckExecutionAdmission:input_type -> academic.execution.v1.CheckExecutionAdmissionRequest
	6,  // 21: academic.execution.v1.AcademicExecutionAuthorityService.RegisterObservation:input_type -> academic.execution.v1.RegisterObservationRequest
	2,  // 22: academic.execution.v1.AcademicExecutionService.ExecuteManagedQuery:output_type -> academic.execution.v1.ExecuteManagedQueryResponse
	9,  // 23: academic.execution.v1.AcademicExecutionService.FenceExecution:output_type -> academic.execution.v1.FenceExecutionResponse
	5,  // 24: academic.execution.v1.AcademicExecutionAuthorityService.CheckExecutionAdmission:output_type -> academic.execution.v1.CheckExecutionAdmissionResponse
	7,  // 25: academic.execution.v1.AcademicExecutionAuthorityService.RegisterObservation:output_type -> academic.execution.v1.RegisterObservationResponse
	22, // [22:26] is the sub-list for method output_type
	18, // [18:22] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_academic_execution_v1_execution_proto_init() }
func file_academic_execution_v1_execution_proto_init() {
	if File_academic_execution_v1_execution_proto != nil {
		return
	}
	file_academic_execution_v1_execution_proto_msgTypes[3].OneofWrappers = []any{
		(*QueryResult_Courses)(nil),
		(*QueryResult_Exams)(nil),
		(*QueryResult_Grades)(nil),
		(*QueryResult_CourseSelections)(nil),
		(*QueryResult_CourseSelectionSchedule)(nil),
		(*QueryResult_CourseAdditionResults)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_academic_execution_v1_execution_proto_rawDesc), len(file_academic_execution_v1_execution_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_academic_execution_v1_execution_proto_goTypes,
		DependencyIndexes: file_academic_execution_v1_execution_proto_depIdxs,
		MessageInfos:      file_academic_execution_v1_execution_proto_msgTypes,
	}.Build()
	File_academic_execution_v1_execution_proto = out.File
	file_academic_execution_v1_execution_proto_goTypes = nil
	file_academic_execution_v1_execution_proto_depIdxs = nil
}
