// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: academic/execution/v1/execution.proto

package academicexecutionv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AcademicExecutionService_ExecuteManagedQuery_FullMethodName = "/academic.execution.v1.AcademicExecutionService/ExecuteManagedQuery"
	AcademicExecutionService_FenceExecution_FullMethodName      = "/academic.execution.v1.AcademicExecutionService/FenceExecution"
)

// AcademicExecutionServiceClient is the client API for AcademicExecutionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AcademicExecutionService 在 Provider 内执行一次平台已授权的查询，不持有任务队列。
type AcademicExecutionServiceClient interface {
	ExecuteManagedQuery(ctx context.Context, in *ExecuteManagedQueryRequest, opts ...grpc.CallOption) (*ExecuteManagedQueryResponse, error)
	FenceExecution(ctx context.Context, in *FenceExecutionRequest, opts ...grpc.CallOption) (*FenceExecutionResponse, error)
}

type academicExecutionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAcademicExecutionServiceClient(cc grpc.ClientConnInterface) AcademicExecutionServiceClient {
	return &academicExecutionServiceClient{cc}
}

func (c *academicExecutionServiceClient) ExecuteManagedQuery(ctx context.Context, in *ExecuteManagedQueryRequest, opts ...grpc.CallOption) (*ExecuteManagedQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteManagedQueryResponse)
	err := c.cc.Invoke(ctx, AcademicExecutionService_ExecuteManagedQuery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *academicExecutionServiceClient) FenceExecution(ctx context.Context, in *FenceExecutionRequest, opts ...grpc.CallOption) (*FenceExecutionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FenceExecutionResponse)
	err := c.cc.Invoke(ctx, AcademicExecutionService_FenceExecution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AcademicExecutionServiceServer is the server API for AcademicExecutionService service.
// All implementations must embed UnimplementedAcademicExecutionServiceServer
// for forward compatibility.
//
// AcademicExecutionService 在 Provider 内执行一次平台已授权的查询，不持有任务队列。
type AcademicExecutionServiceServer interface {
	ExecuteManagedQuery(context.Context, *ExecuteManagedQueryRequest) (*ExecuteManagedQueryResponse, error)
	FenceExecution(context.Context, *FenceExecutionRequest) (*FenceExecutionResponse, error)
	mustEmbedUnimplementedAcademicExecutionServiceServer()
}

// UnimplementedAcademicExecutionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAcademicExecutionServiceServer struct{}

func (UnimplementedAcademicExecutionServiceServer) ExecuteManagedQuery(context.Context, *ExecuteManagedQueryRequest) (*ExecuteManagedQueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteManagedQuery not implemented")
}
func (UnimplementedAcademicExecutionServiceServer) FenceExecution(context.Context, *FenceExecutionRequest) (*FenceExecutionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FenceExecution not implemented")
}
func (UnimplementedAcademicExecutionServiceServer) mustEmbedUnimplementedAcademicExecutionServiceServer() {
}
func (UnimplementedAcademicExecutionServiceServer) testEmbeddedByValue() {}

// UnsafeAcademicExecutionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AcademicExecutionServiceServer will
// result in compilation errors.
type UnsafeAcademicExecutionServiceServer interface {
	mustEmbedUnimplementedAcademicExecutionServiceServer()
}

func RegisterAcademicExecutionServiceServer(s grpc.ServiceRegistrar, srv AcademicExecutionServiceServer) {
	// If the following call panics, it indicates UnimplementedAcademicExecutionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AcademicExecutionService_ServiceDesc, srv)
}

func _AcademicExecutionService_ExecuteManagedQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteManagedQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcademicExecutionServiceServer).ExecuteManagedQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AcademicExecutionService_ExecuteManagedQuery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcademicExecutionServiceServer).ExecuteManagedQuery(ctx, req.(*ExecuteManagedQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AcademicExecutionService_FenceExecution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FenceExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcademicExecutionServiceServer).FenceExecution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AcademicExecutionService_FenceExecution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcademicExecutionServiceServer).FenceExecution(ctx, req.(*FenceExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AcademicExecutionService_ServiceDesc is the grpc.ServiceDesc for AcademicExecutionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AcademicExecutionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "academic.execution.v1.AcademicExecutionService",
	HandlerType: (*AcademicExecutionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteManagedQuery",
			Handler:    _AcademicExecutionService_ExecuteManagedQuery_Handler,
		},
		{
			MethodName: "FenceExecution",
			Handler:    _AcademicExecutionService_FenceExecution_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "academic/execution/v1/execution.proto",
}

const (
	AcademicExecutionAuthorityService_CheckExecutionAdmission_FullMethodName = "/academic.execution.v1.AcademicExecutionAuthorityService/CheckExecutionAdmission"
	AcademicExecutionAuthorityService_RegisterObservation_FullMethodName     = "/academic.execution.v1.AcademicExecutionAuthorityService/RegisterObservation"
)

// AcademicExecutionAuthorityServiceClient is the client API for AcademicExecutionAuthorityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AcademicExecutionAuthorityService 由平台任务模块提供任务租约和用途的权威准入。
type AcademicExecutionAuthorityServiceClient interface {
	CheckExecutionAdmission(ctx context.Context, in *CheckExecutionAdmissionRequest, opts ...grpc.CallOption) (*CheckExecutionAdmissionResponse, error)
	RegisterObservation(ctx context.Context, in *RegisterObservationRequest, opts ...grpc.CallOption) (*RegisterObservationResponse, error)
}

type academicExecutionAuthorityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAcademicExecutionAuthorityServiceClient(cc grpc.ClientConnInterface) AcademicExecutionAuthorityServiceClient {
	return &academicExecutionAuthorityServiceClient{cc}
}

func (c *academicExecutionAuthorityServiceClient) CheckExecutionAdmission(ctx context.Context, in *CheckExecutionAdmissionRequest, opts ...grpc.CallOption) (*CheckExecutionAdmissionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckExecutionAdmissionResponse)
	err := c.cc.Invoke(ctx, AcademicExecutionAuthorityService_CheckExecutionAdmission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *academicExecutionAuthorityServiceClient) RegisterObservation(ctx context.Context, in *RegisterObservationRequest, opts ...grpc.CallOption) (*RegisterObservationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterObservationResponse)
	err := c.cc.Invoke(ctx, AcademicExecutionAuthorityService_RegisterObservation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AcademicExecutionAuthorityServiceServer is the server API for AcademicExecutionAuthorityService service.
// All implementations must embed UnimplementedAcademicExecutionAuthorityServiceServer
// for forward compatibility.
//
// AcademicExecutionAuthorityService 由平台任务模块提供任务租约和用途的权威准入。
type AcademicExecutionAuthorityServiceServer interface {
	CheckExecutionAdmission(context.Context, *CheckExecutionAdmissionRequest) (*CheckExecutionAdmissionResponse, error)
	RegisterObservation(context.Context, *RegisterObservationRequest) (*RegisterObservationResponse, error)
	mustEmbedUnimplementedAcademicExecutionAuthorityServiceServer()
}

// UnimplementedAcademicExecutionAuthorityServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAcademicExecutionAuthorityServiceServer struct{}

func (UnimplementedAcademicExecutionAuthorityServiceServer) CheckExecutionAdmission(context.Context, *CheckExecutionAdmissionRequest) (*CheckExecutionAdmissionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckExecutionAdmission not implemented")
}
func (UnimplementedAcademicExecutionAuthorityServiceServer) RegisterObservation(context.Context, *RegisterObservationRequest) (*RegisterObservationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterObservation not implemented")
}
func (UnimplementedAcademicExecutionAuthorityServiceServer) mustEmbedUnimplementedAcademicExecutionAuthorityServiceServer() {
}
func (UnimplementedAcademicExecutionAuthorityServiceServer) testEmbeddedByValue() {}

// UnsafeAcademicExecutionAuthorityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AcademicExecutionAuthorityServiceServer will
// result in compilation errors.
type UnsafeAcademicExecutionAuthorityServiceServer interface {
	mustEmbedUnimplementedAcademicExecutionAuthorityServiceServer()
}

func RegisterAcademicExecutionAuthorityServiceServer(s grpc.ServiceRegistrar, srv AcademicExecutionAuthorityServiceServer) {
	// If the following call panics, it indicates UnimplementedAcademicExecutionAuthorityServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AcademicExecutionAuthorityService_ServiceDesc, srv)
}

func _AcademicExecutionAuthorityService_CheckExecutionAdmission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckExecutionAdmissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcademicExecutionAuthorityServiceServer).CheckExecutionAdmission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AcademicExecutionAuthorityService_CheckExecutionAdmission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcademicExecutionAuthorityServiceServer).CheckExecutionAdmission(ctx, req.(*CheckExecutionAdmissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AcademicExecutionAuthorityService_RegisterObservation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterObservationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcademicExecutionAuthorityServiceServer).RegisterObservation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AcademicExecutionAuthorityService_RegisterObservation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcademicExecutionAuthorityServiceServer).RegisterObservation(ctx, req.(*RegisterObservationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AcademicExecutionAuthorityService_ServiceDesc is the grpc.ServiceDesc for AcademicExecutionAuthorityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AcademicExecutionAuthorityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "academic.execution.v1.AcademicExecutionAuthorityService",
	HandlerType: (*AcademicExecutionAuthorityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckExecutionAdmission",
			Handler:    _AcademicExecutionAuthorityService_CheckExecutionAdmission_Handler,
		},
		{
			MethodName: "RegisterObservation",
			Handler:    _AcademicExecutionAuthorityService_RegisterObservation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "academic/execution/v1/execution.proto",
}
